### PR TITLE
Add brand assets

### PR DESCRIPTION
**Pull request by sweetpea22**
**Motivation**

Adding new brand assets ✨

**Description**

You'll need to delete the old ones after, didn't want to remove them yet at risk of breaking live imgs. 

suggestions: 
- use the square icon for touch icon in index.html
- when using full mark for web apps, set maxHeight to 40px 
- stacked mark works well when we're sitting next to other brands :D

### CODE REVIEW

**Review by wemeetagain — DISMISSED** [review]
:rocket: :rocket:

**Comment by wemeetagain** [comment]
@dapplion we might save & delete a few of the larger files to keep the repo size down. See https://github.com/ChainSafe/lodestar/issues/1554

**Review by dapplion — APPROVED** [review]

**Review by dapplion — DISMISSED** [review]
Agree on triming the size down a bit!

**Comment by wemeetagain** [comment]
I'm going to commit over this, removing the MB+ images. I've got them saved locally so we can still use them where desired.

**Review by wemeetagain — APPROVED** [review]

**Pull request merged**
