### PR TITLE
Remove i prefix

### PR DESCRIPTION
**Pull request by nflaig**

### CODE REVIEW

**Comment by dapplion** [comment]
@nflaig Why is the diff so big if it's only a few remaining items?

**Comment by nflaig** [comment]
@dapplion no idea tbh, some weird github behavior/bug?

I force-pushed the first commit of this branch because there was a typo in the commit message `Manuel` --> `Manual` but that's it.

The changes shown here do not make sense, for example these changes is in both branches, so it shouldn't show up as a diff here

image

**Comment by nflaig** [comment]
actual changes are done here https://github.com/ChainSafe/lodestar/pull/5145

**Comment by nflaig** [comment]
@dapplion this must be some weird bug on the github side, after you cherry-picked the last commit there is 0 diff between the two branches, at least according to `git diff`

image

**Pull request closed without merging**
