### PR TITLE
Fix Buffer api deprecation message

### PR DESCRIPTION
**Pull request by mpetrunic**
:tada:

### CODE REVIEW

**Review by wemeetagain — APPROVED** [review]
Good fix

**Comment by wemeetagain** [comment]
new linter rule found more deprecated api usage

**Review by twoeths — DISMISSED** [review]

**Review by wemeetagain — CHANGES_REQUESTED** [review]
linter errors: https://github.com/ChainSafe/lodestar/runs/835199562?check_suite_focus=true#step:7:100

**Comment by wemeetagain** [comment]
one more linter error https://github.com/ChainSafe/lodestar/pull/1087/checks?check_run_id=840924904#step:7:97

**Review by wemeetagain — APPROVED** [review]

**Pull request merged**
