### PR TITLE
docs: fix incorrect light-client example

### PR DESCRIPTION
**Pull request by jeluard**
**Motivation**

Make sure that the `light-client` example embedded in the `README.md` file compiles.

### CODE REVIEW

**Review by wemeetagain — APPROVED** [review]
Maybe we should run `yarn check-readme` in CI along with tests to keep these readmes compile-able?

**Comment by nflaig** [comment]
> Maybe we should run `yarn check-readme` in CI along with tests to keep these readmes compile-able?

We actually do
https://github.com/ChainSafe/lodestar/blob/88744d8a4877499c8c7aa43aeb4d576b98581faf/.github/workflows/test.yml#L144-L145

But it doesn't seem to care at all
```bash
~/projects/ethereum/lodestar/packages/light-client [unstable ≡ +0 ~1 -0 !]> yarn check-readme
yarn run v1.22.19
$ typescript-docs-verifier
ℹ Compiling documentation TypeScript code snippets from README.md
ℹ Found 1 TypeScript snippets
✔ All snippets compiled OK
```

@jeluard how did you verify and determine the changes to make it compile, just copy pasted it into a .ts file?

**Comment by jeluard** [comment]
@nflaig Yes, copy pasted.

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.15.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.15.0) :tada:

**Pull request merged**
