### PR TITLE
Add run-time types

### LINKED ISSUE #74: Create run-time type definitions of our interfaces
Unfortunately, typescript interfaces do not appear to be available/exist at run time.
This means that we don't have access to the type information necessary to properly serialize the data.

There is a dependency here, between our "types" and our ssz library that we should be aware of.
Our ssz library assumes a type object with a `fields` key, which it uses to serialize each field. (See [here](https://github.com/ChainSafeSystems/ssz-js/blob/master/src/index.js#L90))

Here is an example that can show the issue:
```javascript
interface ProposalSignedData {
  // Slot number
  slot: uint64;
  // Shard number (`BEACON_CHAIN_SHARD_NUMBER` for beacon chain)
  shard: uint64;
  // Block hash
  blockHash: hash32;
}

const data: ProposalSignedData = {
  slot: 0,
  shard: 0,
  blockHash: 0,
};

const serializedData: Uint8Array = ssz.serialize(data, ???); // <--- problem here
```

Perhaps a way forward would be to create a "type" object for each interface.
Something that would play nicely with ssz-js:
```javascript
const ProposalSignedData = {
  fields: [
    ['slot', 'uint64'],
    ['shard', 'uint64'],
    ['blockHash', 'hash32'],
  ],
};

// from above, problem fixed
const serializedData: Uint8Array = ssz.serialize(data, ProposalSignedData);
```

See also how the python implementation deals with this, eg: [here](https://github.com/ethereum/beacon_chain/blob/master/beacon_chain/state/block.py#L19)

### PR DESCRIPTION
**Pull request by wemeetagain**
Resolves #74 
Fits with the work done in https://github.com/ChainSafeSystems/ssz-js/pull/28 

Each `type` and `interface` declaration now has a corresponding piece of data, named identically, that should exist at runtime.
This will let us serialize objects like so:
```typescript
let x: BeaconBlock = {
  ...
};
serialize(x, BeaconBlock);
```
The first reference to BeaconBlock is the typescript interface, which disappears in the compiled javascript.
The second reference is a variable, existing in the compiled javascript, that fulfils the requirements of a ssz "type" (eg: is either an Array, a string, or an object with a `fields` attribute with the desired shape, in this case, mostly objects with `fields`)

### CODE REVIEW

**Review by ansermino — COMMENTED** [review]
I've come back to this a few times, I find the naming/format rather undesirable. This would be rather confusing for someone who is new to the code. Perhaps we can add an explanation at the top? Or move to a separate file?

**Comment by wemeetagain** [comment]
I'll add a good comment section at the top describing the two different 'type' systems we're relying on, the nature of each, why they're needed, and how they are to be used.

I think we could also move the files from the `interfaces/` directory to a `types/`directory, too, if we want it to be clear to an importer that these are _not just_ interfaces, but both compile-time and run-time types.

(Separately, the file boundary we have between `state.ts` and `blocks.ts` is not very clean, and we could consider either further file splitting, and/or unification by either import/reexport or simply file unification in a `index.ts`.)

**Comment by wemeetagain** [comment]
Just to give more context to my reasoning re: the naming and structure:

---

One alternative implementation I toyed with was using classes, which taken to its conclusion looks roughly like:
```typescript
interface BeaconBlock {
  ...
}
interface OptionalBeaconBlock {
  // same fields as BeaconBlock, but all optional
  ...
}
export class BeaconBlock implements BeaconBlock {
  static fields = [
    ...

  constructor(opts: OptionalBeaconBlock) {
    for (const [k,v] of Object.entries(opts)) {
      this[k] = v;
    }
  }
}
// ...etc for other data types

/// In another file
import {BeaconBlock, BeaconBlockBody, ...} from "../types";

let b: BeaconBlock =
  new BeaconBlock({
    ...,
    body: new BeaconBlockBody({
      ...

ssz.serialize(b, BeaconBlock);
```

Obviously overly verbose and adds a lot of machinery (when we really only need something akin to [records](https://en.wikipedia.org/wiki/Record_%28computer_science%29)), and deceptively bad (these classes should not have methods defined on them, because ssz-deserialized objects will not have access to them)
but the benefit is that we've encapsulated both the interface and runtime type into a single place.

---

Another alternative I played with was using different variable names between interfaces and runtime types:
```typescript
export interface BeaconBlock {
  ...
}

export var BeaconBlockType = {
  fields: [
    ...
  }
}

// In another file
import {BeaconBlock, BeaconBlockType} from "../types";

let b: BeaconBlock = {
  ...
}
ssz.serialize(b, BeaconBlockType);
```
Simple use of simple objects, good.
But there's a strange disconnect between the type and the other ... type. It's seen as soon as we hit the import statement. They both refer to the same concept, and if our language was more extensible/featured, we would, in a perfect world, only have a single type definition, and forgo having to manually maintain consistency across 'types'.

If we accepted the additional machinery of javascript "classes", we could unify these duplicate definitions for downstream consumers into one thing under a 'class' function. The other way, the one presented, is to mimic this, by unifying at the level of the variable name.

**Comment by GregTheGreek** [comment]
Classes may be bit over kill, especially might make things difficult when running the actual node. Not sure, I'll sit on this one.

Number 2 seems most optimal, but are you saying that theres an import collision on two seperate types?

**Comment by wemeetagain** [comment]
@GregTheGreek I'm saying that the interface and the runtime type are redundant information, and conceptually, at some level of abstraction, the same thing.

There isn't an import collision on two separate types. I was just saying that having multiple variables creates separation where there is no need or desire (imo), and because of this, makes sense to fold both into one variable.

Of course, if there's consensus to the contrary, definitely willing to update the PR accordingly.

Edit1: I can see how this is confusing. Javascript only has a single namespace for symbols, and this is taking advantage of a secondary namespace for interfaces provided by typescript.

Edit2: This is the feature being used: https://www.typescriptlang.org/docs/handbook/declaration-merging.html

**Comment by wemeetagain** [comment]
@GregTheGreek gonna add you as a reviewer too

**Comment by GregTheGreek** [comment]
@wemeetagain So sorry, didn't see this as a PR (still getting used to zenhub) thought this was an issue..

**Review by GregTheGreek — CHANGES_REQUESTED** [review]
Could you swap out `var` for `const`, otherwise everything is good :) 👍

**Comment by wemeetagain** [comment]
@GregTheGreek 
It looks like we're defining types roughly in the order specified in the eth2.0 spec.

I used `var` to not disrupt the order of the type declarations, since they are not defined in dependency order. It appears that `interface` uses a similar scoping as `var`.

Eg: `BeaconBlock` (L213) depends on `BeaconBlockBody` (L237).
Using `const` will result in errors (which aren't yet present, since we aren't using the variables, but the bug will be lurking)

**Comment by GregTheGreek** [comment]
oh interesting... we can fix it later.

**Review by GregTheGreek — APPROVED** [review]

**Pull request merged**
