### PR TITLE
Updated README with correct link for Beacon Management 

### LINKED ISSUE #4722: Bug: Broken link in README related to Beacon Management
**Describe the bug**

The current link for Beacon management in the [**Getting Started** Section of the README](https://github.com/ChainSafe/lodestar#getting-started) is broken. I suspect it should be updated to https://chainsafe.github.io/lodestar/usage/beacon-management

### PR DESCRIPTION
**Pull request by maschad**
**Motivation**

To correct the link for Beacon Management in the [Getting Started Section of the README](https://github.com/ChainSafe/lodestar#getting-started)

**Description**

This updates the README with the correct link.

Closes https://github.com/ChainSafe/lodestar/issues/4722

### CODE REVIEW

**Review by wemeetagain — APPROVED** [review]
thanks @maschad

**Review by dapplion — APPROVED** [review]
Thank you!

**Comment by wemeetagain** [comment]
not sure why CI isn't running

**Review by twoeths — APPROVED** [review]

**Comment by wemeetagain** [comment]
Gonna try closing and reopening to retrigger the CI tests

**Comment by maschad** [comment]
> Gonna try closing and reopening to retrigger the CI tests

Thanks! that triggered the tests but it looks like there was either a [flakey test or a bug that was introduced on the simulation tests](https://github.com/ChainSafe/lodestar/actions/runs/3420388314/jobs/5695143962#step:9:71) , I rebased and pushed again.

**Pull request merged**
