### PR TITLE
Persist eth1 genesis progress on error

### PR DESCRIPTION
**Pull request by dapplion**
While keeping eth1 genesis builder detached from the db, persist current progress on error.

#### How to test

To test this branch run the cli with
```
lodestar beacon --forceGenesis --rootDir ./lodestar-db
```
Then CTRL+C after it has processed 1 deposit and it will abort after a few seconds, when done processing that batch (deposit 192 in mainnet). Then run again with the same command and check the logs saying it's processing deposit 193, not deposit 1.

### CODE REVIEW

**Comment by 3xtr4t3rr3str14l** [comment]
what's the latest on this PR?  i don't have any answers to them, but are the questions in your description still open/unresolved?

**Comment by dapplion** [comment]
Still un-resolved questions and it's not a priority so it can be icebox-ed

**Comment by dapplion** [comment]
Testing this branch, it persists and load state from db fine but apparently it's invalid as it throws with
```
2021-03-07 19:00:10 []                 info: Persisting genesis state block=11192975
 ✖ Error: Invalid deposit merkle branch
    at Object.true (/home/lion/Code/eth2.0/lodestar/packages/lodestar-utils/src/assert.ts:7:13)
    at processDeposit (/home/lion/Code/eth2.0/lodestar/packages/lodestar-beacon-state-transition/src/phase0/naive/block/operations/deposit.ts:17:3)
    at forEach (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/chain/genesis/util.ts:78:5)
    at Array.forEach (<anonymous>)
    at applyDeposits (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/chain/genesis/util.ts:64:15)
    at GenesisBuilder.applyDeposits (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/chain/genesis/genesis.ts:159:5)
    at GenesisBuilder.waitForGenesisValidators (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/chain/genesis/genesis.ts:127:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at GenesisBuilder.waitForGenesis (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/chain/genesis/genesis.ts:86:41)
    at initStateFromEth1 (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/chain/initState.ts:85:27)
```

To test this branch run the cli with
```
lodestar beacon --forceGenesis --rootDir ./lodestar-db
```
Then CTRL+C after it has processed 1 deposit and it will abort after a few seconds, when done processing that batch (deposit 192 in mainnet). Then run again with the same command and should trigger the above error.

**Comment by dapplion** [comment]
> Testing this branch, it persists and load state from db fine but apparently it's invalid as it throws with

Fixed the issue. After restarting it was starting from exactly `lastProcessedBlock` instead of `lastProcessedBlock + 1`

Ready for merge, tested and works fine.

:exclamation:  Please note that this PR is important: It takes many hours to build genesis with our slow single thread BLS (4-6 hours), and Infura is very likely to throw some network error during that window. I've not been able to build a genesis state without this PR in the last month.

**Review by wemeetagain — APPROVED** [review]

**Pull request merged**
