### PR TITLE
Add multiarch docker build to CI

### PR DESCRIPTION
**Pull request by wemeetagain**
**Motivation**

See #3692

**Description**

Followed instructions here: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

### CODE REVIEW

**Comment by dapplion** [comment]
Looks good! Tho we should do some checks on the image to ensure:
- It's in the right arch: `docker run chainsafe/lodestar uname -a`
- Lodestar actually runs: `docker run chainsafe/lodestar --help`

**Comment by wemeetagain** [comment]
I don't think we need the architecture check (this is what the buildx tool does).

The --help check should be there to ensure the image was built properly (on our side).

**Review by dapplion — APPROVED** [review]
Looks good!

**Review by g11tech — APPROVED** [review]

**Comment by dapplion** [comment]
Oh @wemeetagain I've experience with qemu and we can try this tricks to speed up the build
- The lodestar source (lib .js files) is platform agnostic, so we can build that in the host platform that should be much faster

**Comment by wemeetagain** [comment]
The docker file just installs via npm so I don't think there's much that can be done to speed it up.

**Pull request merged**
