### PR TITLE
Set lodestar-params as const

### PR DESCRIPTION
**Pull request by dapplion**
**Motivation**

Current approach to customize lodestar-params requires them to be `let`. This is not great since those are supposed to be constants, so creates confusion an allows dangerous mutations.

**Description**

Provide a different mechanism to customize the preset on start-up that allows params to be all constants.

```ts
// Demostrates how to properly change the Lodestar preset safely

// 1. Import from @chainsafe/lodestar-params/setPreset only
import {setActivePreset, PresetName} from "@chainsafe/lodestar-params/setPreset";
setActivePreset(PresetName.minimal);

// 2. Import from any other @chainsafe/lodestar-params paths
import {expect} from "chai";
import {SLOTS_PER_EPOCH} from "@chainsafe/lodestar-params";

expect(SLOTS_PER_EPOCH).to.equal(8, "SLOTS_PER_EPOCH should have minimal preset value");
expect(process.env.LODESTAR_PRESET).to.equal(undefined, "LODESTAR_PRESET ENV must not be set");
```

However if you try to set the active preset after it have been initialized it will throw an error:

```ts
// Demostrates how NOT to change the Lodestar preset

// 1. Import from not only @chainsafe/lodestar-params/setPreset will trigger an error
import {SLOTS_PER_EPOCH} from "@chainsafe/lodestar-params";
import {setActivePreset, PresetName} from "@chainsafe/lodestar-params/setPreset";
// This line should throw
setActivePreset(PresetName.minimal);
```

```
lion@lion-gram:~/Code/eth2.0/lodestar/packages/params$ ../../node_modules/.bin/ts-node test/e2e/changePresetError.ts 

/home/lion/Code/eth2.0/lodestar/packages/params/src/setPreset.ts:25
    throw Error(`Lodestar preset is already frozen. You must call setActivePreset() at the top of your application entry point.
          ^
Error: Lodestar preset is already frozen. You must call setActivePreset() at the top of your
application entry point, before importing @chainsafe/lodestar-params, or any library that may import it.


// index.ts
import {setActivePreset, PresetName} from "@chainsafe/lodestar-params/preset"
setActivePreset(PresetName.minimal)
// Now you can safely import from other paths and consume params
import {SLOTS_PER_EPOCH} from "@chainsafe/lodestar-params"
console.log({SLOTS_PER_EPOCH})

    at Object.setActivePreset (/home/lion/Code/eth2.0/lodestar/packages/params/src/setPreset.ts:25:11)
    at Object.<anonymous> (/home/lion/Code/eth2.0/lodestar/packages/params/test/e2e/changePresetError.ts:8:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module.m._compile (/home/lion/Code/eth2.0/lodestar/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.require.extensions.<computed> [as .ts] (/home/lion/Code/eth2.0/lodestar/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at main (/home/lion/Code/eth2.0/lodestar/node_modules/ts-node/src/bin.ts:198:14)
```

I've added a test running those two scripts directly with a child process to demonstrate that it works

**Extra**
- Export all constants in the root index.ts file so importing them does not require going through commonjs compiled star import shenanigans

### CODE REVIEW

**Review by wemeetagain — DISMISSED** [review]
LGTM, less error-prone approach

**Comment by wemeetagain** [comment]
The params readme may need to be updated

**Comment by wemeetagain** [comment]
What is "commonjs compiled star import shenanigans"?

**Comment by dapplion** [comment]
> What is "commonjs compiled star import shenanigans"?

Take a look at the compiled `/lib` files of a TS file that does `export *`

```ts
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
__exportStar(require("./chainConfig"), exports);
__exportStar(require("./forkConfig"), exports);
__exportStar(require("./beaconConfig"), exports);
//# sourceMappingURL=index.js.map
```

**Review by wemeetagain — APPROVED** [review]

**Pull request merged**
