### PR TITLE
Fix number key database serialization

### PR DESCRIPTION
**Pull request by mpetrunic**
Leveldb is sorting keys lexicographic so it seems best way to keep order with number keys is to serialize them as utf8 string.

### CODE REVIEW

**Comment by wemeetagain** [comment]
> Leveldb is sorting keys lexicographic so it seems best way to keep order with number keys is to serialize them as utf8 string.

I don't see why this is necessary.
Serializing ints in big-endian format has the same properties, no?

**Comment by mpetrunic** [comment]
> > Leveldb is sorting keys lexicographic so it seems best way to keep order with number keys is to serialize them as utf8 string.
> 
> I don't see why this is necessary.
> Serializing ints in big-endian format has the same properties, no?

It's necessary since it doesn't work :smile: 
You can try it yourself by running blockarchive e2e test.
As for reasoning, my best guess is since if it deserializes big int serialized number to string it gets some control characters instead of numbers (ascii 0 is 48!)

**Comment by wemeetagain** [comment]
I'm not sure I get it. The tests are passing on master, no?
unit testing the block archive shows its returning keys/values in order. https://github.com/ChainSafe/lodestar/pull/901

Hardening the eth1 e2e tests, on the other hand :+1: :+1:

**Comment by mpetrunic** [comment]
> I'm not sure I get it. The tests are passing on master, no?
> unit testing the block archive shows its returning keys/values in order. https://github.com/ChainSafe/lodestar/pull/901
> 

We arent testing searching for number value keys anywhere. See the new blockarchive e2e tests. Its not passing on master

**Comment by mpetrunic** [comment]
Will opem another PR with just eth1 test hardening

**Pull request closed without merging**
