### PR TITLE
feat(cli): add info logs for connected services URLS

### LINKED ISSUE #5990: Print out URLs of connected services
### Problem description

It would be great if we could print out URLs of connected services. This makes it easier to verify configuration and detect issues early.

We already do this for external signers
https://github.com/ChainSafe/lodestar/blob/f5e2c3a40c9a01a29a4283d9f17a901ede413068/packages/cli/src/cmds/validator/signers/logSigners.ts#L30
```log
 info: External signers on URL: http://web3signer.web3signer-prater.dappnode:9000
```

but it is missing for other services such as exection clients or beacon nodes.

### Solution description

Print out URLs of connected services 

Beacon node
- execution urls
- builder urls
- eth1 provider urls

Validator client
- beacon node urls

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by harshal619**
**Motivation**

Print URLS in the CLI package for connected services. 

**Description**

Prints info logs to show URLs of connected services

> Beacon node

- execution urls
- builder urls
- eth1 provider urls

> Validator client

- beacon node urls

Closes #5990

### CODE REVIEW

**Comment by nflaig** [comment]
Thanks for looking into this @harshal619 

Few suggestions
- would be better to log the URLs where they are used, i.e. when each component is initialized
- add URLs to log context to be more consistent with other logs like `Started REST API server address=http://127.0.0.1:9596`
- single line log should be sufficient, could include count as part of context but I don't think it is required as there are usually just 1-3 urls

Possible solution for this https://github.com/ChainSafe/lodestar/compare/unstable...nflaig/log-connected-service-urls

**Comment by harshal619** [comment]
@nflaig Makes sense to log URLs where the component is initialized.
The suggested solution by you looks sufficient.

Anyway, it was a good start for me to look into the code and understand it a little.
should I close this PR? As suggested solution already covers all the required changes.

**Comment by nflaig** [comment]
> Anyway, it was a good start for me to look into the code and understand it a little.

Solution looks pretty solid overall and is technically correct, just few nuances to better fit into current logging pattern (logs are kinda subjective and not sure I got it quite right either, definitely needs another review)

> should I close this PR? As suggested solution already covers all the required changes.

Sure, might make things easier. I will close this one when I open up the other PR.

**Comment by nflaig** [comment]
- closed in favor of https://github.com/ChainSafe/lodestar/pull/6099

**Pull request closed without merging**
