### PR TITLE
v0.37.0 release

### PR DESCRIPTION
**Pull request by dapplion**
Merges unstable to stable for v0.37.0 release

Approving this PR = "I have tested this release and looks safe to me"

### CODE REVIEW

**Comment by wemeetagain** [comment]
If automated, would be nice to have the commits/prs in the description

**Comment by dapplion** [comment]
> If automated, would be nice to have the commits/prs in the description

It would be redundant to the Github release + the list of commits in below the PR description. The list of commits match the list of PRs also.

**Review by dapplion — COMMENTED** [review]
:heavy_check_mark: **Approve**

Performance (profitability, resources, overall health) of this version is equal or greater than current stable.

However there are some warning indicators that must be investigated further but don't block the release in my opinion

**Review by g11tech — APPROVED** [review]

**Comment by dapplion** [comment]
Lodestar is downscoring more peers that usual reducing the total count of peers with score > 0

Screenshot from 2022-05-30 11-01-18

This affects the average mesh size of each topic, below target levels

 
Screenshot from 2022-05-30 11-01-48

This creates more churn and inclusion events as Gossip tries to meet the target levels

Screenshot from 2022-05-30 11-17-31

The low scores seem to be caused mainly by p3b weights on beacon_attestation topics. 

Screenshot from 2022-05-30 11-41-44

**Comment by dapplion** [comment]
The size of multiple Gossipsub cache data structures has increased. The biggest is seenCache. Can this be related to decreasing the heartbeat interval?

Screenshot from 2022-05-30 11-06-00

**Review by twoeths — APPROVED** [review]

**Pull request merged**
