### PR TITLE
Remove unnecessary return await

### PR DESCRIPTION
**Pull request by nflaig**
**Motivation**

from eslint docs [no-return-await](https://eslint.org/docs/latest/rules/no-return-await)

> This rule aims to prevent a likely common performance hazard due to a lack of understanding of the semantics of async function.

> Using return await inside an async function keeps the current function in the call stack until the Promise that is being awaited has resolved, at the cost of an extra microtask before resolving the outer Promise

**Benefit**

Improve performance by avoiding the extra microtask

**Trade off**

The function no longer being a part of the stack trace if an error is thrown asynchronously from the Promise being returned. This can make debugging more difficult.

I have personally not experienced any debugging issues due to missing `await` in a return statement, if a developers wants a piece of code to be more debuggable should be explicit about it by assigning the return value to a variable before returning.

```ts
async function foo() {
    const x = await bar();
    return x;
}
```

**Description**

- Add eslint rule to disallow unnecessary return await
- Fix unnecessary return await statements

### CODE REVIEW

**Comment by wemeetagain** [comment]
@dapplion should review this since he had some opinions on this in the past

**Comment by dapplion** [comment]
As long as you don't do
```ts
try {
  await foo() 
} catch () {}
```
all those return await are useless

**Review by dapplion — APPROVED** [review]

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
reopened to get CI to restart

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.6.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.6.0) :tada:

**Pull request merged**
