### PR TITLE
Set strictNullChecks = true in root

### LINKED ISSUE #885: Enable strict null checking
As I was fixing this issue: https://github.com/ChainSafe/lodestar/issues/880, I realized that the main `tsconfig.json` has `strictNullChecks` set to false. I believe that if this had been set to true, then the issue from https://github.com/ChainSafe/lodestar/issues/880 would already have been apparent. There are probably many more hidden problems of a similar nature lurking in the codebase.

We need to remove `strictNullCheck`: false from `tsconfig.json`. This will probably cause a massive amount of TypeScripte errors throughout the entire codebase. The longer we wait, the harder it will be to make the switch.

Also it might be good to have a null/undefined strategy if there isn't one already. Such as always using undefined, always using null, or deciding when to use each. There's also the option of never using undefined or null if possible, such as creating types that are more descriptive, i.e. `NOT_SET`.

Example:

```typescript
  public clock: IBeaconClock | "NOT_SET";
```
You could also say "NOT_INITIALIZED", "NOT_STARTED", or something. I have found this to be a pretty nice way to do things, not without its own problems of course. `null` and `undefined` are just such problematic and broad types.

### PR DESCRIPTION
**Pull request by dapplion**
Sets `strictNullChecks = true` in root tsconfig.json.

For all sub-packages except `lodestar` work was done beforehand with preceding PRs. This one required to fix a large number of errors in `lodestar` and took the approach of not modifying any logic when possible while doing extensive use of the non-null-assertion operator. This is a bad practice that should not be followed in new code, but it was the only way to enable this rule fast. 

Supersedes https://github.com/ChainSafe/lodestar/pull/1378
Fixes https://github.com/ChainSafe/lodestar/issues/885

### CODE REVIEW

**Comment by dapplion** [comment]
@wemeetagain Only changes in logic are
https://github.com/ChainSafe/lodestar/blob/124ca24f0968688746a29c25c5ac3ff92658e844/packages/lodestar/src/network/gossip/gossipsub.ts#L77-L78
https://github.com/ChainSafe/lodestar/blob/124ca24f0968688746a29c25c5ac3ff92658e844/packages/lodestar/src/network/gossip/utils.ts#L43-L45
All other issues including fork choice and sync are fixed with the non-null-assertion operator

**Comment by wemeetagain** [comment]
There's a test error
https://github.com/ChainSafe/lodestar/pull/1420/checks?check_run_id=1003809261#step:8:13

**Comment by dapplion** [comment]
> There's a test error
> https://github.com/ChainSafe/lodestar/pull/1420/checks?check_run_id=1003809261#step:8:13

Fixed with https://github.com/ChainSafe/lodestar/pull/1420/commits/124ca24f0968688746a29c25c5ac3ff92658e844

**Comment by wemeetagain** [comment]
file confiict

**Review by mpetrunic — DISMISSED** [review]

**Comment by wemeetagain** [comment]
damn, one last file conflict

**Review by wemeetagain — APPROVED** [review]

**Pull request merged**
