### PR TITLE
chore: revert async aggregate with randomness

### PR DESCRIPTION
**Pull request by matthewkeil**
**Motivation**

Change is choking network thread when `—subscribeAllSubnets` flag is applied.  Need to further investigate that issue so reverting for 1.23 and will reapply for 1.24 once network issue is resolved.

### CODE REVIEW

**Comment by twoeths** [comment]
this reverts #7204
for more info, the above PR seems to improve main thread a lot that it caused low performant on network thread due to high gc

this is peer count:

Screenshot 2024-11-07 at 06 20 40

there are too few inbound peers while a lot of out bound peers, while mesh peers are a lot which we haven't seen in past releases
Screenshot 2024-11-07 at 06 21 37

`gc` is so bad on network thread

Screenshot 2024-11-07 at 06 21 55

**Review by twoeths — APPROVED** [review]
there could be other issues that we haven't found since the issue happened in `rc.0` too on beta mainnet since Oct 20, but that's with libp2p `1.x`. Anyway this PR definitely needs to merge and test again

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.23.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.23.0) :tada:

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.24.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.24.0) :tada:

**Pull request merged**
