### PR TITLE
enr extension update

### LINKED ISSUE #2561: Error if enr exists
**Describe the bug**

If you already have enr, starting with beacon command fails with:
```
✖ Error: Invalid filetype
    at parse (/Users/nodefactory/Projects/lodestar/packages/cli/src/util/file.ts:47:13)
    at readFile (/Users/nodefactory/Projects/lodestar/packages/cli/src/util/file.ts:89:10)
    at readEnr (/Users/nodefactory/Projects/lodestar/packages/cli/src/config/enr.ts:28:24)
    at persistOptionsAndConfig (/Users/nodefactory/Projects/lodestar/packages/cli/src/cmds/init/handler.ts:85:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.beaconHandler [as handler] (/Users/nodefactory/Projects/lodestar/packages/cli/src/cmds/beacon/handler.ts:24:3)
```
because enr doesn't have extension.

**Expected behavior**
should work

**Steps to Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

- OS: 
- Version: 
- Branch: 
- Commit hash:

### PR DESCRIPTION
**Pull request by g11tech**
**Motivation**

**Description**

Closes #2561

**Steps to test or reproduce**

### CODE REVIEW

**Comment by dapplion** [comment]
Why change to `.yml` extension? Could you add rationale in the PR description? This also looks like it will break current nodes since existing ENRs won't be read at their previous path `enr`

**Comment by g11tech** [comment]
> 
> 
> Why change to `.yml` extension? Could you add rationale in the PR description? This also looks like it will break current nodes since existing ENRs won't be read at their previous path `enr`

this is to close issue #2561, as this code is already breaking while reading at the previous path `enr`, as the readFile expects a fileformat/extension of type: `yml`, `yaml` or `json`.

image

image

image

**Comment by dapplion** [comment]
But then the issue is that our file reader is bad. Changing the enr extension is not the solution

**Comment by g11tech** [comment]
> 
> 
> But then the issue is that our file reader is bad. Changing the enr extension is not the solution

even when you not specify the extension (first time around), its writing the `enr` file in `yml` format only ( `enr:..` ).  readfile seems to be returning a parsed file, and unless you want to make an assumption that if `fileFormat` is empty string, its `yml`, which in my opinion is the worse idea. 
or `readFile` interface having an optional `default` format parameter, which can still make sense.

let me know which one sounds good.

**Comment by dapplion** [comment]
> > But then the issue is that our file reader is bad. Changing the enr extension is not the solution
> 
> even when you not specify the extension (first time around), its writing the `enr` file in `yml` format only ( `enr:..` ). readfile seems to be returning a parsed file, and unless you want to make an assumption that if `fileFormat` is empty string, its `yml`, which in my opinion is the worse idea.
> or `readFile` interface having an optional `default` format parameter, which can still make sense.
> 
> let me know which one sounds good.

I would not give it a .yml format. It can be either `enr` or `enr.dat` (Lighthouse).

Here instead of throwing an error it should just return the file in plain text format
https://github.com/ChainSafe/lodestar/blob/f6778740075fe2b75edf94d1db0b5691039cb500/packages/cli/src/util/file.ts#L46-L47

```ts
 default:
   return contents
   ```

Same for stringify
https://github.com/ChainSafe/lodestar/blob/f6778740075fe2b75edf94d1db0b5691039cb500/packages/cli/src/util/file.ts#L64-L65

**Comment by g11tech** [comment]
ok assign the #2561  to me, i will send in the proper fix.

**Comment by dapplion** [comment]
@g11in thanks! If you create new branches from current master, CI will pass. We fixed it in Friday

**Pull request closed without merging**
