### PR TITLE
chore: align vitest config filenames

### PR DESCRIPTION
**Pull request by jeluard**
**Motivation**

Make sure `vitest` configuration files all follow the same pattern: `vitest.$TYPE.config.ts`

### CODE REVIEW

**Review by nazarhussain — APPROVED** [review]

**Comment by nazarhussain** [comment]
@jeluard The sim tests are failing, before re-running double check if the error output is understandable or we need any improvements there.

**Comment by jeluard** [comment]
@nazarhussain Unclear how I should read the error. I only see 
```── Assertion: finalized
├──── node-1-beacon_lodestar: node has not finalized expected slot finalizedSlot=56 expectedFinalizedSlot=64
```

as suspicious.

**Comment by nazarhussain** [comment]
> @nazarhussain Unclear how I should read the error. I only see
> 
> ```
> ├──── node-1-beacon_lodestar: node has not finalized expected slot finalizedSlot=56 expectedFinalizedSlot=64
> ```
> 
> as suspicious.

So node is not finalizing the chain, it should have reached to `64` finality but yet reaches to `56`. There must be some attestations missing and there would be some error messages for it as well.

**Comment by wemeetagain** [comment]
@nazarhussain what does that error have to do with this PR?

**Comment by nazarhussain** [comment]
> @nazarhussain what does that error have to do with this PR?

Apparently this PR is changing nothing related to sim tests, btu the stats are way off. Nodes missed two slots in first epoch and many more in other epochs. Need to see what's gone wrong in there. 

```
┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼
│ time           │ fork       │ eph   │ slot │ head       │ finzed   │ peers    │ attCount │ incDelay │ errors     │
┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼
│ 15:48:57.257   │ phase0     │ 0/1   │ 1    │ 0xa93b..   │ 0        │ 4        │ 12       │ 1.00     │ 0          │
│ 15:49:3.666    │ phase0     │ 0/2   │ ---  │ ---        │ ---      │ ---      │ ---      │ ---      │ 0          │
│ 15:49:5.156    │ phase0     │ 0/3   │ 3    │ 0x6c15..   │ 0        │ 4        │ 19       │ 1.50     │ 0          │
│ 15:49:11.671   │ phase0     │ 0/4   │ ---  │ ---        │ ---      │ ---      │ ---      │ ---      │ 0          │
│ 15:49:13.174   │ phase0     │ 0/5   │ 5    │ 0xc805..   │ 0        │ 4        │ 20       │ 1.50     │ 0          │
│ 15:49:17.102   │ phase0     │ 0/6   │ 6    │ 0x95c2..   │ 0        │ 4        │ 16       │ 1.00     │ 0          │
│ 15:49:21.131   │ phase0     │ 0/7   │ 7    │ 0x7273..   │ 0        │ 4        │ 16       │ 1.00     │ 0          │
┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼
```

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.16.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.16.0) :tada:

**Pull request merged**
