### PR TITLE
Jonathan/fix map get active validator indices

### PR DESCRIPTION
**Pull request by JonathanLorimer**
Small change:

Mutation with map isn't an issue, as it creates a new array with the mapped values. However, if you don't return a value within the lambda provided to map then it will, by default, insert undefined into the array. To avoid this, and do the filtering in a single iteration, I implemented reduce.

### CODE REVIEW

**Comment by GregTheGreek** [comment]
@JonathanLorimer Awesome thanks for pointing that out! I made a super simple js file to test out the functionality and you're in-fact correct, looks like using reduce definitely solves the issue!
Could you make a few tests for this and then I I'll be more than happy to PR this through :)

**Review by GregTheGreek — CHANGES_REQUESTED** [review]
Can you make a few tests so we can have those pass :)
Maybe 1 with an empty validator list, with all validators that have active set and an array with no active?

**Comment by JonathanLorimer** [comment]
@GregTheGreek added the test cases, just two things.

- First, I had to change around the order of a couple of imports so that they were alphabetical (consider using ordered-imports: false in tslint if you don't want this), and I had to run tslint fix on the test file so the diff will be large

- Second this code in stateTransitionHelpers.ts (line 148) is preventing TS from compiling, and I am not sure what it is supposed to accomplish. The issue is that we are trying to access an indexed value on participationBitfield, which is a number (I am not too familiar with bitwise operators, and how you can access them but TS is not liking the square brackets).
```const bit: int = (participationBitfield[Math.floor(index / 8)] >> (7 - (index % 8))) % 2;```

**Comment by GregTheGreek** [comment]
@JonathanLorimer 
re test: Awesome thank you!

1 - Good point, I'll make that fix in a pr.

2 - I'm going to look into this, not sure why it's causing an issue. Previous pr it didn't seem to have that. Checking it out on my machine right now.

**Comment by GregTheGreek** [comment]
@JonathanLorimer Ok i found out why its failing, line 24 of `tsconfig.json` is set to `strict: true`. since we don't have our integer and byte types finalized yet, this will naturally fail. So if you set it to `false` you'll be able to run the tests !

After running `npm test` the second test you wrote is failing. Expected: `0` Actual: `10`.

Otherwise it's good to merge :)

**Review by GregTheGreek — APPROVED** [review]

**Comment by GregTheGreek** [comment]
@JonathanLorimer Great work, thanks for contributing! :)

**Pull request merged**
