### PR TITLE
Precompute OR flags

### PR DESCRIPTION
**Pull request by dapplion**
**Motivation**

Reduce unnecessary opts in hot paths

**Description**

Pre-computes the OR of flags to not do that on every loop of getAttestationDeltas().
- With my local estimates this PR reduces the total time of `getAttestationDeltas()` by 16%
- In Prater that means about 150ms per epoch transition

### CODE REVIEW

**Comment by dapplion** [comment]
Screenshot from 2021-04-08 21-41-08

**Comment by twoeths** [comment]
this could be coordinate with #2348 . Could you give it a try @dapplion ?

**Comment by dapplion** [comment]
> this could be coordinate with #2348 . Could you give it a try @dapplion ?

Let's merge both

**Review by twoeths — DISMISSED** [review]

**Comment by wemeetagain** [comment]
Can we hold off on this and #2348 until after we add the participation cache?

**Comment by wemeetagain** [comment]
Actually, lets just merge #2348 first, then this (with this PR rebased to take advantage of #2348). And I'll base the participation cache off that.

**Review by wemeetagain — APPROVED** [review]

**Pull request merged**
