### PR TITLE
chore: release v1.23.0

### PR DESCRIPTION
**Pull request by wemeetagain**
- replacement of https://github.com/ChainSafe/lodestar/pull/7155

### CODE REVIEW

**Comment by twoeths** [comment]
this is on 1k, `submitPoolAttestationPool()` was reduced thanks to libp2p revert

Screenshot 2024-11-01 at 14 33 14

gc was reduced more with async `aggregateWithRandomness()`, this is on the test mainnet node

Screenshot 2024-11-01 at 14 35 35

thanks to that the "Prepare Next Epoch" time was reduced, this is  on 1k

Screenshot 2024-11-01 at 14 38 48

the stable lg1k node somehow was very bad due to the high gc there

**Review by twoeths — DISMISSED** [review]

**Review by nflaig — DISMISSED** [review]
All issues I had reported on rc.0 are resolved

**Comment by nflaig** [comment]
Need to cherry-pick https://github.com/ChainSafe/lodestar/pull/7212 as well

**Comment by philknows** [comment]
#7212 will need to be updated with new genesis before release. https://config.mekong.ethpandaops.io/cl/config.yaml

**Review by nflaig — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.23.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.23.0) :tada:

**Comment by twoeths** [comment]
[v1.23.0_feat2-64_main.cpuprofile.zip](https://github.com/user-attachments/files/17841536/v1.23.0_feat2-64_main.cpuprofile.zip)
[v1.23.0_feat2-1k_main.cpuprofile.zip](https://github.com/user-attachments/files/17841538/v1.23.0_feat2-1k_main.cpuprofile.zip)
[v1.23.0_feat2-mainnet-main.cpuprofile.zip](https://github.com/user-attachments/files/17841539/v1.23.0_feat2-mainnet-main.cpuprofile.zip)
[v1.23.0_feat2-64_network.cpuprofile.zip](https://github.com/user-attachments/files/17841540/v1.23.0_feat2-64_network.cpuprofile.zip)
[v1.23.0_feat2-1k_network.cpuprofile.zip](https://github.com/user-attachments/files/17841541/v1.23.0_feat2-1k_network.cpuprofile.zip)
[v1.23.0_feat2-mainnet_network.cpuprofile.zip](https://github.com/user-attachments/files/17841542/v1.23.0_feat2-mainnet_network.cpuprofile.zip)
[v1.23.0_feat2-64_discv5.cpuprofile.zip](https://github.com/user-attachments/files/17841543/v1.23.0_feat2-64_discv5.cpuprofile.zip)
[v1.23.0_feat2-1k-discv5.cpuprofile.zip](https://github.com/user-attachments/files/17841545/v1.23.0_feat2-1k-discv5.cpuprofile.zip)

**Pull request merged**
