### PR TITLE
feat: add disablePeerScoring flag

### LINKED ISSUE #5475: Implement --disable-peer-scoring flag for local testing
**Describe the solution you'd like**

Add a flag `--disable-peer-scoring` for small testnets and local testing, especially for new features.

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

Add a feature flag to disable peer scoring for testing devnets

**Description**

- Refactor `score.ts` to multiple files
- Add IPeerScore interface, the current/default implementation is RealScore
- Add `disablePeerScoring` flag, use `MaxScore` with this flag

Closes #5475

### CODE REVIEW

**Comment by twoeths** [comment]
blocked by #5479

**Review by g11tech — DISMISSED** [review]
looks good and useful :+1:

**Review by nflaig — APPROVED** [review]
lgtm

**Review by dapplion — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.9.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.9.0) :tada:

**Pull request merged**
