### PR TITLE
[WIP] multiproof infrastructure

### PR DESCRIPTION
**Pull request by wemeetagain**
not ready for merging, just making a PR to give visibility

Currently includes infrastructure to:
- get all possible paths of an ssz type
`FullSSZType -> Path[]`
- convert paths to generalized indices
`Path[] -> GeneralizedIndex[]`
- convert generalized indices to paths
`GeneralizedIndex[] -> Path[]`
- create a proof from a value, type, and paths
`any, FullSSZType, Path[] -> Multiproof`

### CODE REVIEW

**Comment by wemeetagain** [comment]
meant to open this a a draft

**Comment by GregTheGreek** [comment]
👀

**Review by mpetrunic — COMMENTED** [review]
Seems ok, not sure I understand whats going on in some places would be nice to break into multiple smaller functions.

What does 1n or 2n do?

**Comment by wemeetagain** [comment]
Most of the work is done in `buildProof`, which is basically `hashTreeRoot` but which saves intermediate nodes in the merkle tree. There's also a similar version of `merkleize` which saves intermediate nodes too.

1n and 2n are `BigInt` literals. We use `BigInt`s to represent `GeneralizedIndex`.

**Comment by wemeetagain** [comment]
Closing for now as this was more of a prototype and is not very suitable for creating proofs in production. We have plans to use a persistent, immutable tree as backing for proof generation.

**Pull request closed without merging**
