### PR TITLE
feat: add electra support for light-client

### PR DESCRIPTION
**Pull request by matthewkeil**
**Motivation**

Branch created on behalf of the original author @ensi321.  Replaces #7038 to avoid a difficult rebase due to the various rebases of the electra branch it was originally based on.  Cherry-picked the commits over and will commit here with fixes for the errors that come up.

Verified that all code in commits up to c5bab83 were on current unstable and 0a33b9a starts novel code for from PR#7038

**Description**

Fix various places to comply with light client electra spec

Will be ready for review after #6986 is merged.

### CODE REVIEW

**Review by wemeetagain — DISMISSED** [review]

**Review by nflaig — COMMENTED** [review]
light client spec tests are currently disabled, this branch should pass those?
https://github.com/ChainSafe/lodestar/blob/9fe72391bea93f7f88b7b739006844352d929cad/packages/beacon-node/test/spec/utils/specTestIterator.ts#L68

**Comment by ensi321** [comment]
> light client spec tests are currently disabled, this branch should pass those?
> 
> https://github.com/ChainSafe/lodestar/blob/9fe72391bea93f7f88b7b739006844352d929cad/packages/beacon-node/test/spec/utils/specTestIterator.ts#L68

Good call. Totally forgot to enable the spec test. Converting this to draft while fixing the test failure

**Comment by ensi321** [comment]
> light client spec tests are currently disabled, this branch should pass those?
> 
> https://github.com/ChainSafe/lodestar/blob/9fe72391bea93f7f88b7b739006844352d929cad/packages/beacon-node/test/spec/utils/specTestIterator.ts#L68

Good call. Enabled.

**Review by nflaig — APPROVED** [review]
LGTM

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.23.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.23.0) :tada:

**Pull request merged**
