### PR TITLE
chore: v1.12.1 release

### PR DESCRIPTION
**Pull request by philknows**

### CODE REVIEW

**Review by g11tech — DISMISSED** [review]
lgtm

**Review by g11tech — DISMISSED** [review]

**Comment by wemeetagain** [comment]
Can we include a few of @nflaig 's nice-to-have fixes?
I was thinking
- #6152 
- #6150 
- #6146

**Comment by philknows** [comment]
> Can we include a few of @nflaig 's nice-to-have fixes? I was thinking
> 
> * [fix: set consensus version header in state and block response #6152](https://github.com/ChainSafe/lodestar/pull/6152)
> * [fix: prevent low peer count warning on startup #6150](https://github.com/ChainSafe/lodestar/pull/6150)
> * [fix: include slot in block error metadata #6146](https://github.com/ChainSafe/lodestar/pull/6146)

We will add these to the final RC release as soon as we wrap up any additional fixes to resolve the invalid state root issue we’re seeing in v1.12.

**Comment by twoeths** [comment]
@philknows also this is to fix the memory leak issue in worker thread #6156

**Review by g11tech — APPROVED** [review]
lgtm

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.12.1](https://github.com/ChainSafe/lodestar/releases/tag/v1.12.1) :tada:

**Pull request merged**
