### PR TITLE
Faster fastMsgIdFn using xxhash

### LINKED ISSUE #4600: Missed attestation after v1.1.0
**Describe the bug**

With v1.1.0 we have ~2% wrong head attestations and ~1% missed attestation

Screen Shot 2022-09-27 at 14 48 44

This is because in v1.1.0 we improved gossipsub hence we have a lot of mesh peers, and that introduced the I/O lag issue
```
Local validator published unaggregated attestation validatorIndex=429161, slot=4786296, committeeIndex=5, subnet=5, sentPeers=17, delaySec=2.5950000286102295
```

at the validator side
```
Sep-27 06:19:39.000[]                ^[[34mdebug^[[39m: HttpClient request routeId=submitPoolAttestations
Sep-27 06:19:43.733[]                ^[[34mdebug^[[39m: HttpClient response routeId=submitPoolAttestations
```
Screen Shot 2022-09-27 at 14 55 05

**Expected behavior**
- Should improve `vc REST API request times` `submitPoolAttestations` and `beacon REST API response times` `submitPoolAttestations`

### LINKED ISSUE #4603: Improve fastMsgIdFn
**Is your feature request related to a problem? Please describe.**

As of v1.2.0 rc.0, fastMsgIdFn takes 1.57% of cpu time since the more mesh peers we have, the more fastMsgIdFn get called

```typescript
export function fastMsgIdFn(rpcMsg: RPC.IMessage): string {
  if (rpcMsg.data) {
    return Buffer.from(digest(rpcMsg.data)).subarray(0, 8).toString("hex");
  } else {
    return "0000000000000000";
  }
}
```
Screen Shot 2022-09-29 at 11 28 30

**Describe the solution you'd like**

Instead of copying to Buffer and convert to hex from there, we can just create String directly from there

```typescript
const hash = digest(data);
String.fromCharCode(hash[0], hash[1], hash[2], hash[3], hash[4], hash[5], hash[6], hash[7]);
```

quick benchmark
```
  encoding.test.ts
    ✔ same to fastMsgIdFn                                              4.564126e+11 ops/s 0.002191000 ns/op   x0.000    3899710 runs   10.0 s
    ✔ new fastMsgIdFn                                                  6.195787e+11 ops/s 0.001614000 ns/op   x0.000    5125581 runs   10.1 s
```

it's ~30% faster

if we don't count the hash, `String.fromCharCode()` is 3x faster
```
✔ Buffer.from(hash).subarray(0, 8).toString                        9.216590e+11 ops/s 0.001085000 ns/op   x0.002    6948395 runs   10.1 s
✔ String.fromCharcode 8 first bytes                                3.134796e+12 ops/s 0.0003190000 ns/op   x0.010   15844892 runs   10.0 s
✔ hash64 bytes                                                     6.570302e+11 ops/s 0.001522000 ns/op        -    5346980 runs   10.0 s
```

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

- We want faster `fastMsgIdFn()`, it turns out it has a big impact on the I/O lagged issue

**Description**

- Same to #4630 (use `xx-hash` for better performance compared to `as-sha256`) but use `h64` instead of `h32` to reduce hash collision, hence no memory issue

Closes #4603
could close #4600 due to its significantly faster `sumitPoolAttestations` request time

**TODO**
- [ ] monitor the metrics on feat1 group

### CODE REVIEW

**Comment by twoeths** [comment]
it's been 8h since I tested this branch on feat1 (vs feat2, both configured `after_block_delay_slot_fraction` as 3 in order to submit attestations right at 1/3 of slot, that's a very busy time to reproduce the missed attestation issue on goerli)

- feat1 (this branch)
Screen Shot 2022-10-07 at 21 39 03

- feat2 (unstable)
Screen Shot 2022-10-07 at 21 39 38

- feat1 (this branch) - submitPoolsAttestation request time
Screen Shot 2022-10-07 at 21 40 31

- feat2 (unstable) - submitPoolsAttestation request time
Screen Shot 2022-10-07 at 21 41 03

all other metrics are the same

**Comment by twoeths** [comment]
also posting the benchmark in this PR

```
network / gossip / fastMsgIdFn
    ✔ fastMsgIdFn sha256 / 200 bytes                                      232180.2 ops/s    4.307000 us/op        -      84581 runs  0.404 s
    ✔ fastMsgIdFn h32 xxhash / 200 bytes                                   178[89](https://github.com/ChainSafe/lodestar/actions/runs/3205610042/jobs/5238344436#step:9:90)09 ops/s    559.0000 ns/op        -    1215000 runs   1.11 s
    ✔ fastMsgIdFn h64 xxhash / 200 bytes                                   1455604 ops/s    687.0000 ns/op        -     [90](https://github.com/ChainSafe/lodestar/actions/runs/3205610042/jobs/5238344436#step:9:91)8438 runs   1.01 s
    ✔ fastMsgIdFn sha256 / 1000 bytes                                     74906.37 ops/s    13.35000 us/op        -      57568 runs  0.808 s
    ✔ fastMsgIdFn h32 xxhash / 1000 bytes                                  1436782 ops/s    696.0000 ns/op        -     666281 runs  0.707 s
    ✔ fastMsgIdFn h64 xxhash / 1000 bytes                                  1142857 ops/s    875.0000 ns/op        -     731729 runs  0.[91](https://github.com/ChainSafe/lodestar/actions/runs/3205610042/jobs/5238344436#step:9:92)4 s
    ✔ fastMsgIdFn sha256 / 10000 bytes                                    8846.896 ops/s    113.0340 us/op        -       1779 runs  0.316 s
    ✔ fastMsgIdFn h32 xxhash / 10000 bytes                                441891.3 ops/s    2.263000 us/op        -     109369 runs  0.303 s
    ✔ fastMsgIdFn h64 xxhash / 10000 bytes                                554323.7 ops/s    1.804000 us/op        -     275290 runs  0.610 s
```

**Review by wemeetagain — APPROVED** [review]
LGTM, great work

**Comment by philknows** [comment]
<3 thanks @tuyennhv !

**Comment by twoeths** [comment]
This PR only reduce fastMsgIdFn time, it does not help I/O lag issue in #4600
For some reasons, metrics in feat1 is better than feat2 even I deploy `unstable` to both of them

**Pull request merged**
