### PR TITLE
Create new ssz-util package

### PR DESCRIPTION
**Pull request by ec2**
This pull request takes expandYamlInput and the corresponding unexpand into a new package called `ssz-util`. Further work on moving other SSZ utilities such as generating random SSZ types will follow.

### CODE REVIEW

**Review by mpetrunic — CHANGES_REQUESTED** [review]
Can you also move expandJsonValue from /src/api/rest/utils?
I'm pretty sure ssz-util needs to depend on @chainsafe/ssz, @chainsafe/bit-utils and decamelize.

Would be awesome if you could also migrate spec-test-utils to do the same but it would require changing all spec tests that modify bignum to number so it's up to you :)

**Comment by mpetrunic** [comment]
@wemeetagain @tueric I forgot, why do we want to create new package ssz-utils instead of using those methods from eth2.0-utils that I'm working on?

**Comment by wemeetagain** [comment]
@mpetrunic we want to create a ssz-util package to divide our utils between functions that rely on ssz and functions that are used by ssz.

`expandYamlValue`, `lodestar/src/util/createValue`, `lodestar/src/util/objects`, `simpleserialize.com/util/random` are all prime candidates for what this library would be about.

**Comment by ec2** [comment]
Yeah, and to add to @wemeetagain 's comment, I needed to add a function for unexpandYaml, but the corresponding expandYaml was in the lodestar package, so we would have needed to update the lodestar package in order or update something used in SSZ.

**Comment by GregTheGreek** [comment]
Removes circular dependencies as well I believe?

**Comment by wemeetagain** [comment]
discussed in discord, lets move these ssz utils into the ssz package

**Comment by mpetrunic** [comment]
@wemeetagain @tueric can we close this in favor of #461 ?

**Pull request closed without merging**
