### PR TITLE
New metrics for peers

### LINKED ISSUE #3835: Add metrics to track lost peers
Add more peer metrics:
- Track connection length, log avg min max of peer connections length
- For long connections, track disconnecting reason
- Track count of reportPeer() calls labeled by reason
- Track avg min max of application layer scores

CC @tuyennhv

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

New metrics for peers

**Description**

- Track connection length, log avg min max of peer connections length
- For long connections, track disconnecting reason
- Track count of reportPeer() calls labeled by reason
- Track avg min max of application layer scores
- Track long lived subnets

Closes #3835

### CODE REVIEW

**Comment by twoeths** [comment]
@dapplion any ideas why the dashboard is so different? I generated it from contabo-20

**Review by wemeetagain — DISMISSED** [review]

**Comment by wemeetagain** [comment]
LGTM but try regenerating the dashboard. It seems like its too different

**Comment by dapplion** [comment]
> @dapplion any ideas why the dashboard is so different? I generated it from contabo-20

Adding new charts to Grafana without triggering massive diffs is tricky. I can try to write a how-to guide when avail

**Review by wemeetagain — APPROVED** [review]

**Comment by twoeths** [comment]
thanks @wemeetagain 🙏

**Pull request merged**
