### PR TITLE
Split preset from config

### PR DESCRIPTION
**Pull request by wemeetagain**
**Motivation**
See #2547 and https://hackmd.io/fDlzBx9NQjShUAtHZNcoMw

**Description**

Take a look at the `params`, `types`, `config` packages, which are the meat of this PR, and have been significantly changed.
All downstream changes come from that.

Notable changes:
- `IBeaconParams` is no longer, same with `config.params`
  - instead, many of the params are now part of `IBeaconPreset`, accessible directly on the lodestar-params package
    - `import {SLOTS_PER_EPOCH} from "@chainsafe/lodestar-params"` 
- mainnet/minimal presets are toggled via environment variable `LODESTAR_PRESET`
  - the currently active preset can be accessed with: `import {ACTIVE_PRESET} from "@chainsafe/lodestar-params"`
- there is no longer an exposed mainnet/minimal config
  - instead, there is now a "default" config (and a default `IChainConfig`)
  - `import {config, chainConfig} from "@chainsafe/lodestar-config/default"`
- eth ssz types are available from the lodestar-types package: `import {ssz} from "@chainsafe/lodestar-types"`
  - eth ssz types are no longer attached to `IBeaconConfig`

TODO
- [x] fix tests

### CODE REVIEW

**Comment by wemeetagain** [comment]
Ready for review :rocket:

**Comment by twoeths** [comment]
Got conflicts after recent merges to master

**Comment by mpetrunic** [comment]
No idea how to review this actually 🤣 
from scrolling trough files it looks good to me

**Review by twoeths — DISMISSED** [review]

**Comment by dapplion** [comment]
> No idea how to review this actually 
> from scrolling trough files it looks good to me

First the config, params and type packages. Then through scroll through the tests to make sure there's nothing too odd.

**Review by dapplion — APPROVED** [review]
Awesome work :fire: overall thinks are much cleaner now

**Pull request merged**
