### PR TITLE
Set state cache size to 1 during initial sync

### PR DESCRIPTION
**Pull request by wemeetagain**

### CODE REVIEW

**Review by mpetrunic — APPROVED** [review]

**Comment by twoeths** [comment]
in the past I used to see some peers sent us orphaned blocks during initial sync so should we increase it a little bit? not sure if it happens again through

**Comment by dapplion** [comment]
> in the past I used to see some peers sent us orphaned blocks during initial sync so should we increase it a little bit? not sure if it happens again through

Is this related? https://github.com/ChainSafe/lodestar/issues/2127

**Comment by twoeths** [comment]
> > in the past I used to see some peers sent us orphaned blocks during initial sync so should we increase it a little bit? not sure if it happens again through
> 
> Is this related? #2127

yeah it's same issue but I'm not sure whose nodes I received data from

**Comment by wemeetagain** [comment]
> in the past I used to see some peers sent us orphaned blocks during initial sync so should we increase it a little bit? not sure if it happens again through

We should be able to handle orphaned blocks using the regen. In that case, we'd just replay a few blocks starting from the last checkpoint state.

**Pull request merged**
