### PR TITLE
docs: add X (Twitter) Hyperlink to README

### PR DESCRIPTION
**Pull request by davidcardenasus**
**Motivation**

Increased visibility and community engagement for the Lodestar X account.

**Description**

Adds X (Twitter) Hyperlink to README.

### CODE REVIEW

**Comment by nflaig** [comment]
Thanks @davidcardenasus, I also think this is a good idea.

What I am not sure about is adding this to badges, I think we should use those for technical references. And those are already bit overloaded.

Maybe it makes sense to add this to https://github.com/ChainSafe/lodestar#getting-started, we already have a reference to discord and the mailing list there. Could be similar to the discord one

image

It kinda fits into the topic of announcements and critical information about Lodestar, which is already mentioned for the mailing list. I'd suggest to either add it there as another reference or as another bullet point.

@philknows what do you think?

**Comment by philknows** [comment]
I'm thinking it would be better to remove the bullet point about mailing list (this may not come to fruition) and replace it with a point to follow us on X/Twitter instead. There was a previous staker survey that showed more people paid attention to Twitter than they did with e-mail updates also.

**Comment by davidcardenasus** [comment]
Screenshot 2023-10-19 010924

Went with this! Let me know if okay.

**Comment by philknows** [comment]
Closed for #6051

**Pull request closed without merging**
