### PR TITLE
feat: schedule deneb fork on testnets

### PR DESCRIPTION
**Pull request by g11tech**
UPDATE: it has been decided to first check the rollout of deneb on goerli PR (https://github.com/ChainSafe/lodestar/pull/6254) via a goerli focused release and if things go good then the schedule will be applied on a new release

deneb has been tentatively schedule for testnets (post mid jan 2024)

see: 
- https://github.com/ethereum/EIPs/pull/8051
- https://github.com/ethereum/execution-specs/pull/860

see :
 - https://github.com/eth-clients/goerli/pull/178
 - https://github.com/eth-clients/sepolia/pull/61
 - https://github.com/eth-clients/holesky/pull/94

### CODE REVIEW

**Comment by philknows** [comment]
Let's wait for the merges in the various eth-client repos before go ahead with this.

**Comment by g11tech** [comment]
this schedule is a go for now (unless something bad happens on goerli)

so the ideal strategy would be to:

hold off deployment of this release to sepolia and holesky till the verdict on goerli is out

**Comment by g11tech** [comment]
UPDATE: first goerli is being released and based on the actual rollout, this scheduled will be applied (or modified) for sepolia/holesky and released separately

**Review by philknows — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.15.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.15.0) :tada:

**Pull request merged**
