### PR TITLE
fix: start clock last when initializing validator client

### PR DESCRIPTION
**Pull request by nflaig**
**Motivation**

Clock needs to be started as late as possible when initializing validator client to ensure all functions are being scheduled.

https://github.com/ChainSafe/lodestar/blob/27012f96ec70725d1440069a1c6ca0f0424ea8ab/packages/validator/src/util/clock.ts#L48-L49

**Description**

Start clock last when initializing validator client

### CODE REVIEW

**Comment by wemeetagain** [comment]
is the problem that we could miss the first slot?

**Comment by nflaig** [comment]
> is the problem that we could miss the first slot?

No, it's just that after `clock.start` is called, all `runEveryX` calls after that won't be registered anymore

**Comment by wemeetagain** [comment]
Oh, right! 
So we currently aren't logging on unhealthy primary beacon node or setting metrics.beaconHealth?

**Comment by nflaig** [comment]
> Oh, right! So we currently aren't logging on unhealthy primary beacon node or setting metrics.beaconHealth?

yeah, I have not retested the unhealthy log after moving it in constructor (from init previously) and was kinda blindly trusting that it should work there because the beacon health was there as well but noticed this yesterday when experimenting with my multi node setup.

**Review by wemeetagain — APPROVED** [review]

**Review by twoeths — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.21.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.21.0) :tada:

**Pull request merged**
