### PR TITLE
chore: pin nodejs version to 22.4

### PR DESCRIPTION
**Pull request by wemeetagain**
This reverts commit 69ae688bed4b17f93801494aa16919888935c780.

**Motivation**

- poor performance on 1.24.0-rc.0

### CODE REVIEW

**Review by wemeetagain — COMMENTED** [review]
lgtm

**Comment by twoeths** [comment]
after the revert I see gc pause time rate reduced while gossip traffic volume is the same. It's only been tested 7h on the unstable mainnet node so need more time to monitor, posting here so that we can trace back later

Screenshot 2024-12-13 at 08 50 33

**Comment by nflaig** [comment]
we should revert this again

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.24.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.24.0) :tada:

**Pull request merged**
