### PR TITLE
Automatic release and publish

### LINKED ISSUE #1876: Automatic release

### PR DESCRIPTION
**Pull request by mpetrunic**
- added command to bump versions
- added note on cutting release
- ci will on version bump detection, create tag, publish on npm and generate release page with changelog based on PR titles

resolves #1876

If something goes wrong, tag and release will rollback. Only untested feature is actual publish on npm

### CODE REVIEW

**Comment by dapplion** [comment]
Awesome, really into this! How will the changelog look like with the current settings of this PR?

**Review by dapplion — APPROVED** [review]

**Comment by mpetrunic** [comment]
> Awesome, really into this! How will the changelog look like with the current settings of this PR? 

https://github.com/mpetrunic/lodestar/releases/tag/v0.15.0

It takes pr titles and authors

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
Do we just need to update lerna.json?

**Comment by mpetrunic** [comment]
> Do we just need to update lerna.json?

Check the readme section update 🙂

**Comment by dapplion** [comment]
Would it make sense for all of us to strictly follow conventional commits on PR titles?

**Comment by mpetrunic** [comment]
> Would it make sense for all of us to strictly follow conventional commits on PR titles?

We should just make them clear. There is action to enforce conventional pr titles if we want.

**Pull request merged**
