### PR TITLE
fix: revert level update

### LINKED ISSUE #6794: Replace `leveldown` with `classic-level` in db tests
this PR (and this old dependency version) highlights that we're using a now-deprecated `leveldown` in our db tests. It should be replaced with `classic-level`.

_Originally posted by @wemeetagain in https://github.com/ChainSafe/lodestar/pull/6793#discussion_r1603298992_

### LINKED ISSUE #6826: v1.19.0-rc.0 high gc time
### Describe the bug

v1.19.0-rc.0 shows high gc time on the mainnet node

Screenshot 2024-05-29 at 15 00 52

while it's consistently <3% on the stable mainnet node (v1.18.0)
Screenshot 2024-05-29 at 15 01 23

this leads to high epoch transition time

Screenshot 2024-05-29 at 15 02 34

vs stable

Screenshot 2024-05-29 at 15 03 08

### Expected behavior

Metrics should be the same or better than v1.18.0

### Steps to reproduce

_No response_

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

v1.19.0-rc.0

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

`classic-level` was upgraded from 1.2.0 to 1.4.1 in #6795 and it caused a lot of `gc` in docker deployment

This PR is created on behalf of @matthewkeil 

**Description**

- The issue only happen in docker deployment probably due to this step https://github.com/ChainSafe/lodestar/blob/8b6ecc44c1892115d0e7396b2a5f0ae8fc0d9e6f/Dockerfile#L34
- I'm not sure if it's too much to revert this PR, looks like the issue it resolves #6794 is optional for v1.19.0 so we can add it back with classic-level v1.20.0 later then create another issue for classic-level v1.4.1

closes #6826
**TODOs**

The above hypothesis is not confirmed until the below step:
- [ ] reproduce in a service deployment node with extra step as mentioned above
- [ ] test this branch with docker deployment

### CODE REVIEW

**Comment by jeluard** [comment]
At first glance looks like setting `classic-level` version to `1.2.0` would do it? This would give us more control on what version is used and prevent accidental upgrades.

Not a lot of changes with `1.4.1` but [some](https://github.com/Level/classic-level/commit/b9fd5e99cfb546229d222ba6c3acb5d7384759a4) are related to napi refactorings. 
Given that this lib doesn't appear super active and our surface area with `leveldb` is thin, might be a potential future candidate for some `rust` based binding.

**Comment by matthewkeil** [comment]
Thanks @twoeths !!   I was looking at metrics of fea1 and feat3 which both have about the same code (node 20 and all other 1.19 commits) and only feat1 shows that weird db pattern.  feat3 and feat4 (the branch without the level update) look the same with a "normal" pattern of db activity.  Not entirely convinced this is the root cause we are hunting for sadly.... 

### `feat1`
Screenshot 2024-05-31 at 10 33 33 AM

### `feat3`
Screenshot 2024-05-31 at 10 33 41 AM

### `feat4`
Screenshot 2024-05-31 at 10 33 48 AM

**Comment by matthewkeil** [comment]
> At first glance looks like setting `classic-level` version to `1.2.0` would do it? This would give us more control on what version is used and prevent accidental upgrades.
> 
> Not a lot of changes with `1.4.1` but [some](https://github.com/Level/classic-level/commit/b9fd5e99cfb546229d222ba6c3acb5d7384759a4) are related to napi refactorings. Given that this lib doesn't appear super active and our surface area with `leveldb` is thin, might be a potential future candidate for some `rust` based binding.

~~I'm also curious if the base c implementation had any updates.  Will take a peek.  We had a memory leak in batch processing that came out of the native layer so could be that its not in the bindings or js layer.~~

Update: Last LevelDB update was quite a while ago... so you are def right @jeluard if level proves to be the issue we are hunting for

https://github.com/google/leveldb/releases

**Comment by twoeths** [comment]
> At first glance looks like setting classic-level version to 1.2.0 would do it? This would give us more control on what version is used and prevent accidental upgrades.

yes I wanted to only downgrade `classic-level` but still got v1.4.1 in the end maybe because v1.4.1 was already in `yarn.lock` so got Matt's branch as a quick try. Feel free to go for it if you can find a solution @jeluard 

need to confirm the hypothesis through, testing in progress

**Comment by twoeths** [comment]
this is not the cause, added the `classic-level` rebuild to a service deployment and it's still fine

Screenshot 2024-05-31 at 20 45 38

while this PR itself still have bad performance

Screenshot 2024-05-31 at 20 46 15

**Comment by twoeths** [comment]
> while this PR itself still have bad performance

it was a docker deployment

**Pull request closed without merging**
