### PR TITLE
fix: block value in `produceBlockV3` should be in wei

### LINKED ISSUE #6259: Payload and block values should be in wei
Based on https://github.com/ethereum/beacon-APIs/pull/400 both should be denominated in _wei_.

### PR DESCRIPTION
**Pull request by ensi321**
**Description**

Currently `consensusBlockValue` is in Gwei. To align with `executionPayloadValue`, block value is converted into Wei. 

Note that values in `RewardCache` will still be in Gwei for the purpose of rewards API, which is denominated in Gwei. 

- Closes #6259 
- spec PR https://github.com/ethereum/beacon-APIs/pull/400

### CODE REVIEW

**Comment by nflaig** [comment]
> Note that values in RewardCache will still be in Gwei for the purpose of rewards API, which is denominated in Gwei.

You are right the spec states to use gwei for rewards API but isn't this a bit odd? I feel like we should use the same unit across all APIs

**Comment by ensi321** [comment]
> > Note that values in RewardCache will still be in Gwei for the purpose of rewards API, which is denominated in Gwei.
> 
> You are right the spec states to use gwei for rewards API but isn't this a bit odd? I feel like we should use the same unit across all APIs

Yea I have pointed this out in `api` channel on Discord. 

I think we either be inconsistent with payload value in the same endpoint, or be inconsistent with reward value from other endpoints. It's unideal either way.

**Comment by ensi321** [comment]
I just realized the beacon API PR that proposes block value in Wei hasn't been merged yet. We can hold off merging this until that PR is merged.

**Comment by nflaig** [comment]
> We can hold off merging this until that PR is merged.

yeah, let's wait a bit until there is a final decision on this and the spec PR is merged

**Review by g11tech — DISMISSED** [review]
blocked till the spec is updated

**Comment by g11tech** [comment]
@ensi321 can you also link the spec PR in the description (it may be in the linked issue but direct linking here is more useful)

**Comment by ensi321** [comment]
> yeah, let's wait a bit until there is a final decision on this and the spec PR is merged

PR is merged. I believe we can continue reviewing this PR @nflaig @g11tech

**Review by nflaig — APPROVED** [review]
lgtm

**Review by wemeetagain — APPROVED** [review]
lgtm

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.15.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.15.0) :tada:

**Pull request merged**
