### PR TITLE
feat: increase default target peers to 100

### LINKED ISSUE #5799: Increase target peers to 100, max peers to 110
### Problem description

Gradually all nodes will subscribe to exactly 2 subnets per node due to https://github.com/ethereum/consensus-specs/pull/3312 so it'll not easy to find enough subnet peers

### Solution description

We should track different things:
- Is it over 110 peers at some time, what's the consequence of that #5732
- Network volume, especially when we join a sync committee, only do it once we resolve #5741 ?
- Track time to publish a message, especially messages on core topics. See https://github.com/ChainSafe/js-libp2p-gossipsub/pull/451

### Additional context

Also other clients already increased to 100 peers (lighthouse, nimbus), lodestar should do the same

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

- Increase target peers to 100 like other clients
- Has tested this option for 3 days and haven't seen it affect memory. Now this branch makes it as default option

**Description**

- Also it make sense to enable gossipsub batch publish option to serialize published messages once in gossipsub

Closes #5799

### CODE REVIEW

**Comment by twoeths** [comment]
These metrics are captured on the test mainnet node, it's consistent to other nodes
- I don't see the heap memory increased, this is on main thread

Screenshot 2024-03-20 at 08 36 46

- network thread heap memory don't increase as well, but its gc time increased a bit

Screenshot 2024-03-20 at 08 40 18

- it's interesting that having more peers help us receive block 5ms - 11ms sooner , this is consistent on all nodes
Screenshot 2024-03-20 at 08 43 12

- mesh peers are the same to stable
Screenshot 2024-03-20 at 08 46 34

- peer count is as expected (lg1k node)
Screenshot 2024-03-20 at 08 53 10

**Comment by twoeths** [comment]
after 4 days, I found `process_heap_bytes` increased on the test mainnet node

Screenshot 2024-03-22 at 10 20 55

heap allocation on network thread spiked then get back to normal (see https://github.com/ChainSafe/lodestar/issues/6106), it's stable on the mainnet thread
Screenshot 2024-03-22 at 10 22 57

**Comment by nflaig** [comment]
I've been running my mainnet node on 100 peers for almost 2 weeks now, effectiveness looks pretty good so far but I am also seeing a increase in heap memory over time.

image


image

Might also be related to Deneb upgrade or a memory leak we introduced in the new release. Will collect some metrics with 50 peers now to see if it is related to increasing the peer count.

**Comment by twoeths** [comment]
@nflaig thanks for the input, that looks pretty bad
seems there's a memory leak in network thread and it only happens with real mainnet node #6595
it's not likely we can increase peer count to 100 by default, need more time to figure out the memory issue first

**Comment by nflaig** [comment]
Network worker heap memory increase seems unrelated to increasing the peer count, still seeing the same with 50 peers

image

Will collect some more data with 100 peers, I did not take a heap snapshot yet because I forgot to enable lodestar api namespace..

**Comment by nflaig** [comment]
Was able to take a heapsnapshot from my node while the network thread memory was at almost 1 GB
image

[network_thread_2024-04-08T15-34-10.340Z.tar.xz](https://www.dropbox.com/scl/fi/znfbomze7ph54zub0b8cr/network_thread_2024-04-08T15-34-10.340Z.tar.xz?rlkey=2xcse0a6ehdljgr7r6u1brsz8&dl=0)

**Comment by twoeths** [comment]
there are a lot of users already increased the target peers to 100 and it's noted that the performance of nodes increases a lot with this so we decided to get this PR in.
The heap memory leak issue in network thread is actually not related to peer count and was tracked in https://github.com/ChainSafe/lodestar/issues/6595

**Review by nflaig — APPROVED** [review]
:tada:

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.18.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.18.0) :tada:

**Pull request merged**
