### PR TITLE
Added dockerfile

### PR DESCRIPTION
**Pull request by zscole**
I added a dockerfile.

### CODE REVIEW

**Review by Mikerah — APPROVED** [review]

**Comment by Mikerah** [comment]
Need an approval from @wemeetagain or @GregTheGreek to make sure this runs on other machines.

**Comment by Mikerah** [comment]
Resolves https://github.com/ChainSafeSystems/lodestar/issues/135

**Comment by GregTheGreek** [comment]
@zscole Can you remove the .DS_STORE changes please

**Comment by zscole** [comment]
oh snap my b

**Comment by wemeetagain** [comment]
it breaks for me, I think it's our fault. :rofl: 
```
$ sudo docker build -f Docker/Dockerfile .

...

> nyc -r lcov -e .ts -x "*.test.ts" mocha -r ./.babel-register "tests/**/*.test.ts" && nyc report

/lodestar/node_modules/@babel/core/lib/transformation/normalize-file.js:209
    throw err;
    ^

SyntaxError: /lodestar/src/constants/enums.ts: Export 'Domain' is not defined (11:2)

   9 | 
  10 | export {
> 11 |   Domain,
     |   ^
  12 | };
```

**Comment by wemeetagain** [comment]
This is a good start to getting up and running. :100: 
We can iterate and iron out the kinks.

**Review by wemeetagain — APPROVED** [review]

**Pull request merged**
