### PR TITLE
Set udp to enr

### LINKED ISSUE #4623: Lodestar does not add UDP to ENR
**Describe the bug**

Jorge from Netheremind got the ENR from Lodestar shortly after start-up and the ENR did not had a UDP port.

**Expected behavior**

Add UDP port to ENR on startup from configured --port flag

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

- We haven't set udp in enr due to the memory issue, see https://github.com/ChainSafe/lodestar/issues/4623#issue-1393788493
- Need to set it back

**Description**

- Root cause of memory issue is `@chainsafe/snappy-stream`, migrated to 5.1.2
- When we set udp to enr, node receives so many incoming peers and libp2p prune peers randomly, so setting `maxConnection` (as our `maxPeers`) to tcp helps, thanks @dapplion 

Closes #4623

**TODOs**

- [x] Verify the PR in feat1 group
- [x] Same work without setting `maxConnection` to `tcp` to verify the memory leak issue faster in `nogroup 2 3`

### CODE REVIEW

**Review by dapplion — APPROVED** [review]
Pre-approving pending testing. Thank you so much for the debugging effort @tuyennhv :heart:

**Review by wemeetagain — APPROVED** [review]
The metrics on this look really nice. :+1: 

> Same work without setting maxConnection to tcp to verify the memory leak issue faster in nogroup 2 3

I recommend we do more experimentation in a future PR and merge this as-is

**Comment by twoeths** [comment]
CPU usage is reduced from 145% (as in unstable 1k ) to 120% - 130%

Screen Shot 2023-01-14 at 13 56 36

**Comment by twoeths** [comment]
works on nogroup `2 & 3` nodes:

Screen Shot 2023-01-15 at 16 11 30

Screen Shot 2023-01-15 at 16 12 18

**Pull request merged**
