### PR TITLE
Track balances as Number64UintType

### LINKED ISSUE #2972: Track balance as Number
Currently a balance is of type Gwei, 1ETH is tracked as 1_000_000_000 and as a bigint.

We can track balance as a number for faster processing and for saving memory too, because it's unlikely that a validator balance has more than 9M ETH as calculated below

```
> 2 ** 53 / 1000000000
9007199.254740993
```

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

Track `balances` as the new `Number64UintType` of ssz for faster processing, same for slot, epoch

**Description**

This depends on https://github.com/ChainSafe/ssz/pull/159

+ For all Number64 type, use the new `Number64UintType` of ssz
+ Track balances as a number too `new ListType({elementType: Number64, limit: VALIDATOR_REGISTRY_LIMIT})`
+ Update CachedBalancesList: remove `persistent-ts` array there to save memory, move it to `balanceList.ts`
+ Increase balance/decrease balance: use the new api `tree_applyDeltaAtIndex()` or `tree_applyDeltaInBatch()` to avoid the pattern `balances[i] = balances[i] + delta` (which have to do `deserialize` then `serialize`)
+ `processRewardsAndPenalties`: use the new api `tree_newTreeFromDeltas()` to build balances tree and avoid BigInt calculation and Uint8Array allocation, it return new number[] array to be used for next step of epoch transition

Closes #2972 #2049

More related improvement could be done after this PR:
+ Track effectiveBalance as number too, may simplify calculation at different places a bit (see #2981)

### CODE REVIEW

**Comment by dapplion** [comment]
Killer improvements!! :fire: amazing job

**Comment by twoeths** [comment]
> Killer improvements!! 🔥 amazing job

just want to clarify that most of the improvement come from the new ssz and we already merge that to master. The main improvement for this PR is `processRewardsAndPenalties` and removing a separate `balances` persistent-ts cache

**Comment by twoeths** [comment]
| #  |this branch | master | ratio|
| -- | -- | -- | -- |
| pyrmont_e62330 - altair processRewardsAndPenalties | 78.252 ms/op | 213.63 ms/op | 0.37 |
| altair processRewardsAndPenalties - 250000 normalcase | 123.93 ms/op | 338.31 ms/op | 0.37 |
| altair processRewardsAndPenalties - 250000 worstcase | 139.13 ms/op | 281.75 ms/op | 0.49 |
| mainnet_e58758 - phase0 processRewardsAndPenalties | 102.81 ms/op | 273.29 ms/op | 0.38 |

**Review by dapplion — APPROVED** [review]
Looks great nice work!

**Pull request merged**
