### PR TITLE
fix: simplify snappy frame encoding

### PR DESCRIPTION
**Pull request by wemeetagain**
**Motivation**

During upgrade to node 20, I noticed that our `snappy` dependency was out of date.
But worse, this dependency was hidden in our snappy frame compression library, which is a poorly maintained, untyped fork at https://github.com/chainsafe/node-snappy-stream

**Description**
This is a minimal implementation of snappy frame compression that doesn't rely on node streams, stream-to-it, and half-a-dozen other libraries in node-snappy-stream. Instead it uses an async generator to add the framing.

The `snappy` dependency has also been updated to v7.x.x

### CODE REVIEW

**Review by dapplion — COMMENTED** [review]
Can you add a test with pre-generated compress data? Current tests check the loop data -> compress -> uncompress -> check eq. Would be good to have data -> compress --> check eq, uncompress -> check eq, where the compressed data is generated with the previous version proven to work

**Comment by wemeetagain** [comment]
We already have those tests :) `reqresp/test/unit/encoders/encodingStrategies/sszSnappy/{encode,decode}.ts`

**Comment by wemeetagain** [comment]
@ChainSafe/lodestar ready for rereview

**Review by dapplion — DISMISSED** [review]
LGTM!

**Review by dapplion — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.10.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.10.0) :tada:

**Pull request merged**
