### PR TITLE
fix: check pubkey or validator index known to a state

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

Got this error in mekong devnet found by @nflaig 

```
Dec-05 20:57:46.624[chain]           debug: Block error slot=207552, code=BLOCK_ERROR_PRESTATE_MISSING, error=Cannot read properties of undefined (reading 'exitEpoch')
```

```
TypeError: Cannot read properties of undefined (reading 'exitEpoch')
    at CustomContainerTreeViewDU.get [as exitEpoch] (/home/nico/projects/ethereum/lodestar/node_modules/@chainsafe/ssz/src/viewDU/containerNodeStruct.ts:78:61)
    at processPendingDeposits (file:///home/nico/projects/ethereum/lodestar/packages/state-transition/src/epoch/processPendingDeposits.ts:55:37)
```

**Description**

Consider this scenario when we have multiple epoch transitions per epoch, given n is the epoch transition slot
Screenshot 2024-12-06 at 10 44 08

pending deposits of the whole epoch are processed by pulling up (n-1) state, then we add pubkeys to `indes2pubkey`
then at slot n, we process epoch transition again, found validator index from `index2pubkey` but validator is not added to registry of the state, then the issue happen

To resolve it, I added `isPubkeyKnown()` function and `isValidatorKnown` utils and use them at concerned place.

**Steps to test or reproduce**

resync mekong?

### CODE REVIEW

**Review by ensi321 — APPROVED** [review]

**Review by nflaig — APPROVED** [review]
LGTM

**Comment by nflaig** [comment]
> Steps to test or reproduce
resync mekong?

This will be hard to reproduce, isn't the only way to trigger this issue if we run the epoch transition twice, ie. if there is a reorg across epoch boundaries?

From [looking at mekong nodes](https://dora.mekong.ethpandaops.io/slots/filtered?f&f.missing=1&f.orphaned=1&f.pname=lodestar), there is just a single node (lodestar-geth-3) that has this issue.

**Comment by michaelsproul** [comment]
We have a similar cache in Lighthouse, but I thought we were safe from reorgs because deposits are only applied once they are finalized. i.e. the pubkey cache only contains keys of validators from finalized states, and these can't change during a reorg.

Does Lodestar add a validator to the pubkey cache prior to its finalized deposits being processed, or is there some corner case where a new validator is created from a non-finalized deposit?

**Comment by twoeths** [comment]
@michaelsproul there is a corner case when head is at slot (n-1) (given n % 32 = 0), we pull up the state to get through epoch transition, find new finalized checkpoint, process deposits of finalized validator, update `pubkey2Index` and update the state. At slot n, we process epoch transition again, find the same new finalized checkpoint, but did not add new validators to registry because it's know in `pubkey2Index` since it's shared.

so basically it may happen when we have multiple epoch transitions per epoch which rarely happen in lodestar, as described in the description. If lighthouse always have 1 epoch transition per epoch then it'll not happen

image

to answer your questions
> Does Lodestar add a validator to the pubkey cache prior to its finalized deposits being processed

no

> or is there some corner case where a new validator is created from a non-finalized deposit?

no validator is created from a non-finalized deposit, but there is a corner case as described above

**Comment by michaelsproul** [comment]
Thanks @twoeths, that's interesting. Lighthouse isn't vulnerable to this bug even with multiple epoch transitions because we (inefficiently) have two pubkey caches: one on the state and one global one. So the first epoch transition would add to that state's cache and the global one, while the second would add to its own state cache and perform an idempotent add to the global cache.

In future we are hoping to eliminate this duplication and will keep this issue in mind. I think we will either use a persistent data structure that shares the bulk of data but may diverge between states (and the global cache), or epoch-tagged validators so that the API is something like:

```rust
fn validator_index(&self, pubkey: PublicKey, epoch: Epoch) -> Option<u64>;
```

and this would return `None` for `epoch<=N - 1` and `Some(..)` only for `epoch>=N`.

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.24.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.24.0) :tada:

**Pull request merged**
