### PR TITLE
chore: release 1.9.0

### PR DESCRIPTION
**Pull request by wemeetagain**

### CODE REVIEW

**Comment by twoeths** [comment]
@wemeetagain  I just did a force push for `v1.9.0-rc.3`

**Comment by twoeths** [comment]
this is result of 3 day testing on a real mainnet node.
- Less dropped attestations

Screenshot 2023-06-22 at 08 37 33

- while there are the same received RPCs (meaning same mesh peers)

Screenshot 2023-06-22 at 08 38 20

- Gossip Block Received/Processed time is the same

Screenshot 2023-06-22 at 08 39 41

- rss is the same

Screenshot 2023-06-22 at 08 41 03

- while cpu is 60% higher (could be because we process more attestations)

Screenshot 2023-06-22 at 08 41 25

- other metrics are the same to v1.8.0 (Peer Stats, Req/Resp)
- Update on Jun 23: `submitPoolAttestations` api is higher since v1.9.0

Screenshot 2023-06-23 at 05 34 36

**Review by philknows — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.9.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.9.0) :tada:

**Comment by twoeths** [comment]
[0627_v1.9.0_mainnet_subscribeAllSubnets.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/11878842/0627_v1.9.0_mainnet_subscribeAllSubnets.cpuprofile.zip)

**Pull request merged**
