### PR TITLE
feat: enable debug apis by default

### LINKED ISSUE #6822: Consider enabling debug namespace by default
Vouch requires debug api to be enabled as it uses the state to determine the validators statuses. This means it is required [to pass --rest.namespace flag](https://github.com/attestantio/vouch?tab=readme-ov-file#lodestar) to work with Lodestar. All other clients have debug apis enabled by default.

### PR DESCRIPTION
**Pull request by nflaig**
**Motivation**

- https://github.com/ChainSafe/lodestar/issues/6822

**Description**

Enable debug apis by default, see referenced issue for rationale.

Closes https://github.com/ChainSafe/lodestar/issues/6822

### CODE REVIEW

**Comment by philknows** [comment]
Consensus on today's standup is that we would feel a lot more comfortable to enable by default only if we had DOS protection measures in place. Something like #6838 where we have protection measures and adding a CLI flag disabling certain endpoints/functionality. 

It was also suggested that we should make our documentation note more prominent about having to manually turn on debug API. Argument is that experienced power users of Lodestar will be able to enable it via flag rather than burdening inexperienced users with exposing this risk by default.

**Comment by nflaig** [comment]
> Consensus on today's standup is that we would feel a lot more comfortable to enable by default only if we had DOS protection measures in place

After watching the recording and what was discussed there, it feels to me more like a misunderstanding of the current situation. Enabling debug routes by default does not introduce any new DoS vector as the same can already be achieved by calling `getStateValidators` api which is part of `beacon` namespace.

> Something like https://github.com/ChainSafe/lodestar/issues/6838 where we have protection measures and adding a CLI flag disabling certain endpoints/functionality.

Whether or not we implement a solution for #6838 is not relevant for this PR. The issue is meant to address protecting public beacon nodes which have `debug` namespace enabled explicitly already.

> rather than burdening inexperienced users with exposing this risk by default.

If operators / stakers expose their beacon api publicly due to misconfiguration, having their node go down due to oom is the least of their worries. Please see  https://github.com/ChainSafe/lodestar/issues/6822#issuecomment-2135504604. and just in general, enabling debug endpoints by default doesn't introduce any new risks, as mentioned multiple times (happy to be proven otherwise)


> It was also suggested that we should make our documentation note more prominent about having to manually turn on debug API. Argument is that experienced power users of Lodestar will be able to enable it via flag

Our client should just work by default, people trying to use ethdo or other tooling that requires debug routes might not be advanced users that know about these different api namespaces. I've seen plenty of users facing this issue with Lodestar specifically because **all** other clients enable the `debug` namespace by default already. There was even discussion on the beacon-api repo to move it out of `debug` namespace (https://github.com/ethereum/beacon-APIs/pull/357) but it was closed due to friction this would create changing the path, not because it would introduce a risk.

As a side note, a lot of tooling (e.g. eth-docker) already enables `debug` by default ([ref](https://github.com/eth-educators/eth-docker/blob/1935139d74d68b182f0bb670bb8e32e6f921a94c/lodestar.yml#L64-L65)) because of the UX degradation mentioned above of having the user figure this out themselves.

**Comment by matthewkeil** [comment]
> > Consensus on today's standup is that we would feel a lot more comfortable to enable by default only if we had DOS protection measures in place
> 
> After watching the recording and what was discussed there, it feels to me more like a misunderstanding of the current situation. Enabling debug routes by default does not introduce any new DoS vector as the same can already be achieved by calling `getStateValidators` api which is part of `beacon` namespace.

Makes sense.  I thought getting the state was the only route that causes an issue.

> > Something like #6838 where we have protection measures and adding a CLI flag disabling certain endpoints/functionality.
> 
> Whether or not we implement a solution for #6838 is not relevant for this PR. The issue is meant to address protecting public beacon nodes which have `debug` namespace enabled explicitly already.

Also makes sense.

> > rather than burdening inexperienced users with exposing this risk by default.
> 
> If operators / stakers expose their beacon api publicly due to misconfiguration, having their node go down due to oom is the least of their worries. Please see [#6822 (comment)](https://github.com/ChainSafe/lodestar/issues/6822#issuecomment-2135504604). and just in general, enabling debug endpoints by default doesn't introduce any new risks, as mentioned multiple times (happy to be proven otherwise)

I tend to lean towards this as an issue but truth be told, it can be solved with documentation.  I also tend to think that the single-threaded nature of JS causes more risk than just OOM.  Large api requests halt the world for everything else so its also worth noting this in the docs if we turn this on by default.

> > It was also suggested that we should make our documentation note more prominent about having to manually turn on debug API. Argument is that experienced power users of Lodestar will be able to enable it via flag
> 
> Our client should just work by default, people trying to use ethdo or other tooling that requires debug routes might not be advanced users that know about these different api namespaces. I've seen plenty of users facing this issue with Lodestar specifically because **all** other clients enable the `debug` namespace by default already.

Agreed.  I have noticed a lot of issues related to this and I suppose the UX of having it on by default may sway my opinion considering the discussion above.

> There was even discussion on the beacon-api repo to move it out of `debug` namespace ([ethereum/beacon-APIs#357](https://github.com/ethereum/beacon-APIs/pull/357)) but it was closed due to friction this would create changing the path, not because it would introduce a risk.

Yes, but this was what lighthouse mentioned and this is very much not the case for us....  The node stops with a 400mb api response.  https://github.com/ethereum/beacon-APIs/pull/357#issuecomment-1742634965

> As a side note, a lot of tooling (e.g. eth-docker) already enables `debug` by default ([ref](https://github.com/eth-educators/eth-docker/blob/1935139d74d68b182f0bb670bb8e32e6f921a94c/lodestar.yml#L64-L65)) because of the UX degradation mentioned above of having the user figure this out themselves.

I tend to see this in a new light but would like to put this thought forward, if the consumers are not seeing the note in the docs about turning on the debug namespace will they also miss the note about protecting one's node from attacks.

If we ensure that idea is front-and-center (even more prominently displayed in getting-started, on the readme, etc), that open apis are risky (should be common sense but that is definitely not so common) I suppose this will be a good change from a DX perspective...

**Comment by nflaig** [comment]
> Yes, but this was what lighthouse mentioned and this is very much not the case for us.... The node stops with a 400mb api response. https://github.com/ethereum/beacon-APIs/pull/357#issuecomment-1742634965

I would argue it's worse in case of Lighthouse because their node will bring down the whole server, maybe they are streaming the data more efficiently but without proper rate limiting in place this is a huge DoS vector for them as well. that's why we wanna have something like https://github.com/ChainSafe/lodestar/issues/6838 ...the `getStateValidators` response is more than 600MB (json-serialized) on mainnet, no server can handle serialization this if there are 100x consecutive requests..not even rust

> they also miss the note about protecting one's node from attacks.

Right now, a user has to go out of their way to expose the beacon api, you have to set `--rest.address 0.0.0.0`, ignore the warning logged in the console, configure port-forwarding (in case of home staker) and have no firewall set up.

and we have a warning in the docs already
image

and console
```
warn: REST API server is exposed, ensure untrusted traffic cannot reach this API
```

If there are further ideas how we can warn about the api being exposed I am all for it. We could push for having authentication (similar to keymanager api) enabled by default but it will be hard to get consensus on this on spec level, and I don't see it as useful either.

**Comment by wemeetagain** [comment]
> getStateValidators

Ah yes, forgot about that terrible endpoint.
Are there any efforts to deprecate the worst offenders?

Noting that an exposed API is already a DoS vector, it seems ok to add the debug namespace by default.

I guess the hope would be that we could disable the worst endpoints / variants by default.
The hope is that an exposed API would go from terrible DoS vector (where on the order of 1 bad request blows up a node) to less-terrible DoS vector (where on the order of 1000 requests blow up the node).

**Comment by nflaig** [comment]
> Are there any efforts to deprecate the worst offenders?

There are efforts but since this api is required by a lot of infrastructure / tooling around the CL (and the VC itself) it is required to provide an alternative, if all offenders support ssz, we could at least disable JSON on those, see https://github.com/ethereum/beacon-APIs/pull/449 for potential solution.

> The hope is that an exposed API would go from terrible DoS vector (where on the order of 1 bad request blows up a node) to less-terrible DoS vector (where on the order of 1000 requests blow up the node).

yeah that would the best outcome we can get if people wanna expose the beacon api directly. It will still be quite easy to DoS, if people wanna run a infrastructure provider like Infura for the CL, they will have to implement a caching layer and other protections either way.

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.20.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.20.0) :tada:

**Pull request merged**
