### PR TITLE
refactor: move validator api endpoints to standalone functions

### PR DESCRIPTION
**Pull request by nazarhussain**
**Motivation**

- Make the code readable and maintainable. 
- This will help to maintain over 1000 lines of Validator API code. 
- In next phase we need do a quite a refactoring in block production flow this refactor will make it easy to review and maintain. 

**Description**

- Extract Validator API endpoint implementation to separate functions

**Steps to test or reproduce**

- Run all tests

### CODE REVIEW

**Review by nflaig — CHANGES_REQUESTED** [review]
I don't see how this makes the code more maintainable. Splitting up code just because the file has above X amount of lines of code does not make sense to me. After this PR a lot more boilerplate code is required to add a new api. 

We also lose the git history / blame on the validator api code which is always something we should avoid unless it is really required for a refactoring with strong reasoning behind it (which I don't see from the Motivation in PR description)

**Comment by g11tech** [comment]
i think we can have file splits functionalty wise i.e. attestations related, synccommittee related, block related (produce and publish, and hence please no function renaming, also build on top of this PR: #6236 as this and its base PR: #6227 are high priority and need to be in the next milestone for deneb release) 

boiler plate `build...` wrapper isnt too much imo but yea we don't need to go a super deep endpoint level split

**Comment by nazarhussain** [comment]
If I spin up there is tons of literature on the topic, but the basic rule of thumb have a global agreement. 

**More readable code is more maintainable code.**

And readability of a 1000 lines of single function nested upto 4-5 levels is less than of a 100 lines of function. Consider the fact that here we are not taking about `index.ts` file as 1000 lines, rather `getValidatorApi` of 1000 lines function.

Few references: A very common used practices is Airbnb Style Guide, which suggest [50 lines per function](https://github.com/airbnb/javascript/blob/11ab37144b7f846f04f64a29b5beb6e00d74e84b/packages/eslint-config-airbnb-base/rules/style.js#L224)  and [300 lines per file](https://github.com/airbnb/javascript/blob/11ab37144b7f846f04f64a29b5beb6e00d74e84b/packages/eslint-config-airbnb-base/rules/style.js#L217). An other industry best practices guide for Ruby even go strict and suggest to have [10 lines per method](https://github.com/rubocop/ruby-style-guide?tab=readme-ov-file#short-methods). If I remember correctly Bob Martin author of  Clean Code suggested to have it upto 100 lines per function. 

So we can debate on number of lines but bloating a function to unlimited number lines is not something even debatable. 

Git history is well preserved and can be traced back even if code is moved to different files, you just have to follow a different tree path on some level. If we really make git history a blocker for refactoring, then we can't really improve any product. 

The other reference point to split by behavior is not gonna work because each team member may have different understanding of it. So splitting per endpoint is straight forward for everyone to understand. And having idiomatic smaller higher order functions have a lot of text book benefits that I don't want to list here.

**Comment by nflaig** [comment]
> rather getValidatorApi of 1000 lines function

That's not a single function, you could use a class instead and would achieve the same result. If indentations are a concern could use a class + methods which would reduce the depth by one but honestly better to review each function see if improvements can be done there.

> Few references

I don't think either of those are helpful for this argument.

> So we can debate on number of lines but bloating a function to unlimited number lines is not something even debatable.

I am not debating this, my points are
- more boilerplate code (less maintainable)
- git history lost for no good reason
- weak reasoning behind refactoring: "Make the code readable and maintainable", I would argue it is less readable if you want to review the validator api as you have to navigate through a bunch of files.

> Git history is well preserved and can be traced back even if code is moved to different files

Just look at the git diff of this PR (+1,193 −937), it's not reviewable. I would have to trust that you properly copy-pasted the code and made no mistakes.

> If we really make git history a blocker for refactoring, then we can't really improve any product

Again, not part of my argument, never said it is a blocker but there should be strong reasoning to move code around like that which this PR does not have.


---

This is my subjective opinion which can probably only be changed if there is a good and objective argument for this refactoring which I think is something we should have for every proposed code change.

**Comment by ensi321** [comment]
As a contributor who recently picked up the validator api code, let me put in my two cents. I think while it seems large and overwhelming (>1000 lines of code), its organization is good but a little messy.

Something I observed:
1) There are some "utility" functions like `getGenesisBlockRoot` and `notOnOptimisticBlockRoot` and they are mixed with the endpoint functions. 
2) Some endpoint functions are directly defined in the return statement, some are defined in variables and later be fed inside the return statement (eg. `produceBlockV3`) 

For 1, I think they can be managed separately and they are trivial enough that losing git history might not be a big deal compare to endpoint functions. (I could be wrong). `ValidatorEndpointDependencies` makes sense to me and the extra amount of boilerplates doesn't impact too much of readability and reviewability. 

For 2, it is not clear to me why some are defined in the former way and some are defined in the latter way. My thought was functions with complex logic like `produceBlockV3` warrants a separate variable. But then `getProposerDuties` which looks complex to me, is directly defined in the return statement. 

My humble suggestion is moving forward, any new endpoint with complex logic should be placed in a standalone file under `endpoints` folder as illustrated in this PR. New endpoints with simple logic can be directly defined in the return statement in `index.ts`. Existed endpoints should be left as is to avoid sudden large change to the codebase, and loss of git history. 

For the purpose of this PR, I think `produceBlockV3` can be the first endpoint to be placed in a standalone file to set an example for the future complex endpoints. And the loss of git history might be mild since it's one of the newer endpoints.

**Comment by nflaig** [comment]
Moving everything that is defined before the return statement out of the file would be a good first step. Everything block production related could definitely deserve it's own file, not a big fan of endpoints folder for that but maybe just a `produceBlock.ts` file in the same folder?

What I don't like in this PR are cases were we add 12 lines of boilerplate code for 1 line of actual code.
https://github.com/ChainSafe/lodestar/blob/f6907c2ddc13f4da8fa9dca98805a9b908526b14/packages/beacon-node/src/api/impl/validator/endpoints/submitBeaconCommitteeSelections.ts#L9-L11

Previously, the api impl type was also inferred when updating the route definition, now it requires a manual step to pick the correct type and clue it together in index file. 

And the last thing is that the validator impl now deviates from how we define other routes, do we move the others into separate file as well and why is it not part of this PR then?

I feel like moving everything into separate files should be a last resort if all other attempts of refactoring failed or are insufficient.

**Comment by dapplion** [comment]
Strongly in favour of keeping git history and not moving existing code around

**Comment by philknows** [comment]
I don’t work with the codebase as much as you guys but would like to see a decision about it today if possible. There should be a decision on how to organize the existing functionality in which @dapplion is strongly against and also a decision on how to organize this going forward. Some of the newer guys opinions should give a fresh perspective here on what to do.

**Comment by jeluard** [comment]
My 2 cents: generally in favor of improving readability. What could improve it in this specific scenario is having shorter functions, supported by extracted utility functions. It would also help with improving code comprehension (and removing the need for some comments) and testability.
No strong opinions on having one file per endpoints. `git history` is generally important in old enough codebase but might also be an indication of poor code readability :)

**Comment by wemeetagain** [comment]
I've pulled the code locally to give a fair review. Tried to navigate and weigh the pros and cons here and in unstable.
I tend to agree with Nico and Lion for the reasons they mentioned.

I don't really read this file as "a single 1000 line function", rather the file is an implementation of a single interface, `routes.validator.Api`. I tend to read the file as a list of functions, the functions related to the validator namespace of the beacon-apis. The structure we have now is like a prototypical class, with the chain, metrics, etc acting as the class state.

I think some of the utility functions could be pulled out, and either made pure or pulled into methods.

As far as how we should structure code going forward, whether to combine functionality in a single file or move things across files is, imo, somewhat subjective, and shouldn't necessarily be reduced to "smaller file is more readable, so smallest file is most readable".
Some questions I think about:
- What is the conceptual unit of code in this file? A conceptual unit may exist at the code level, as an interface or practical grouping, at the application level, as some domain-specific idea.
- How is this function / module used? Are there multiple consumers of this function / module? If not, what other concept is this code related to?
- How can this conceptual unit of code be simplified or its purpose highlighted? Is there a way to simplify the algorithms? More or better documentation?

Block production may warrant its own file, given the importance in the application. It seems that this was also the original catalyst for this PR.

**Comment by dapplion** [comment]
A bit tangential, but relevant IMO:

I want to comment on a common trend in JS community which is the phobia to long files. Long _may_ indicate opportunities to split code, but they are not intrinsically bad. Splitting a long file because it's long doesn't always help the overall project.

I past example I personally fought to keep as long file is the gossipsub/index.ts file (https://github.com/ChainSafe/js-libp2p-gossipsub/blob/master/src/index.ts). Splitting it always resulted in harder to follow code. We have been doing just fine with it. Even git is smart enough to almost never trigger conflicts even if you edit the same file.

**Comment by wemeetagain** [comment]
Closing this PR now. Feel free to open a PR to refactor utility functions and / or a PR to refactor the block production code.

**Pull request closed without merging**
