### PR TITLE
chore: switch from gtag to plausible

### PR DESCRIPTION
**Pull request by jeluard**
**Motivation**

Use chainsafe analytics platform

### CODE REVIEW

**Comment by nflaig** [comment]
> Use chainsafe analytics platform

By that you mean this is from chainsafe, or something others within chainsafe use already?

And who is managing this?

**Comment by jeluard** [comment]
@nflaig Right, this is the go to chainsafe analytics platform. It's a [SaaS](https://plausible.io/) AFAIK

**Comment by nflaig** [comment]
> @nflaig Right, this is the go to chainsafe analytics platform. It's a [SaaS](https://plausible.io/) AFAIK

can you please add more context to the PR, and was there any discussion on this?

**Comment by jeluard** [comment]
@nflaig This is a request from ChainSafe marketing

**Review by nflaig — APPROVED** [review]
Let's get this in for next release so we don't use two different analytic platforms. And make sure to highlight it in release notes, as part of docs migration.

**Comment by philknows** [comment]
Will add additional context to this. Generally we should refrain from using overly excessive analytics trackers in our software at ChainSafe especially if it’s capturing data that we otherwise wouldn’t need to achieve our goals.

Using some sort of tracker is useful to enhance our documentation to better understand how people navigate our docs and how to improve it. Alongside with understanding our reach as an indication of potential usage outside of staking metrics. #6549 was a stop-gap measure (because it was free and we anticipated v1.18 to be released much earlier) until marketing gave us some sort of direction on what they were using. 

It made sense to use a less intrusive platform and align with what marketing uses for other projects at ChainSafe. This PR aligns with the goal of being less intrusive and using common tools between ChainSafe projects.

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.18.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.18.0) :tada:

**Pull request merged**
