### PR TITLE
feat: add anonymized analytics to docs

### LINKED ISSUE #6549: Add analytics support to documentation website
# Resources

* https://github.com/facebook/docusaurus/issues/7221
* https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag

### PR DESCRIPTION
**Pull request by jeluard**
**Description**

Add anonymized analytics to the docusaurus based docs website.

Fixes #6549

### CODE REVIEW

**Comment by philknows** [comment]
Already discussed this with Julien as a way to get better metrics on our docs for improved dev ex. Understanding users and what they are consuming and how they are consuming our pages will help us create a better experience for them. Not intended for anything more than that and this can be revoked at anytime if there are concerns.

**Review by nflaig — APPROVED** [review]
Looks good to me but for transparency we should probably highlight this in our next release.

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.18.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.18.0) :tada:

**Comment by philknows** [comment]
Sidenote: Google Analytics has been removed via #6680 before publishing the new docs.

**Pull request merged**
