### PR TITLE
State transition unit tests

### LINKED ISSUE #226: [Testing] unit tests for state transition utils

### PR DESCRIPTION
**Pull request by mpetrunic**
Basically this includes sh**t ton of tests haha
I've found and fixed some bugs, probably more of them will occur once I setup spec tests.

I haven't tested some of the methods (mostly process epoch balances) as they are way too complex to write unit tests.

By using stubbed bls, 346 unit tests are executed in less than 8 seconds

resolves #226

### CODE REVIEW

**Comment by mpetrunic** [comment]
> Merging [#235](https://codecov.io/gh/ChainSafe/lodestar/pull/235?src=pr&el=desc) into [master](https://codecov.io/gh/ChainSafe/lodestar/commit/33a7cd7d14a98c9f0d2ba05f8adffcebc106c7fa?src=pr&el=desc) will **increase** coverage by `1.71%`.

Seriously?!? haha

**Comment by GregTheGreek** [comment]
Code coverage is very broken. Makes no sense

**Review by GregTheGreek — COMMENTED** [review]
This is amazing : 🔥 !!!!!! So amazing. I'll double check the tests in a bit but looks great !

**Comment by wemeetagain** [comment]
:heart_eyes: :heart_eyes: Holy cow!

**Review by wemeetagain — APPROVED** [review]

**Review by GregTheGreek — APPROVED** [review]

**Pull request merged**
