### PR TITLE
fix: compute and get head once when producing block

### LINKED ISSUE #6612: Get head once when producing block
### Describe the bug

Consider this scenario:
- block `n - 1` comes really late
- at slot n, head is block `n - 2`, we produce block and get SyncAggregate which all voted for block `n - 2`
- then block `n - 1` come, we get head again it's now block `n - 1`, we set block `n - 1` as `parentRoot`
- then block data is inconsistent

When other node receives the block, it gets state from `parentRoot` and find SyncAggregate signature invalid

```
Mar-28 17:05:11.000[chain]         ^[[36mverbose^[[39m: Clock slot slot=8735124
Mar-28 17:05:11.082[rest]            ^[[34mdebug^[[39m: Exec req-mlkg x.x.x.x produceBlockV3
Mar-28 17:05:11.164[api]           ^[[36mverbose^[[39m: Assembling block with produceEngineOrBuilderBlock fork=deneb, builderSelection=maxprofit, slot=8735124, isBuilderEnabled=true, isEngineEnabled=true, strictFeeRecipientCheck=false, builderBoostFactor=10

Mar-28 17:05:11.165[chain]         ^[[36mverbose^[[39m: Added block to forkchoice and state cache slot=8735123, root=0x020c02ba62299550591532a0ba6f22b4e5732251de9782a1599b28319f1583dd
Mar-28 17:05:11.232[chain]         ^[[36mverbose^[[39m: New chain head slot=8735123, root=0x020c02ba62299550591532a0ba6f22b4e5732251de9782a1599b28319f1583dd, delaySec=12.23200011253357

Mar-28 17:05:11.233[chain]         ^[[36mverbose^[[39m: After importBlock caching postState without SSZ cache slot=8735123
Mar-28 17:05:11.233[chain]           ^[[34mdebug^[[39m: Imported block slot=8735123, recvToValLatency=0.48000001907348633, recvToValidation=0.5480000972747803, validationTime=0.06800007820129395
Mar-28 17:05:11.233[chain]         ^[[36mverbose^[[39m: Block processed slot=8735123, root=0x020c02ba62299550591532a0ba6f22b4e5732251de9782a1599b28319f1583dd, delaySec=12.233000040054321

Mar-28 17:05:11.442[api]             ^[[34mdebug^[[39m: Produced common block body fork=deneb, builderSelection=maxprofit, slot=8735124, isBuilderEnabled=true, isEngineEnabled=true, strictFeeRecipientCheck=false, builderBoostFactor=100
```

### Expected behavior

We should compute then get head once and use it across `produceBlock` flow

### Steps to reproduce

_No response_

### Additional context

should be done before proposer boost reorg #5125

### Operating system

Linux

### Lodestar version or commit hash

v1.17.0

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

- When producing blocks, we compute and get head multiple times which could get multiple heads and our produced block is invalid, see https://github.com/ChainSafe/lodestar/issues/6612

**Description**

- Compute and get head once when producing block
- This is actually from a proposer boost PR https://github.com/ensi321/lodestar/pull/3/files cc @ensi321 

Closes #6612

### CODE REVIEW

**Comment by twoeths** [comment]
n-historical state e2e test is failing, waiting for #6581 to have `forkchoice.getProposerHead()` in order to overwrite it in the `ReorgedForkChoice`

**Comment by twoeths** [comment]
the `getProposerHead()` api is even not consumed after #6581, skipping the test for now, will enable it again once we have the proposer boost work in #5125

**Review by ensi321 — APPROVED** [review]
lgtm

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.18.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.18.0) :tada:

**Pull request merged**
