### PR TITLE
Multiple rpc apis and transports

### PR DESCRIPTION
**Pull request by mpetrunic**
- enabled multiple transports for multiple rpc apis
- moves some method from validator namespace to beacon rpc namespace

### CODE REVIEW

**Comment by GregTheGreek** [comment]
For consistency reasons can you add a description :)

**Comment by GregTheGreek** [comment]
You created a `Beacon API` and moved `getClientVersion`, `getFork`, `getGenesisTime` and `getSyncingStatus` from the validator api to the beacon api?

**Comment by mpetrunic** [comment]
yeah, it' logical The issue creator seems to agree. I can move it back but it doesn't really makes sense

**Review by GregTheGreek — APPROVED** [review]
LGTM

**Review by wemeetagain — APPROVED** [review]
:tada:

**Pull request merged**
