### PR TITLE
add eslint rule to help with import order

### PR DESCRIPTION
**Pull request by dadepo**
**Motivation**

In a previous [PR](https://github.com/ChainSafe/lodestar/pull/3522#discussion_r810566341) it was pointed out that the preferred order for imports should be:

1. Non-chainsafe modules
2. @ chainsafe modules
3. Local paths

This PR enforces this via eslint to make it more applicable. It also updates existing import to adhere with the import rule

### CODE REVIEW

**Comment by dadepo** [comment]
As agreed during the planning meeting, please wait till the ssz refactor is merged before merging this.
Edit: Converted to draft to make it more obvious it should not be merged yet

**Review by wemeetagain — APPROVED** [review]

**Review by dapplion — CHANGES_REQUESTED** [review]
Blocking to after merging https://github.com/ChainSafe/lodestar/pull/3760

**Comment by dadepo** [comment]
Easier to branch from master again and apply the eslint fix (as it has been done here https://github.com/ChainSafe/lodestar/pull/3885), rather than trying to fix this merge conflict. Hence closing this issue.

**Comment by dapplion** [comment]
> Easier to branch from master again and apply the eslint fix (as it has been done [here](https://github.com/ChainSafe/lodestar/pull/3885), rather than trying to fix this merge conflict. Hence closing this issue.

For new PRs you can still force reset a branch at a different point to persist the PR since it's attempting the same thing

**Pull request closed without merging**
