### PR TITLE
Fix sim test log and enable metrics

### PR DESCRIPTION
**Pull request by dapplion**
**Motivation**

2 fixes from developing gossip pull queues

**Description**

- Fix typo in sim test log
- Allow to enable metrics with ENV
- Log stdout file path

CC: @nazarhussain

### CODE REVIEW

**Comment by nazarhussain** [comment]
Seems good but let's get this PR merged first https://github.com/ChainSafe/lodestar/pull/5120, as it will create a lot of conflicts.

**Comment by dapplion** [comment]
> Seems good but let's get this PR merged first #5120, as it will create a lot of conflicts.

Merged #5120 :+1:

**Comment by wemeetagain** [comment]
@dapplion @nazarhussain is anyone going to fix the conflicts?

**Comment by dapplion** [comment]
@nazarhussain Would you mind taking over this PR and re-apply on the new logic?

**Comment by dapplion** [comment]
Stale PR, closing for now. @nazarhussain please re-open if this fixes have not still landed

**Pull request closed without merging**
