### PR TITLE
Docs: fix typo

### PR DESCRIPTION
**Pull request by Evalir**
**Description**

Just found a small typo while going through the docs. :)

**Steps to test or reproduce**

None.

### CODE REVIEW

**Review by dapplion — DISMISSED** [review]
Thanks for the fix! :heart:

**Review by wemeetagain — DISMISSED** [review]
:heart:

**Comment by dapplion** [comment]
@Evalir Would you mind rebasing to current master? That would fix the test errors

**Comment by Evalir** [comment]
Ah yeah @dapplion! No problem, just rebased. Should be good to go when tests pass! (might need a re-approve)

**Review by dapplion — APPROVED** [review]

**Comment by Evalir** [comment]
Alright, all green!

**Pull request merged**
