### PR TITLE
Add bulldozer config

### PR DESCRIPTION
**Pull request by dapplion**
Automate merging PRs on an opt-in basis. Prevents having to come back to merge if reviews are ready before CI passing

### CODE REVIEW

**Comment by mpetrunic** [comment]
There is github option for that, bulldozer is no longer used:
image

**Comment by dapplion** [comment]
> There is github option for that, bulldozer is no longer used:
> image

Yeah, but that would make it mandatory for all PRs. I would like to be an opt-in feature only. Is it possible with the native Github feature?

**Comment by mpetrunic** [comment]
> > There is github option for that, bulldozer is no longer used:
> > image
> 
> Yeah, but that would make it mandatory for all PRs. I would like to be an opt-in feature only. Is it possible with the native Github feature?

probably not. but like, just don't ad second approval 😄

**Comment by dapplion** [comment]
> probably not. but like, just don't ad second approval

Sometimes I do want to add my approval to a PR but I want to wait for Cayman's opinion for example before merging. This setup would prevent me from doing this.

**Comment by wemeetagain** [comment]
> > probably not. but like, just don't ad second approval
> 
> Sometimes I do want to add my approval to a PR but I want to wait for Cayman's opinion for example before merging. This setup would prevent me from doing this.

Seems useful in that case. Probably won't be used every day, but occasionally, you know you want a PR merged, but don't want to wait around for the tests to finish.

**Review by wemeetagain — APPROVED** [review]

**Comment by dapplion** [comment]
@wemeetagain Would be awesome to have this working. Can you take a look at the repo settings if it's all good, and the app is configured fine?

**Pull request merged**
