### PR TITLE
Use GENESIS_SLOT, GENESIS_EPOCH as constants

### LINKED ISSUE #703: Move GENESIS_SLOT/GENESIS_EPOCH to constants
(they were not truly configurable in the first place)
https://github.com/ethereum/eth2.0-specs/pull/1556

### PR DESCRIPTION
**Pull request by twoeths**
## Goal
+ Close #703 
+ There are other changes regarding Eth1Data that should be addressed by #704

### CODE REVIEW

**Review by mpetrunic — COMMENTED** [review]
I think you can calculate genesis epoch from genesis slot though

**Comment by wemeetagain** [comment]
genesis state initialization spec tests failing

**Comment by twoeths** [comment]
> genesis state initialization spec tests failing

It's because we failed to verify deposits' signatures in that test. I notice that there are signature differences between data of spec test 0.10.0 vs 0.10.1-fix, let's revisit this issue in the newly created unit test `deposit2.test.ts`

**Comment by twoeths** [comment]
Do we want to completely remove `GENESIS_EPOCH` constant?

**Review by mpetrunic — APPROVED** [review]

**Review by wemeetagain — APPROVED** [review]

**Pull request merged**
