### PR TITLE
ci: check docs spelling

### LINKED ISSUE #1829: Add tools to improve docs checking
Add CI tools to improve doc checking. See https://www.writethedocs.org/guide/tools/testing/

Implementation example https://github.com/ConsenSys/doc.teku/blob/master/.circleci/config.yml

### PR DESCRIPTION
**Pull request by dapplion**
**Motivation**

Catch spelling mistakes before merging

**Description**

Run PySpelling in CI

Closes https://github.com/ChainSafe/lodestar/issues/1829

### CODE REVIEW

**Comment by wemeetagain** [comment]
```
Run scripts/wordlist_sort_check.sh
sort: .wordlist.txt:2: disorder: APIs
Error: The wordlist is not sorted.
```
https://github.com/ChainSafe/lodestar/actions/runs/5112160804/jobs/9189892314?pr=5527#step:9:6

**Comment by dapplion** [comment]
> ```
> Run scripts/wordlist_sort_check.sh
> sort: .wordlist.txt:2: disorder: APIs
> Error: The wordlist is not sorted.
> ```
> 
> https://github.com/ChainSafe/lodestar/actions/runs/5112160804/jobs/9189892314?pr=5527#step:9:6

Yeah I'm not sure why it breaks in CI. Running sort locally does not error. I tried different sorting algorithms but the one CI always disagrees :(

**Comment by matthewkeil** [comment]
@dapplion got this over the hump.  Please check that the configuration works for our needs

**Comment by matthewkeil** [comment]
The sort seems to be working correctly for me.

This is the correct run from https://github.com/ChainSafe/lodestar/pull/5527/commits/e3cca3bf154b150656639aaf070a2bec88b8e91f
https://github.com/ChainSafe/lodestar/actions/runs/5318793348/jobs/9630614242

This is the "unfixed" run from https://github.com/ChainSafe/lodestar/pull/5527/commits/ca261a216cfd2722803efa50af62431050bc3a1d
https://github.com/ChainSafe/lodestar/actions/runs/5318818176/jobs/9630659354?pr=5527 

This is it running correctly again https://github.com/ChainSafe/lodestar/pull/5527/commits/28290721e769a9519a83a59e980c5c5d5a4c6568
https://github.com/ChainSafe/lodestar/actions/runs/5318859379/jobs/9630735024?pr=5527

**Review by wemeetagain — APPROVED** [review]

**Review by nflaig — COMMENTED** [review]
Retroactively gave this a review, looks really clean!

**Comment by dapplion** [comment]
big thank you @matthewkeil for helping deliver this!

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.10.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.10.0) :tada:

**Pull request merged**
