### PR TITLE
lodestar/cli: overhaul util/version and gitdata

### LINKED ISSUE #2950: lodestar --version should indicate release track
**What is your question?**

Given a binary build from latester:

```
~/lodestar master user@errai
❯ ./packages/cli/bin/lodestar --version
0.28.0

~/lodestar master user@errai
❯ git log -n1 | head -3                
commit 0add9d11d619e8f096d5dbf54ec40a6cf7b14f8f
Author: Lion - dapplion <35266934+dapplion@users.noreply.github.com>
Date:   Wed Aug 11 09:58:29 2021 +0200
```

Couple of issues:
- it does not indicate release track (stable/beta/nightly...)
- it does not indicate code version (git commit, from a release, "dirty"/unstable...)
- in this case, it provides a wrong version number (because master is already ahead of `0.28.0` right?)

Happy to take this one.

### PR DESCRIPTION
**Pull request by q9f**
**Motivation**

Allow for more information in the version string; also clean up util/version and gitdata and reduce duplicated code.

**Description**

* Refactored git data file code and removed some duplicated structures and unused code.
* `util/gitData/*` no longer generates version strings, it just handles all version information (semver, branch, commit, ...)
* `util/version` now generates a proper version string from available data (either from json or from git)
    * example: `v0.28.1/q9-yarn-semver/+14/b0616bfd (unstable)` (semver/branch/number of commits since last release/commit hash/release track if any)
* `util/version` now defines a default release track _(stability)_, for now: `alpha`
* `cli/cli` improved top banner of the `--help` output and also used same information for `--version`

```
~/.opt/chainsafe/lodestar q9-yarn-semver
❯ ./lodestar --version
🌟 Lodestar: TypeScript Implementation of the Ethereum 2.0 Beacon Chain.
  * Version: v0.28.1/q9-yarn-semver/+14/b0616bfd (unstable)
  * by ChainSafe Systems, 2018-2021

~/.opt/chainsafe/lodestar q9-yarn-semver
❯ ./lodestar --help   
🌟 Lodestar: TypeScript Implementation of the Ethereum 2.0 Beacon Chain.
  * Version: v0.28.1/q9-yarn-semver/+14/b0616bfd (unstable)
  * by ChainSafe Systems, 2018-2021

Commands:
  beacon             Run a beacon chain node
  validator          Run one or multiple validator clients
  account <command>  Utilities for generating and managing Ethereum 2.0 accounts
  init               Initialize Lodestar directories and files necessary to run
                     a beacon chain node. This step is not required, and should
                     only be used to prepare special configurations
  dev                Quickly bootstrap a beacon node and multiple validators.
                     Use for development and testing

Options:
      --rootDir     Lodestar root directory                             [string]
      --network     Name of the Eth2 chain network to join
           [string] [choices: "mainnet", "pyrmont", "prater", "altair-devnet-3"]
                                                            [default: "mainnet"]
      --preset      Specifies the default eth2 spec type
                   [string] [choices: "mainnet", "minimal"] [default: "mainnet"]
      --paramsFile  Network configuration file
                                        [string] [default: $rootDir/config.yaml]
  -h, --help        Show help                                          [boolean]
  -v, --version     Show version number                                [boolean]

📖 For more information, check the CLI reference:
  * https://chainsafe.github.io/lodestar/reference/cli

✍️ Give feedback and report issues on GitHub:
  * https://github.com/ChainSafe/lodestar
```

The code also handles the logic of releases and dirty/nightly builds. A release version string is simply `v0.28.1 (alpha)` whereas dirty builds have all info `v0.28.1/q9-yarn-semver/+14/b0616bfd (unstable)`. If git data is not available, it will fall back to lerna.json/package.json and just use `0.28.1`.

This is my first typescript contribution. Review with care. 🙏🏼 

Fixes #2950

### CODE REVIEW

**Comment by q9f** [comment]
I would appreciate if we can make a test point release (v0.28.2) if this is good to go.

**Review by wemeetagain — DISMISSED** [review]
LGTM!

I tested locally against this branch and with a mock v0.28.2 release.
This shouldn't effect our npm releases, it will just make `lodestar --version` more accurate.

**Comment by q9f** [comment]
Ok, fixed the linter issues, this should be good to go.

**Review by wemeetagain — DISMISSED** [review]

**Comment by q9f** [comment]
Sorry, fixed one minor logic issue. Now it's good to go.

**Review by wemeetagain — APPROVED** [review]

**Review by dapplion — APPROVED** [review]
Looks great! Much more accurate and polished than before.

The purpose of the gitData file was to distribute the commit at which that version is built to NPM. Since `(package.json).version` only includes the semver, that information is not available and you need to go to git to check the commit associated to that tag. That has been very useful for nightly releases since we show the "version" tag (version +  branch + commit) in the metrics panel, so very quickly you can check what that node is running from Grafana.

Do you think we achieve a similar behavior is more clean and polished way?

**Comment by q9f** [comment]
Thanks for the review. The logic around gitData was not changed and should be still available. Do you mean, we should expose branch and commit on the metrics even though it's usually a tag release? Metrics is the only place where I changed it for simplicity but happy to add back more details.

**Comment by dapplion** [comment]
@q9f Another better option would be to use nightly versioning as `0.27.1-dev.a6b280` instead of what we have right now that's just a counter `0.27.1-dev.31` :+1:

**Comment by q9f** [comment]
> @q9f Another better option would be to use nightly versioning as `0.27.1-dev.a6b280` instead of what we have right now that's just a counter `0.27.1-dev.31` +1

I just [checked](https://github.com/ChainSafe/lodestar/runs/3354937219), the nighly release version is `0.28.2-dev.3+022659b5fc0` according to Github actions (appending the `--canary` git sha option) but the NPM registry just truncates everything after the `+` to strict (?) semver and it just [remains](https://www.npmjs.com/package/@chainsafe/lodestar/v/0.28.2-dev.2) `0.28.2-dev.3`. I found this: https://github.com/lerna/lerna/issues/1893

> Association with the current NPM versions is very hard. If the published version is `foo@0.1.5-alpha.124`, I have to count 124 commits up from `0.1.4` or go through CI logs to figure out which commit that version is tied to. If it were `foo@0.1.5-alpha.124.3d6bee55` or `foo@0.1.5-alpha.3d6bee55` it would be much easier.
> 
> It looks like Lerna is publishing with the `+${sha}` suffix, but it seems NPM is stripping it out. If that's the case, why is this format [not configurable](https://github.com/lerna/lerna/blob/master/commands/publish/index.js#L359)?



At first glance, there seems no easy way to force lerna to do that properly.

**Comment by dapplion** [comment]
> > @q9f Another better option would be to use nightly versioning as `0.27.1-dev.a6b280` instead of what we have right now that's just a counter `0.27.1-dev.31` +1
> 
> I just [checked](https://github.com/ChainSafe/lodestar/runs/3354937219), the nighly release version is `0.28.2-dev.3+022659b5fc0` according to Github actions (appending the `--canary` git sha option) but the NPM registry just truncates everything after the `+` to strict (?) semver and it just [remains](https://www.npmjs.com/package/@chainsafe/lodestar/v/0.28.2-dev.2) `0.28.2-dev.3`. I found this: [lerna/lerna#1893](https://github.com/lerna/lerna/issues/1893)
> 
> > Association with the current NPM versions is very hard. If the published version is `foo@0.1.5-alpha.124`, I have to count 124 commits up from `0.1.4` or go through CI logs to figure out which commit that version is tied to. If it were `foo@0.1.5-alpha.124.3d6bee55` or `foo@0.1.5-alpha.3d6bee55` it would be much easier.
> > It looks like Lerna is publishing with the `+${sha}` suffix, but it seems NPM is stripping it out. If that's the case, why is this format [not configurable](https://github.com/lerna/lerna/blob/master/commands/publish/index.js#L359)?
> 
> At first glance, there seems no easy way to force lerna to do that properly.

What if we write our own version format? Not use any counter at all and only the commit hash:
```
0.28.2-dev.022659b5fc0
```

**Pull request merged**
