### PR TITLE
Fixing the negative cache hit artifacts in regenFn stats, collapsing the getSate metric panels

### PR DESCRIPTION
**Pull request by g11tech**
**Motivation**
Fixing the negative cache hit artifacts in regenFn stats, collapsing the getSate metric panels into 1 single one as per our analysis is doesn't seemed to be called from anywhere outside regen. 
plus shortning the full length cache panels to half length.

context: https://github.com/ChainSafe/lodestar/issues/3120

how the regen fn panels now look (e.g)

image

how getState is collapsed into just 1:

image

**Description**

Closes #issue_number

**Steps to test or reproduce**

### CODE REVIEW

**Comment by dapplion** [comment]
@g11tech The screen capture shows that one row only has one panel. Please add an empty panel such that all rows have exactly 2 panels with the same width. Otherwise Grafana may bug

**Comment by dapplion** [comment]
Thanks! Looks great overall. Why not add the total count metric call above this line? Then you will only need one

https://github.com/ChainSafe/lodestar/blob/027a62088870727132c2b97353a269149fae6f33/packages/lodestar/src/chain/regen/queued.ts#L141

**Comment by g11tech** [comment]
> @g11tech The screen capture shows that one row only has one panel. Please add an empty panel such that all rows have exactly 2 panels with the same width. Otherwise Grafana may bug

its the last panel (the getState empty one having all its collapsed  metric targets), so wouldnt bug. but will add another empty one just the same.

**Comment by g11tech** [comment]
> Thanks! Looks great overall. Why not add the total count metric call above this line? Then you will only need one
> 
> https://github.com/ChainSafe/lodestar/blob/027a62088870727132c2b97353a269149fae6f33/packages/lodestar/src/chain/regen/queued.ts#L141

thats what is causing negative artifacts, as there is a slight delay between queuing and jobqueue  executing  as well as gets spread over as jobqueue picks and executes. so cant move it in jobqueue's processing scope. this would be same as regen_fn_call_duration_count which was being used earlier.

**Comment by g11tech** [comment]
discord conversation context for condensing the charts further:

image

**Comment by g11tech** [comment]
sample screenshots:
image
image

**Comment by g11tech** [comment]
@dapplion

**Review by dapplion — DISMISSED** [review]

**Comment by dapplion** [comment]
Used the histogram counter `regen_fn_call_duration_count` instead of the new `regen_fn_queued_total` since they should be identical with no added code

**Comment by g11tech** [comment]
> Used the histogram counter `regen_fn_call_duration_count` instead of the new `regen_fn_queued_total` since they should be identical with no added code

@dapplion as discussed over the discord, `regen_fn_queued_total` is required as duration_count is timeshifted (as its is being processed inside job processorr). As agreed, reverted the code to original. formatting feedback included!

**Review by dapplion — APPROVED** [review]

**Pull request merged**
