### PR TITLE
Fix unstable sim tests 

### LINKED ISSUE #4609: SIM tests are unstable and causing delay in CI
**Describe the bug**

It is observed that SIM tests are unstable and failed randomly. Need to fine tune the configurations to avoid false positives to save CI time. 

**Expected behavior**

The SIM tests should be stable and don't include false positive failures. 

**Steps to Reproduce**
Run sim tests. 

**Referece**
https://github.com/ChainSafe/lodestar/actions/runs/3145578978/jobs/5113039772

### PR DESCRIPTION
**Pull request by nazarhussain**
**Motivation**

- Make the assertions more flexible 
- Wait for block from node not the absolute clock time.  

Closes #4609

**Steps to test or reproduce**

Run all CI jobs all together.

### CODE REVIEW

**Comment by wemeetagain** [comment]
@nazarhussain sim tests still failing

**Comment by dapplion** [comment]
Sim tests still failing @nazarhussain

**Comment by nazarhussain** [comment]
@wemeetagain @dapplion Yes I forget to mark this PR draft. It's not ready yet, created PR to run CI jobs.

**Review by dapplion — DISMISSED** [review]

**Comment by dapplion** [comment]
Note: This branch also suffers from the socket timeout then disconnect issue at random, as https://github.com/ChainSafe/lodestar/pull/4621

```
Eph -1/6 1.002[NODE-2]           [32minfo[39m: Synced - slot: -2 - head: 0 0xe228…e2a5 - finalized: 0x0000…0000:0 - peers: 3
Eph -1/7 0.717[NODE-2/network] [36mverbose[39m: peer disconnected peer=16...SAdSwE, direction=outbound, status=CLOSED
Eph -1/7 0.961[NODE-2/network] [36mverbose[39m: peer disconnected peer=16...URw6iT, direction=outbound, status=CLOSED
Eph -1/7 1.001[NODE-2]           [33mwarn[39m: Low peer count peers=1
Eph -1/7 1.001[NODE-2/chain]  [36mverbose[39m: Clock slot slot=-1
```

**Review by dapplion — APPROVED** [review]

**Pull request merged**
