### PR TITLE
Group and refactor the wss options

### PR DESCRIPTION
**Pull request by g11tech**
**Motivation**
Weak Subjectivity sync options have become important and needs their own grouping as the main options were getting cluttered.

This PR refactors the wss cli options and group them in a wss group as wss options are cluttering the main options.
Now they are grouped in the cli help like this:

```
wss
      --wss.weakSubjectivityStateFile   Path or URL to download a weak
                                        subjectivity state file in ssz-encoded
                                        format                          [string]
      --wss.weakSubjectivitySyncLatest  Enable fetching of a weak subjectivity
                                        state via --weakSubjectivityServerUrl.
                                        If an argument is provided to
                                        --weakSubjectivityCheckpoint, fetch the
                                        state at that checkpoint.  Else, fetch
                                        the latest finalized state.    [boolean]
      --wss.weakSubjectivityCheckpoint  Tell the beacon node to fetch a weak
                                        subjectivity state at the specified
                                        checkpoint. The string arg must be in
                                        the form <blockRoot>:<epoch>. For
                                        example, 0x1234:100 would ask for the
                                        weak subjectivity state at checkpoint of
                                        epoch 100 with block root 0x1234.
                                                                        [string]
      --wss.weakSubjectivityServerUrl   Pass in a server hosting Beacon Node
                                        APIs from which to fetch weak
                                        subjectivity state, required in
                                        conjunction with
                                        --weakSubjectivitySyncLatest or
                                        --weakSubjectivityCheckpoint sync.
                                                                        [string]

```

### CODE REVIEW

**Comment by wemeetagain** [comment]
maybe we can do something like:
```
weakSubjectivity
      --weakSubjectivity.stateFile   Path or URL to download a weak
                                        subjectivity state file in ssz-encoded
                                        format                          [string]
      --weakSubjectivity.syncLatest  Enable fetching of a weak subjectivity
                                        state via --weakSubjectivityServerUrl.
                                        If an argument is provided to
                                        --weakSubjectivityCheckpoint, fetch the
                                        state at that checkpoint.  Else, fetch
                                        the latest finalized state.    [boolean]
      --weakSubjectivity.checkpoint  Tell the beacon node to fetch a weak
                                        subjectivity state at the specified
                                        checkpoint. The string arg must be in
                                        the form <blockRoot>:<epoch>. For
                                        example, 0x1234:100 would ask for the
                                        weak subjectivity state at checkpoint of
                                        epoch 100 with block root 0x1234.
                                                                        [string]
      --weakSubjectivity.serverUrl   Pass in a server hosting Beacon Node
                                        APIs from which to fetch weak
                                        subjectivity state, required in
                                        conjunction with
                                        --weakSubjectivitySyncLatest or
                                        --weakSubjectivityCheckpoint sync.
                                                                        [string]
```

**Comment by g11tech** [comment]
@wemeetagain renamed as suggested :slightly_smiling_face: 
```
weakSubjectivity
      --weakSubjectivity.stateFile   Path or URL to download a weak subjectivity
                                     state file in ssz-encoded format   [string]
      --weakSubjectivity.syncLatest  Sync and start from a weak subjectivity
                                     state at --weakSubjectivity.checkpoint (if
                                     provided, else fetches the latest
                                     finalized) via the
                                     --weakSubjectivity.serverUrl      [boolean]
      --weakSubjectivity.checkpoint  To fetch and start beacon node off a state
                                     at the provided weakSubjectivity
                                     checkpoint, to be supplied in
                                     <blockRoot>:<epoch> format. For example,
                                     0x1234:100 will sync and start off from the
                                     weakSubjectivity state at checkpoint of
                                     epoch 100 with block root 0x1234.  [string]
      --weakSubjectivity.serverUrl   Pass in a server url hosting Beacon Node APIs
                                     from which to fetch weak subjectivity
                                     state, required in conjunction with
                                     --weakSubjectivity.syncLatest or
                                     --weakSubjectivity.checkpoint.     [string]
```

**Review by wemeetagain — DISMISSED** [review]
LGTM

@dapplion lets coordinate on merging this since this is a breaking change

**Review by dapplion — CHANGES_REQUESTED** [review]
I set request changes to "block" this PR:

After using Lodestar for a while compared to other clients the dot notation in CLI arguments is really weird. I think the original @wemeetagain 's reasoning was to map to how the options are in the BeaconOptions Javascript object.

I propose to drop all `group.arg` notation in favor of regular arguments with dash notation. That will make using lodestar CLI more similar to any other CLI out there. Also we can expose the dot notation only for hidden override of BeaconOptions like we have now for params.

Let me know your thoughts.

Regarding this PR I would leave everything as is for now (close PR) and tackle the options refactoring latter after coming to consensus on what options to expose and good though out names

**Comment by dapplion** [comment]
@g11tech If you want you can still group the current arguments in the CLI help because it's a non breaking change improvement. Also add the nice docs you wrote which are super helpful!

**Comment by g11tech** [comment]
> @g11tech If you want you can still group the current arguments in the CLI help because it's a non breaking change improvement. Also add the nice docs you wrote which are super helpful!

@dapplion  wohoo!!! :rocket: :heart: . made the args change non breaking. now the helps looks like:
```
weakSubjectivity
      --weakSubjectivityStateFile   Path or URL to download a weak subjectivity
                                    state file in ssz-encoded format    [string]
      --weakSubjectivitySyncLatest  Sync and start from a weak subjectivity
                                    state at --weakSubjectivityCheckpoint (if
                                    provided, else fetches the latest finalized)
                                    via the --weakSubjectivityServerUrl[boolean]
      --weakSubjectivityServerUrl   Pass in a server url hosting Beacon Node
                                    APIs from which to fetch weak subjectivity
                                    state, required in conjunction with
                                    --weakSubjectivitySyncLatest or
                                    --weakSubjectivityCheckpoint.       [string]
      --weakSubjectivityCheckpoint  To fetch and start beacon node off a state
                                    at the provided weakSubjectivity checkpoint,
                                    to be supplied in <blockRoot>:<epoch>
                                    format. For example, 0x1234:100 will sync
                                    and start off from the weakSubjectivity
                                    state at checkpoint of epoch 100 with block
                                    root 0x1234.                        [string]

```

**Review by dapplion — APPROVED** [review]
Looks great! :heart:

**Comment by wemeetagain** [comment]
I don't think dot notation is that weird.
For some reference, run `geth --help` and look at their cli options.

**Review by wemeetagain — APPROVED** [review]

**Comment by dapplion** [comment]
> I don't think dot notation is that weird. For some reference, run `geth --help` and look at their cli options.

Good point! Let's open an issue an survey consensus

**Pull request merged**
