### PR TITLE
fix: update the gossip message size checks

### PR DESCRIPTION
**Pull request by g11tech**
some updates

ref: https://github.com/ethereum/consensus-specs/pull/4041

~~DONOT MERGE YET waiting on consensus~~ 
~Update: 3/5 clients have agreed to increase it~

### CODE REVIEW

**Review by ensi321 — APPROVED** [review]
lgtm

We probably need to think more about the gas limit issue. Including checking on the uncompressed size, and also checking if builder is honouring the gas limit etc. Ideally to have uncompressed size check either in this or next release.

**Comment by nflaig** [comment]
Lets get consensus with other client teams on this first before merging anything, putting into draft for now

**Comment by philknows** [comment]
My perception based on Consensus-layer Call 147 is that changes to `MAX_CHUNK_SIZE` and `GOSSIP_MAX_SIZE` pre-Pectra should only be changed for emergency purposes only and decision to increase should be done for the fork.

**Comment by ensi321** [comment]
Closing as we have decided not to increase the gossip limit per ACDC#147

**Pull request closed without merging**
