### PR TITLE
chore: release 1.9.0

### PR DESCRIPTION
**Pull request by wemeetagain**

### CODE REVIEW

**Comment by twoeths** [comment]
attaching the profile on main thread (this is a 3h node, gossi
[0526_mainnet_v1.9.0_rc.0.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/11573582/0526_mainnet_v1.9.0_rc.0.cpuprofile.zip)
p sub messages are just half of its usual volume)

**Comment by dapplion** [comment]
>  attaching the profile on main thread (this is a 3h node, gossi
[0526_mainnet_v1.9.0_rc.0.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/11573582/0526_mainnet_v1.9.0_rc.0.cpuprofile.zip)
p sub messages are just half of its usual volume)

This CPU results are pretty nice, the node spend 490000 ms idle and 118160 ms busy (19%). All percentages displayed are relative to busy times. This benchmark shows new hot paths that rise in percentage as the node is so idle. 

However I agree that the fork-choice should not have such a dominant share, hotpaths should be: hashing and crypto

**Comment by twoeths** [comment]
attaching the profile of network thread, this was taken from VsCode with promise tracking
[0528_v1.9.0_rc.0_network_thread.cpuprofile.zip](https://github.com/ChainSafe/lodestar/files/11583810/0528_v1.9.0_rc.0_network_thread.cpuprofile.zip)

**Comment by wemeetagain** [comment]
Closing as this ended up being too unstable

**Pull request closed without merging**
