### PR TITLE
chore: add capella state transition perf tests

### PR DESCRIPTION
**Pull request by dapplion**
**Motivation**

The mainnet beacon chain state has grown a lot, add performance tests for current mainnet test 

**Description**

Add capella state transition perf tests

### CODE REVIEW

**Comment by dapplion** [comment]
Results in CI

```
   capella processEpoch - mainnet_e217614
Downloading file https://github.com/dapplion/ethereum-consensus-test-data/releases/download/v0.1.0/state_mainnet_6963647.ssz
    ✔ capella processEpoch - mainnet_e217614                             0.9132258 ops/s    1.095019  s/op        -         23 runs   26.4 s
    capella processEpoch steps - mainnet_e217614
      ✔ mainnet_e217614 - capella beforeProcessEpoch                        4.135378 ops/s    241.8159 ms/op        -         82 runs   20.6 s
      ✔ mainnet_e217614 - capella processJustificationAndFinalization       48902.15 ops/s    20.44900 us/op        -       1104 runs   2.49 s
      ✔ mainnet_e217614 - capella processInactivityUpdates                  65.48910 ops/s    15.26972 ms/op        -         29 runs   1.01 s
      ✔ mainnet_e217614 - capella processRewardsAndPenalties                2.847790 ops/s    351.1494 ms/op        -         70 runs   25.4 s
      ✔ mainnet_e217614 - capella processRegistryUpdates                    33606.67 ops/s    29.75600 us/op        -       2186 runs   3.56 s
      ✔ mainnet_e217614 - capella processSlashings                           1162791 ops/s    860.0000 ns/op        -       1975 runs   3.19 s
      ✔ mainnet_e217614 - capella processEth1DataReset                       1168224 ops/s    856.0000 ns/op        -       1315 runs   2.49 s
      ✔ mainnet_e217614 - capella processEffectiveBalanceUpdates            243.0548 ops/s    4.114298 ms/op        -         61 runs  0.939 s
      ✔ mainnet_e217614 - capella processSlashingsReset                     321853.9 ops/s    3.107000 us/op        -       1505 runs   2.69 s
      ✔ mainnet_e217614 - capella processRandaoMixesReset                   151148.7 ops/s    6.616000 us/op        -       3743 runs   5.11 s
      ✔ mainnet_e217614 - capella processHistoricalRootsUpdate              927643.8 ops/s    1.078000 us/op        -       5208 runs   6.94 s
      ✔ mainnet_e217614 - capella processParticipationFlagUpdates           309981.4 ops/s    3.226000 us/op        -       1122 runs   2.45 s
      ✔ mainnet_e217614 - capella afterProcessEpoch                         3.335558 ops/s    299.7999 ms/op        -         12 runs   5.43 s
```

**Review by twoeths — APPROVED** [review]
The statistics are not close to mainnet, I think we need to improve our perf test with more validators

**Comment by dapplion** [comment]
> The statistics are not close to mainnet, I think we need to improve our perf test with more validators

Note I used a real state from mainnet from yesterday so the number of validators is ok. What can deviate metrics in production is peripheral use making the machine overloaded, etc.

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.10.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.10.0) :tada:

**Pull request merged**
