### PR TITLE
Validate attestation source target head for inclusion

### LINKED ISSUE #2909: Invalid attestations included in blocks
**Describe the bug**

Lodestar blocks include attestations voted for orphaned head, for example https://altair-devnet-2-explorer.ethdevops.io/block/351#attestations and https://altair-devnet-2-explorer.ethdevops.io/block/407#attestations

**Expected behavior**

We should only include attestations with correct source, target and head.

**Steps to Reproduce**

Join `altair-devnet-2`

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

+ When lodestar validator becomes proposer, we include attestations with orphaned head
+ Some block has up to 37 attestations like in https://altair-devnet-2-explorer.ethdevops.io/block/351

**Description**

+ Validate attestation source, target, head before we include them to block
+ Notice that we want to cache block roots during the process to avoid having to get it from the tree

Closes #2909

**Tested with altair-devnet-2**
+ Test result with`curl http:///localhost:9596/eth/v1/validator/blocks/${slots}?randao_reveal=0x1b66ac1fb663c9bc59509846d6ec05345bd908eda73e670af888da41af171505cc411d61252fb6cb3fa0017b679f8bb2305b26a285fa2737f175668d0dff91cc1b66ac1fb663c9bc59509846d6ec05345bd908eda73e670af888da41af171505`

|Slot|Result|In explorer - client|
|----|------|------------------|
|6633|4x6632 attestations|4x6632 attestations - Lighthouse|
|6643|5x6642, 1x6641 attestation (correct head)|same - Lodestar|
|6652|4x6651 attestations|4x6651 attestations - Lighthouse|

### CODE REVIEW

**Comment by dapplion** [comment]
@tuyennhv If it economically viable we should include incorrect target and head attestations. We must only validate that the source is correct. In the future we should have a better packing algorythm that sorts attestations by economical value properly accounting for correct head and target.

**Comment by twoeths** [comment]
@dapplion I only see we validate attestation head and target at gossip validation https://github.com/ChainSafe/lodestar/blob/40358ff5786763f1e417d8ad2ef2a720ce30d0e4/packages/lodestar/src/chain/validation/aggregateAndProof.ts#L57

**Comment by dapplion** [comment]
> @dapplion I only see we validate attestation head and target at gossip validation
> 
> https://github.com/ChainSafe/lodestar/blob/40358ff5786763f1e417d8ad2ef2a720ce30d0e4/packages/lodestar/src/chain/validation/aggregateAndProof.ts#L57

We do validate the source but in a less obvious optimized way

**Comment by twoeths** [comment]
> > @dapplion I only see we validate attestation head and target at gossip validation
> > https://github.com/ChainSafe/lodestar/blob/40358ff5786763f1e417d8ad2ef2a720ce30d0e4/packages/lodestar/src/chain/validation/aggregateAndProof.ts#L57
> 
> We do validate the source but in a less obvious optimized way

could you link the line of code here? if we already validate source in gossip, maybe we don't have to do it here.

**Comment by twoeths** [comment]
just found this log in `altair-devnet-2` logs:
```
 Aug-03 10:18:24.104 [API]             ^[[31merror^[[39m: Req req-p1hh produceBlock error message=Attestation source does not equal justified checkpoint: source={"epoch":"110        7","root":"0x21ce5deed38b1965e59180f75fe414f85eaaf203e1e10e0b67699a3bca7eb158"} justifiedCheckpoint={"epoch":"1108","root":"0x822fe00309a976bf69cfd4fb6289c8f45f0e6912534b2c1        0d4c0f80406a18b4f"}
3748488 Error: Attestation source does not equal justified checkpoint: source={"epoch":"1107","root":"0x21ce5deed38b1965e59180f75fe414f85eaaf203e1e10e0b67699a3bca7eb158"} justifiedC        heckpoint={"epoch":"1108","root":"0x822fe00309a976bf69cfd4fb6289c8f45f0e6912534b2c10d4c0f80406a18b4f"}
3748489     at getAttestationParticipationStatus (/usr/app/node_modules/@chainsafe/lodestar-beacon-state-transition/src/altair/block/processAttestation.ts:115:11)
3748490     at processOp (/usr/app/node_modules/@chainsafe/lodestar-beacon-state-transition/src/altair/block/processAttestation.ts:52:52)
3748491     at processOperations (/usr/app/node_modules/@chainsafe/lodestar-beacon-state-transition/src/altair/block/processOperations.ts:48:7)
3748492     at Object.processBlock [as altair] (/usr/app/node_modules/@chainsafe/lodestar-beacon-state-transition/src/altair/block/index.ts:32:3)
3748493     at Object.processBlock (/usr/app/node_modules/@chainsafe/lodestar-beacon-state-transition/src/allForks/stateTransition.ts:92:5)
3748494     at computeNewStateRoot (/usr/app/node_modules/@chainsafe/lodestar/src/chain/factory/block/index.ts:59:12)
3748495     at assembleBlock (/usr/app/node_modules/@chainsafe/lodestar/src/chain/factory/block/index.ts:42:21)
3748496     at Object.produceBlock (/usr/app/node_modules/@chainsafe/lodestar/src/api/impl/validator/index.ts:145:23)
3748497     at Object.handler (/usr/app/node_modules/@chainsafe/lodestar-api/src/server/utils/server.ts:70:23)
```

even if we validate attestation source at gossip, we still have to do it again at the time of `produceBlock` since justified checkpoint may move forward.

**Comment by dapplion** [comment]
> > > @dapplion I only see we validate attestation head and target at gossip validation
> > > https://github.com/ChainSafe/lodestar/blob/40358ff5786763f1e417d8ad2ef2a720ce30d0e4/packages/lodestar/src/chain/validation/aggregateAndProof.ts#L57
> > 
> > 
> > We do validate the source but in a less obvious optimized way
> 
> could you link the line of code here? if we already validate source in gossip, maybe we don't have to do it here.

Oh right, we do not validate the source on gossip. And as you pointed out we must check the source since it may move
```python
    if data.target.epoch == get_current_epoch(state):
        assert data.source == state.current_justified_checkpoint
        state.current_epoch_attestations.append(pending_attestation)
    else:
        assert data.source == state.previous_justified_checkpoint
        state.previous_epoch_attestations.append(pending_attestation)
```

**Review by dapplion — APPROVED** [review]

**Pull request merged**
