### PR TITLE
fix: build error log during esm bundle build

### LINKED ISSUE #6726: `yarn check-types` builds a production bundle and creates untracked files
Since we merged https://github.com/ChainSafe/lodestar/pull/6685, running `yarn check-types` has become really slow and at the same time also creates untracked files (see https://github.com/ChainSafe/lodestar/pull/6685#discussion_r1586631639)

My suggestion is to either revert the PR or come up with a proper solution as of right now this negatively affects developer experience.

It also fails randomly locally, and even in the CI (see https://github.com/ChainSafe/lodestar/pull/6685#discussion_r1586635384)

- [x] fix build error
- [x] no more untracked files as side effect of running build
- [x] `yarn lint` should consistently pass, irrespective of running `yarn check-types` before
- [x] move build out of `yarn check-types` to speed up time to run `yarn check-types` by  25%-30%

### PR DESCRIPTION
**Pull request by nazarhussain**
**Motivation**

Fix the build error during the esm bundle build. 

**Description**

- Fix the build error duirng the esm bundle build. 
- Create degging bundle file when a flag is set. 

Partially addresses #6726

**Steps to test or reproduce**

- Run all tests

### CODE REVIEW

**Review by nflaig — COMMENTED** [review]
This doesn't close https://github.com/ChainSafe/lodestar/issues/6726, just addresses 1 part of it

**Comment by nazarhussain** [comment]
> This doesn't close #6726, just addresses 1 part of it

It's fixes the erorr in bundling and also th untracked files. 

Buildng types beore checking types is a requried thing not a bug.

**Comment by nflaig** [comment]
> Buildng types beore checking types is a requried thing not a bug.

My issue is also about not degrading devex by running a 12s build in check-types, we need a better solution for that. I updated the issue to list out the 4 points explicitly that need to be addressed, this just resolves 2 out of 4 of those, as far as I can see.

**Comment by nazarhussain** [comment]
> > Buildng types beore checking types is a requried thing not a bug.
> 
> My issue is also about not degrading devex by running a 12s build in check-types, we need a better solution for that. I updated the issue to list out the 4 points explicitly that need to be addressed, this just resolves 2 out of 4 of those, as far as I can see.

Feel free to open PR to improve the devx.

**Comment by nflaig** [comment]
> Feel free to open PR to improve the devx.

imo we should not merge a PR with such a negative side effect in the first place

**Comment by nazarhussain** [comment]
> imo we should not merge a PR with such a negative side effect in the first place

That was discussed and merged as testing correct types are more important than devx at the moment. And one should not need to run check-types on all the packages all the time locally, for that we have CI.

**Review by nflaig — APPROVED** [review]

**Comment by nflaig** [comment]
> And one should not need to run check-types on all the packages all the time.

if you do a major refactoring you have to :(

**Comment by nazarhussain** [comment]
> if you do a major refactoring you have to :(

In any refactoring, we should do type checks package by package usually and all packages less often.  

If you have to check types on all packages all the time, then you may reconsider your refactoring strategy.

**Comment by nflaig** [comment]
> all packages all the time

well not all the time, but running a build in check-types seems like a major design flaw to me

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.19.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.19.0) :tada:

**Pull request merged**
