### PR TITLE
ci: assert yarn prints no warnings

### LINKED ISSUE #5115: Add CI step to check no warning of unmet dependency
**Describe the bug**

Discord user reported a yarn warning for unmet dependencies. This is harmless to the user but as part of our "log hygiene" effort we must ensure the warnings are not emitted in the happy case.

We should add a new step in CI that ensures that those warnings are not emitted, by either
- Run some yarn command to check unmet dependencies

or (not prefered)
- Capture yarn install output
- Check for unmet dependencies

### PR DESCRIPTION
**Pull request by dapplion**
**Motivation**

- See https://github.com/ChainSafe/lodestar/issues/5115

**Description**

yarn does not offer a clean way to trigger those warnings. From https://github.com/yarnpkg/yarn/issues/4594 and some local tests --check-files seem to work fine, but I haven't tested on CI before opening this PR

Closes https://github.com/ChainSafe/lodestar/issues/5115

### CODE REVIEW

**Comment by nflaig** [comment]
Looks good but the job succeeds either way are we fine with this behavior for now?

I am not sure we can fix all warnings, most of unmet peer dep warnings were resolved here
- https://github.com/ChainSafe/lodestar/pull/5469

**Comment by dapplion** [comment]
Hmm the script should not succeed actually, there are warnings now. Does yarn emit warnings via stdout or stderr?

**Comment by nflaig** [comment]
This is the output of [the job](https://github.com/ChainSafe/lodestar/actions/runs/5110027191/jobs/9185457601?pr=5565)

```
Run scripts/assert_no_yarn_warnings.sh
yarn install v1.22.19 [1/5] Validating package.json... [2/5] Resolving packages... [3/5] Fetching packages... [[4](https://github.com/ChainSafe/lodestar/actions/runs/5110027191/jobs/9185457601?pr=5565#step:9:5)/[5](https://github.com/ChainSafe/lodestar/actions/runs/5110027191/jobs/9185457601?pr=5565#step:9:6)] Linking dependencies... warning " > @lodestar/reqresp@1.8.0" has unmet peer dependency "libp2p@~0.42.2". warning "workspace-aggregator-fce28fe8-89b4-4e7e-9236-918f9035bc21 > @lodestar/beacon-node > @chainsafe/bls@7.1.1" has unmet peer dependency "@chainsafe/blst@^0.2.4". warning "workspace-aggregator-fce28fe8-89b4-4e7e-9236-918f9035bc21 > @lodestar/beacon-node > prometheus-gc-stats@0.6.4" has incorrect peer dependency "prom-client@>= 10 <= 12". warning "workspace-aggregator-fce28fe8-89b4-4e7e-9236-918f9035bc21 > @lodestar/beacon-node > @multiformats/multiaddr > dns-over-http-resolver > native-fetch@4.0.2" has unmet peer dependency "undici@*". [5/5] Building fresh packages... Done in 71.45s.
There were warnings in yarn install --check-files
```

The script works but we are still exiting with code 0. Probably just have to do `exit 1`

**Comment by dapplion** [comment]
Oh lol, forgot that line

**Review by nflaig — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.10.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.10.0) :tada:

**Pull request merged**
