### PR TITLE
chore: update year on the chainsafe cli notice

### PR DESCRIPTION
**Pull request by nflaig**
**Motivation**

It's 2023 already

**Description**

Update year on the chainsafe cli notice

### CODE REVIEW

**Review by matthewkeil — APPROVED** [review]
Great attention to details!

**Review by wemeetagain — APPROVED** [review]

**Comment by dapplion** [comment]
Why there has to be a year there BTW?

**Comment by philknows** [comment]
> Why there has to be a year there BTW?

Not sure TBH... is this a requirement that was put in there from sometime back in the early days @wemeetagain ? Would prefer for it to be automated, but not a huge deal.

**Comment by nflaig** [comment]
if we want to keep the year could also just do `2018-${new Date().getFullYear()}`

**Comment by wemeetagain** [comment]
Good idea!

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.9.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.9.0) :tada:

**Pull request merged**
