### PR TITLE
Run eslint on test/ too

### PR DESCRIPTION
**Pull request by dapplion**
Eslint is a great tool to catch potential dangerous code practices. It should be run over the test files too. This PR only changes the package.json scripts to run eslint and both src and test. If there is consensus on this change I can start fixing all the issues found by eslint.

```
@chainsafe/lodestar-utils: ✖ 11 problems (2 errors, 9 warnings)
@chainsafe/lodestar-beacon-state-transition: ✖ 38 problems (38 errors, 0 warnings)
@chainsafe/lodestar-validator: ✖ 12 problems (12 errors, 0 warnings)
@chainsafe/lodestar: ✖ 263 problems (122 errors, 141 warnings)
@chainsafe/spec-test-runner: ✖ 49 problems (31 errors, 18 warnings)
@chainsafe/lodestar-cli: ✖ 4 problems (2 errors, 2 warnings)
```

## Progress

- [x] benchmark-utils
- [x] lodestar: https://github.com/ChainSafe/lodestar/pull/1834
- [x] lodestar-beacon-state-transition: https://github.com/ChainSafe/lodestar/pull/1832
- [x] lodestar-cli
- [x] lodestar-config
- [x] lodestar-db
- [x] lodestar-fork-choice
- [x] lodestar-params: https://github.com/ChainSafe/lodestar/pull/1833
- [x] lodestar-spec-test-util
- [x] lodestar-types
- [x] lodestar-utils
- [x] lodestar-validator
- [x] spec-test-runner

### CODE REVIEW

**Comment by 3xtr4t3rr3str14l** [comment]
is this something that's still being worked on?  i find myself running eslint manually on my tests fairly often, so would be cool to have something like this baked into our process

**Comment by dapplion** [comment]
> is this something that's still being worked on? i find myself running eslint manually on my tests fairly often, so would be cool to have something like this baked into our process

Totally! If you want you can lead the effort by turning these settings on in the packages with less development (utils, db) and monitor open PRs on other packages (validator, cli) and do PRs for them once big chunks of work are merged in

**Comment by 3xtr4t3rr3str14l** [comment]
@dapplion going to continue this effort on `P0/lint-fix` branch.  currently turning this on for each package one-by-one.  so far, it's looking like most of them won't have that big of a diff, if any diff at all, off the latest master (it's really `lodestar` and `lodestar-beacon-state-transition` that have the biggest diffs and coincidentally also have active PRs out).  So, I will make a new PR to turn on the linting for all the packages except `lodestar` and `lodestar-beacon-state-transition`, for now (on `P0/lint-test` branch) and then hopefully make a PR for those 2 remaining packages once the relevant PRs are merged (obviously `lodestar` will be the trickiest one in that regard, hah)

**Comment by dapplion** [comment]
> @dapplion going to continue this effort on `P0/lint-fix` branch. currently turning this on for each package one-by-one. so far, it's looking like most of them won't have that big of a diff, if any diff at all, off the latest master (it's really `lodestar` and `lodestar-beacon-state-transition` that have the biggest diffs and coincidentally also have active PRs out). So, I will make a new PR to turn on the linting for all the packages except `lodestar` and `lodestar-beacon-state-transition`, for now (on `P0/lint-test` branch) and then hopefully make a PR for those 2 remaining packages once the relevant PRs are merged (obviously `lodestar` will be the trickiest one in that regard, hah)

Sounds good!

**Pull request closed without merging**
