### PR TITLE
chore: unhide flags relevant for devnets / testing

### PR DESCRIPTION
**Pull request by nflaig**
**Motivation**

Those flags are relevant for devnets or testing and are used quite commonly

**Description**

Unhides the following flags
- `--genesisStateFile` (required to configure custom network)
- `--ignoreWeakSubjectivityCheck` (required in devnets with long non-finality)
- `--persistNetworkIdentity` (has been asked multiple times by users if this options exists)

### CODE REVIEW

**Comment by eniko1556** [comment]
I'm chipping in with some options I use for spinning up custom testnet and validator, that I didn't see in the docs. 

`-keystoresDir`
`--secretsDir`
`--disableKeystoresThreadPool`

And for custom testnets: 
`--eth1.depositContractDeployBlock`
`--network.connectToDiscv5Bootnodes`

I think one more new option is `supernode` which I don't know if lodestar supports, but generally, I see this option in many clients, but many of them hide it. Not sure if it's should be hidden or not.

**Comment by nflaig** [comment]
> -keystoresDir
--secretsDir

Those should all not be relevant, you can just use the default values and only configure the storage location via `--dataDir`, I think unhiding every single one of the dir options would bloat the CLI reference docs and those are not relevant for 99% of users.

And `disableKeystoresThreadPool` makes the key import slightly faster if you are running in kurtosis but only if insecure keys are used which are really fast to decrypt, otherwise this will make the key import much slower.


> And for custom testnets:

`depositContractDeployBlock` the [default value for this is `0`](https://github.com/ChainSafe/lodestar/blob/8922d55a236db211a56fe6a74d8b19d315da8b08/packages/beacon-node/src/eth1/options.ts#L26), I don't think it's required to set this at all for post-merge networks (which all new test networks are at this point).


`--network.connectToDiscv5Bootnodes` is a bit controversial as well as you should not have to set this, usually bootnodes are there to discover peers, not to use as peers (and many don't even run libp2p). So I would rather tend towards keeping this flag hidden.

**Review by wemeetagain — APPROVED** [review]
LGTM

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.24.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.24.0) :tada:

**Pull request merged**
