### PR TITLE
fix: sync cached balance when adding new validator to registry

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

Got "invalid state root" issue in mekong

```
debug: Block error slot=143681, code=BLOCK_ERROR_INVALID_STATE_ROOT, slot=143681, root=0xbffe8157d89ac64e41c6e856b91f2a26229d06183cbeff804df82ef460f3971e, expectedRoot=0x1b43fb4c8e07039aa3c28255899f385671ad499759b047465f144005f6a7a1f8
```

**Description**

- we did not sync cached balance when adding a new validator to registry. When top up in 2nd deposit, the cached balance is undefined hence the `processEffectiveBalanceUpdates` is not correct

Closes #issue_number

**Testtomg**
- [x]  I was able to reproduce the issue in unit test [here](https://gist.github.com/twoeths/f5e78905bc59610df2656b6c580a74e7)
- [ ] however it does not work in my node, still got same issue

### CODE REVIEW

**Comment by twoeths** [comment]
the latest [commit](https://github.com/ChainSafe/lodestar/pull/7255/commits/6469a690b9ce7f1f4ada2bdc81dc1d193c84359c)  should fix the issue for a node with existing database

@philknows or @nflaig to confirm 🙏

**Review by nflaig — APPROVED** [review]
LGTM - I am able to sync my node to head from existing db state

**Comment by twoeths** [comment]
was able to reproduce the issue and get the node synced using this branch too

**Comment by twoeths** [comment]
found this in the log `Nov-28 07:16:22.083[chain]            info: Removed persisted checkpoint states from the last run count=33, maxEpochsInMemory=3`

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.23.1](https://github.com/ChainSafe/lodestar/releases/tag/v1.23.1) :tada:

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.24.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.24.0) :tada:

**Pull request merged**
