### PR TITLE
Round up chunk count for list of basic objects

### LINKED ISSUE #397: SSZ: hashTreeRoot never return
**Describe the bug**
This unit test never return
```
it(`should hash correctly with slice/array data`, () => {
    const accountBalances = {
      balances: []
    };
    for (let i = 0; i < 2; i++) {
      accountBalances.balances.push(new BN("32000000000"));
    }
    const accountBalancesType: AnySSZType = {
      fields: [["balances", { elementType: "uint64", maxLength: 2 }]]
    };
    const hash = hashTreeRoot(accountBalances, accountBalancesType).toString(
      "hex"
    );
    assert(hash);
  });
```
This is because of the implementation inside `hashTreeRoot`.
**Expected behavior**
It should return a hash or throw an error

### PR DESCRIPTION
**Pull request by twoeths**
## Goal
+ Close #397 
## Root cause
+ bitLength() function runs forever if input parameter is <0
+ Chunk count is not correct for list of basic objects according to the spec

### CODE REVIEW

**Review by wemeetagain — DISMISSED** [review]
lgtm!
I reverted the code-climate change bc I don't think it actually made things more maintainable

**Review by mpetrunic — DISMISSED** [review]

**Comment by GregTheGreek** [comment]
It seems the minimal spec tests have a large amount of failures, are we out of date somehwere?

**Comment by twoeths** [comment]
> It seems the minimal spec tests have a large amount of failures, are we out of date somehwere?

I missed parentheses, added 1 more unit test to investigate and fix it.

**Comment by twoeths** [comment]
> lgtm!
> I reverted the code-climate change bc I don't think it actually made things more maintainable

Thanks @wemeetagain . So how can we get through this Code Climate "too many returns" check?

**Review by mpetrunic — APPROVED** [review]
Codeclimate is not required check, I will disable too many returns rule in some future PR

**Review by GregTheGreek — APPROVED** [review]

**Comment by GregTheGreek** [comment]
Great work @tuyennhv !!

**Pull request merged**
