### PR TITLE
chore: fix usage of dependant where should be dependent

### PR DESCRIPTION
**Pull request by kevinheavey**
Basically dependant is a noun and dependent is an adjective. There are some places where dependent should be used instead of dependant.

There are also a bunch of cases in the repo where it's not clear which word was intended, but the cases in this PR are clear.

https://www.easybib.com/guides/grammar-guides/vocabulary/confusing-words/dependant-vs-dependent/

### CODE REVIEW

**Comment by nflaig** [comment]
Thanks @kevinheavey, changes look good to me.

There are also code variables that could be updated in this PR

https://github.com/ChainSafe/lodestar/blob/c9226e1eb537a70abe5f81b1a0eeb25dc4b73b0a/packages/beacon-node/src/chain/lightClient/index.ts#L39

https://github.com/ChainSafe/lodestar/blob/c9226e1eb537a70abe5f81b1a0eeb25dc4b73b0a/packages/beacon-node/src/chain/opPools/aggregatedAttestationPool.ts#L453

According to beacon API spec, this should be called [DependentRoot](https://github.com/ethereum/beacon-APIs/blob/197ecffae2b813d94797184ae50387589c601fe7/beacon-node-oapi.yaml#L278-L279) and [dependent_root](https://github.com/ethereum/beacon-APIs/blob/197ecffae2b813d94797184ae50387589c601fe7/apis/validator/duties/attester.yaml#L51)

**Comment by nflaig** [comment]
Just noticed, if you search for "dependant root" you will find a bunch more that should be changed. I checked the consensus and beacon  spec, there is no such thing as dependant root.

**Review by nflaig — APPROVED** [review]
lgtm, thanks @kevinheavey

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.12.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.12.0) :tada:

**Pull request merged**
