### PR TITLE
Add yamux as first streamMuxer

### PR DESCRIPTION
**Pull request by dapplion**
**Motivation**

- Noticed to be required in https://github.com/ChainSafe/lodestar/pull/4774 to interop with external assertions

**Description**

Add yamux as first streamMuxer

**TODO**

Leaving as draft, since before merging we must assert:
- [x] Lodestar can interop in Mainnet correctly
- [ ] Memory consumption + CPU performance is similar
- [x] Gossip throughput in the same
- [x] Gossip scoring appears similar

### CODE REVIEW

**Comment by twoeths** [comment]
I've tested this branch on feat2 mainnet node, there's gossip peer scoring issue that cause the node to have lower mesh peers

- this branch
Screen Shot 2022-12-06 at 14 43 21

- feat1 (same to unstable)
Screen Shot 2022-12-06 at 14 44 16

**Comment by twoeths** [comment]
all metrics look good except for the memory issue, we resolved with #5001

rebasing to latest unstable and deployed to `feat` for the last test

**Comment by wemeetagain** [comment]
marking as ready for review, @tuyennhv feel free to :+1: when you're comfortable

**Comment by dapplion** [comment]
- Closing for issue https://github.com/ChainSafe/lodestar/issues/5804

**Pull request closed without merging**
