### PR TITLE
Update yargs to v17

### PR DESCRIPTION
**Pull request by wemeetagain**
Small thing noticed when trying to add a `--show-hidden` cli option.

Update yargs v16 to v17. Resolves a small typing issue.

### CODE REVIEW

**Review by dapplion — DISMISSED** [review]

**Review by dapplion — DISMISSED** [review]
LGTM

**Review by twoeths — DISMISSED** [review]

**Comment by dapplion** [comment]
@wemeetagain Bad types in e2e test

```
chainsafe/lodestar:   19 passing (1m)
@chainsafe/lodestar:   1 failing
@chainsafe/lodestar:   1) cmds / validator
@chainsafe/lodestar:        should list validators:
@chainsafe/lodestar:      TypeError: validatorPubKeys.sort is not a function
@chainsafe/lodestar:       at Context.<anonymous> (file:///home/runner/actions-runner/_work/lodestar/lodestar/packages/cli/test/e2e/example.test.ts:87:29)
```

**Comment by wemeetagain** [comment]
LGTM, can't approve since I opened the PR

**Review by nflaig — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.8.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.8.0) :tada:

**Pull request merged**
