### PR TITLE
Refactor discovery consumer

### LINKED ISSUE #3395: Improve peer discovery logic
**Describe the bug**

- Get ENRs from discv5 and connect only to peers with matching eth2 field.
- Trigger searches for subnets peers more efficienly

Closes https://github.com/ChainSafe/lodestar/pull/3403

### PR DESCRIPTION
**Pull request by dapplion**
**Motivation**

Our current usage of discv5 is very sub-optimal
- Queries are issued continuously non-stop, finding tons of ENRs
- however, the node struggles to find good peers

**Description**

Moves discv5 into our own PeerManager evicting it from libp2p blackbox. Now we control dials and have access to the ENRs directly.
- Check eth2 field and other metrics to connect only to good ENRs
- Cache good results to prevent continuous queries
- Add many new metrics to have visibility into how optimal this design is. There's a lot to improve still

**Metrics**

Answer the questions:
- How efficiently are we finding relevant ENRs?
- How efficient are our dial attempts?
- How efficient is the cachedENRs mechanism?
- How frequently the app layer is requesting more peers?

Screenshot from 2021-10-30 13-25-34
Screenshot from 2021-10-30 13-25-44

Screenshot from 2021-10-30 13-25-56

Closes https://github.com/ChainSafe/lodestar/issues/3395

### CODE REVIEW

**Comment by dapplion** [comment]
dial time metrics already show cases where a failed dial took 16 minutes.

Screenshot from 2021-10-30 14-05-00

**Comment by dapplion** [comment]
I've tested this PR for 12 hours in Prater nodes (1, 16, and 900 validators) and validator performance has not been changed at all. It seems attestations are propagated properly :+1:

**Comment by twoeths** [comment]
on contabo-0, it shows that we connect to only 1-2 attestation subnet peers a lot of time although we have 7 validators connected to that node. Sometimes the number goes up to 60 and then drop significantly to 1-2.

**Comment by dapplion** [comment]
Screenshot from 2021-11-04 09-30-38

With this branch the scrape timing has uptick-ed significantly. Seems that some metrics are heavy to compute. Need to investigate more

**Review by wemeetagain — APPROVED** [review]
As discussed offline w @dapplion , profitability, performance is unaffected here. Peer discovery from boot is much better. We should merge and continue to refine this.

**Pull request merged**
