### PR TITLE
Tueric/interop refactor process blocks

### PR DESCRIPTION
**Pull request by ec2**

### CODE REVIEW

**Review by wemeetagain — APPROVED** [review]

**Review by mpetrunic — CHANGES_REQUESTED** [review]
Can you remove commented old code?

I would consider moving block processing and it's queue to another class as chain class has way too much code already.

**Comment by ec2** [comment]
> Can you remove commented old code?
> 
> I would consider moving block processing and it's queue to another class as chain class has way too much code already.

I see where you're coming from, and I'm open to doing that. What are your thoughts, @wemeetagain @GregTheGreek ?

**Comment by GregTheGreek** [comment]
I would uninstall the old Queue library, remove old code, but I would hold off on moving the code out to its own class only because we are planning to refactor the whole thing.

**Comment by mpetrunic** [comment]
> I would uninstall the old Queue library, remove old code, but I would hold off on moving the code out to its own class only because we are planning to refactor the whole thing.

Wouldn't moving block process queue to separate class be part of refactor?

**Comment by GregTheGreek** [comment]
> Wouldn't moving block process queue to separate class be part of refactor?

I think we should have a discussion on the overall flow everything before that.

**Comment by wemeetagain** [comment]
I'm thinking we target minimal code changes to get interop merged into master then regroup and refactor more drastically from there.
So, priorities being something that 1. works 2. isn't a total hack and 3. isn't a giant refactor if you can help it.

**Comment by GregTheGreek** [comment]
> I'm thinking we target minimal code changes to get interop merged into master then regroup and refactor more drastically from there.
So, priorities being something that 1. works 2. isn't a total hack and 3. isn't a giant refactor if you can help it.

Yep I agree with this - let's get all outstanding pr's in and then have a discussion on the overall system

**Comment by ec2** [comment]
Cool. Will clean up, and push for another review

**Review by mpetrunic — APPROVED** [review]

**Comment by mpetrunic** [comment]
@tueric you have a lint error though

**Review by GregTheGreek — APPROVED** [review]

**Pull request merged**
