### PR TITLE
fix: handle outOfRangeData when range sync Deneb

### LINKED ISSUE #7248: Mekong: cannot sync from genesis
### Describe the bug

I got a lot of error like this when syncing mekong from genesis:

```
Nov-27 02:51:43.328[sync]            debug: Sync peer joined peer=16Uiu2HAmU1rcw1WaTEfbHs9z7Z9hhjLh93NmfYgRRKs7BYQK2cLZ, syncType=Finalized, startEpoch=0, targetSlot=143616, targetRoot=0x22e6eba7b8292950ab718c43abac6584bffb3d84cfe4cf7b3554d76b0e4b4883
Nov-27 02:51:43.328[sync]            debug: SyncChain added syncType=Finalized, firstEpoch=0, targetSlot=143616, targetRoot=0x22e6eba7b8292950ab718c43abac6584bffb3d84cfe4cf7b3554d76b0e4b4883
Nov-27 02:51:43.328[sync]            debug: SyncChain startSyncing localFinalizedEpoch=0, lastEpochWithProcessBlocks=0, targetSlot=143616
Nov-27 02:51:43.328[sync]          verbose: Batch download error id=Finalized, startEpoch=0, status=Downloading - Cannot sync blobs outside of blobs prune window
Error: Cannot sync blobs outside of blobs prune window
    at beaconBlocksMaybeBlobsByRange (file:///usr/src/lodestar/packages/beacon-node/src/network/reqresp/beaconBlocksMaybeBlobsByRange.ts:50:9)
    at SyncChain.RangeSync.downloadBeaconBlocksByRange (file:///usr/src/lodestar/packages/beacon-node/src/sync/range/range.ts:203:12)
    at SyncChain.sendBatch (file:///usr/src/lodestar/packages/beacon-node/src/sync/range/chain.ts:398:40)
    at SyncChain.requestBatches (file:///usr/src/lodestar/packages/beacon-node/src/sync/range/chain.ts:352:17)
    at SyncChain.triggerBatchDownloader (file:///usr/src/lodestar/packages/beacon-node/src/sync/range/chain.ts:316:12)
    at SyncChain.startSyncing (file:///usr/src/lodestar/packages/beacon-node/src/sync/range/chain.ts:168:10)
    at RangeSync.update (file:///usr/src/lodestar/packages/beacon-node/src/sync/range/range.ts:296:17)
    at RangeSync.addPeer (file:///usr/src/lodestar/packages/beacon-node/src/sync/range/range.ts:132:10)
    at NetworkEventBus.BeaconSync.addPeer (file:///usr/src/lodestar/packages/beacon-node/src/sync/sync.ts:197:22)
    at NetworkEventBus.emit (node:events:532:35)
```

### Expected behavior

no error

### Steps to reproduce

_No response_

### Additional context

_No response_

### Operating system

Linux

### Lodestar version or commit hash

v1.23.0/unstable

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

Cannot sync lodestar from mekong genesis due to this error `Cannot sync blobs outside of blobs prune window`

**Description**

Beacon node should return `BlockInputType.outOfRangeData` block input instead of throwing that error

Closes #7248

### CODE REVIEW

**Review by nflaig — DISMISSED** [review]

**Comment by twoeths** [comment]
not a complete fix, got 
```
Nov-27 06:31:46.242[chain]           error: Error processing finalized checkpoint epoch=132619 - No block found for slot 4243744 root 0x33644e93138cf253cd809458ca2022213ecc282aab3f2f98faaab3de117cc1ec
Nov-27 06:31:55.124[chain]           error: Error processing finalized checkpoint epoch=132620 - No block found for slot 4243744 root 0x33644e93138cf253cd809458ca2022213ecc282aab3f2f98faaab3de117cc1ec
```

the reason is all `archiveBlocks` never finish, and the `archiveBlocks` for epoch n try to reprocess blocks of epoch `n-1`. The first failed is

```
Nov-27 03:13:26.363[chain]           error: Error processing finalized checkpoint epoch=2 - No blobSidecars found for slot 64 root 0xe845c6383893d2ac7e4ec87a3cb836ccaaa4ff9a73f45e64d04ff2f0bb3ddd00
```

**Comment by twoeths** [comment]
was able to sync with this branch from genesis (in progress, not finish yet), the error is gone

```
grep -e "Skip blobSidecars migration" -rn beacon-2024-11-27.log | wc -l
778
```

**Review by nflaig — APPROVED** [review]
Looks good to me, without these changing we can't sync a node post-deneb if blobs are expired already without using checkpoint sync.

The sepolia node is syncing post-deneb without errors while on unstable branch it was just stuck on deneb fork transition.
```
info: Syncing - 4.2 days left - 5.77 slots/s - slot: 6413947 - head: 4308799 0x1ff2…e8c9 - exec-block: valid(5248314 0xe48b…) - finalized: 0xf150…04d4:134648 - peers: 15
info: Syncing - 4.3 days left - 5.65 slots/s - slot: 6413948 - head: 4308831 0xaf60…7e6b - exec-block: valid(5248342 0xa31d…) - finalized: 0xac66…0bf3:134649 - peers: 16
info: Syncing - 4.6 days left - 5.30 slots/s - slot: 6413949 - head: 4308863 0x42c8…7d97 - exec-block: valid(5248374 0x6b22…) - finalized: 0xfb0a…8d20:134650 - peers: 16
```
The `Error processing finalized checkpoint` error is no longer happening.

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.23.1](https://github.com/ChainSafe/lodestar/releases/tag/v1.23.1) :tada:

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.24.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.24.0) :tada:

**Pull request merged**
