### PR TITLE
feat: add giraffe banner for electra fork activation

### PR DESCRIPTION
**Pull request by ensi321**
Need to keep up with the ascii art game. I have two contenders: single or double giraffes.

Feel free to post your banner if you have a better one.

```
                                                                  2048 
                                                                  :++           
                                                                 :-==---        
                                                           :-+=--:-:-+**=:      
                                                       :-=+*=++=-+**+++=+++=-:  
                                                  :-==++++*#=+#+++++*++++-=*#*- 
                                            :---=++=*##+**+%**+::           ::  
                                      ::--=+**++#*=*#++%@#*+-                   
                            ::MAXEB++==*#*+-+###*++*#%#*=:                      
                         :-+==++=*#%%*-*##*=+**#%@%*=-:                         
                        -=**=+%*=*+*#++#***#%#*##=:                             
                     :-++===+**=*@%*=*#*+%@@#+:                                 
                  :-+-*##++==###+*#+#%@@*=-:                                    
  32      :-:--=+-**+===+*%*=*%%++#**+-:                                        
     ::-===*=*+*++=+#%#=*@@%+=+=+%@%*:                                          
   :-*=+#*=**==++*+=**#+%%#+*%%*=*****-                                         
  -*=+==+=+%@*-#*+%@%%**%%#=**=#%#+%%@*                                         
 :==+-+*=*=***#+#%%##%*#@@#=@@+%%#*+**:                                         
 : -*=*+#+=%*#%*#%#+##***+**%***+###*                                           
   -*+#+**+*+=*+*%**#%%*==++++@%++===                                           
   :++*+#%**++==++*###*+**+--+**++---                                           
    ==+*+++++=: ::------::  +*+*=+-==                                           
    -=+++=+=-               -+*+ ==+-                                           
    -======:                -++- --+-                                           
   :=--=-=:                 :++: :==-                                           
   +==--=-                  :==   --=                                           
  :+==---                    ::   :--:                                          
   -====:                     -:   -==                                          
   :-:==                     :-    :=-                                          
    : --                     :-    -:                                          
    : --                     :-    :-                                          
    : --                     ::      -:                                         
    : -=:                    ::      --                                         
    - -=:                    :-      -=-                                        
    ::-=-                    --:      ==:                                       
   : : :=-:                  ::::     :--:                                      
    :::                       :                                                 
`;
```

### CODE REVIEW

**Comment by nflaig** [comment]
```ts
export const ELECTRA_GIRAFFE_BANNER = String.raw`
                                                                                 
           A--A
       .-./   #\.-.
      '--;d    b;--'
         \# \/  /
          \'--'/
           |==|
           | #|
           |# |
          /   #\
         ;   #  ;
         | #    |
        /|  ,, #|\
       /#|  ||  | \
   .-.'  |# ||  |# '.-.
  (.=.),'|  ||# |',(.=.)
   '-'  /  #)(   \  '-'
        '""'  '""'
---------------------------------------------------------
  --  ___  ----  __   --  ___  ----  __ ---   ____   ---- 
--   __ -- _____ ---  __ --   __ -- _____ --- __  ----  _
`;

```

Got this one but there is no theme to it, I like yours more

**Comment by philknows** [comment]
I like yours @ensi321

**Comment by wemeetagain** [comment]
can you print the banner in the description for posterity?

**Comment by ensi321** [comment]
Closing in favour of #7286

**Pull request closed without merging**
