### PR TITLE
HttpClient: log request and response

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

Similar to the node side, we want to debug when we request and get response from validator side

**Description**

part of #3911

### CODE REVIEW

**Comment by dapplion** [comment]
Warning! This is a breaking change to the API of lodestar-api. If we are gonna do the breaking change let's review the interface and ensure it doesn't change in the short - medium term again

**Comment by twoeths** [comment]
> Warning! This is a breaking change to the API of lodestar-api. If we are gonna do the breaking change let's review the interface and ensure it doesn't change in the short - medium term again

This follows our convention `constructor(options, modules)`, and `modules` could be extended in the future.

@dapplion do you know any apps use our `api` interface except for lodestar?

**Comment by g11tech** [comment]
> > Warning! This is a breaking change to the API of lodestar-api. If we are gonna do the breaking change let's review the interface and ensure it doesn't change in the short - medium term again
> 
> This follows our convention `constructor(options, modules)`, and `modules` could be extended in the future.
> 
> @dapplion do you know any apps use our `api` interface except for lodestar?

the light client demo, but i guess its easily updated :+1:

**Review by wemeetagain — DISMISSED** [review]
LGTM

I think the breaking change is fine, aligns with the 'style' of our other code and makes it easier to add more modules to the client if we need.

**Comment by dapplion** [comment]
> LGTM
> 
> I think the breaking change is fine, aligns with the 'style' of our other code and makes it easier to add more modules to the client if we need.

:+1: sounds good to me.

Can we wait for https://github.com/ChainSafe/lodestar/pull/3914 ? the http client will have access the routeId and makes for nicer logging that dumping the full url.

**Review by dapplion — APPROVED** [review]

**Pull request merged**
