### PR TITLE
Reorganize source files under src/

### PR DESCRIPTION
**Pull request by wemeetagain**
~Current diff is unreadable, wait for #115 to land and I'll rebase~

Addresses half of #117 

- Move all source files under beaconChain/src/
  - `lib/` is renamed `src/`
  - `constants/`, `forkChoice/`, `helpers/`, `node/`, `pow/`, `types/` moved under `src/`
- Edit `src/` and `tests/` imports to link up
- Edit `package.json` to point to `src/` - our linting was not fully operational
- Fix linting errors uncovered
- Update `nyc.json` to point to `src/`

### CODE REVIEW

**Review by GregTheGreek — APPROVED** [review]
LGTM

**Comment by GregTheGreek** [comment]
Also, the CI seems to have failed on `npm test`

**Comment by wemeetagain** [comment]
@GregTheGreek 
I'm seeing the tests passing.
There's a codecov/patch failure though, I think because of our lack of tests?

**Comment by GregTheGreek** [comment]
Weird it was failing a second ago...

**Review by ansermino — APPROVED** [review]

**Pull request merged**
