### PR TITLE
chore: release v1.21.0

### PR DESCRIPTION
**Pull request by wemeetagain**
replaces https://github.com/ChainSafe/lodestar/pull/6988

as discussed in discord, we decided to cut a new release candidate off our latest unstable (30a13f91f)

### CODE REVIEW

**Review by philknows — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.21.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.21.0) :tada:

**Comment by twoeths** [comment]
there is signifiant improvement on `beforeProcessEpoch`, this is on lg1k after we deploy v1.21.0:

Screenshot 2024-08-12 at 08 34 20

there is also more mesh peers, this is on the stable mainnet node

Screenshot 2024-08-12 at 08 34 59

Attcount with >0 mesh peers is a little bit improved

Screenshot 2024-08-12 at 08 36 58

also there is higher rss + process heap bytes, could be due to napi-rs:

Screenshot 2024-08-12 at 08 39 43

**Comment by twoeths** [comment]
[v1.21.0_beta-md64_main.cpuprofile.zip](https://github.com/user-attachments/files/16576719/v1.21.0_beta-md64_main.cpuprofile.zip)
[v1.21.0_beta-lg1k_main.cpuprofile.zip](https://github.com/user-attachments/files/16576720/v1.21.0_beta-lg1k_main.cpuprofile.zip)
[v1.21.0_beta-mainnet_main.cpuprofile.zip](https://github.com/user-attachments/files/16576721/v1.21.0_beta-mainnet_main.cpuprofile.zip)
[v1.21.0_beta-md64_network.cpuprofile.zip](https://github.com/user-attachments/files/16576722/v1.21.0_beta-md64_network.cpuprofile.zip)
[v1.21.0_beta-lg1k_network.cpuprofile.zip](https://github.com/user-attachments/files/16576723/v1.21.0_beta-lg1k_network.cpuprofile.zip)
[v1.21.0_beta-mainnet_network.cpuprofile.zip](https://github.com/user-attachments/files/16576724/v1.21.0_beta-mainnet_network.cpuprofile.zip)
[v1.21.0_beta-md64_discv5.cpuprofile.zip](https://github.com/user-attachments/files/16576725/v1.21.0_beta-md64_discv5.cpuprofile.zip)
[v1.21.0_beta-lg1k_discv5.cpuprofile.zip](https://github.com/user-attachments/files/16576726/v1.21.0_beta-lg1k_discv5.cpuprofile.zip)
[v1.21.0_beta-mainnet_discv5.cpuprofile.zip](https://github.com/user-attachments/files/16576727/v1.21.0_beta-mainnet_discv5.cpuprofile.zip)

**Comment by twoeths** [comment]
also gc time on the stable mainnet node is a little bit improved (this is 6h rate interval)

Screenshot 2024-08-12 at 08 45 52

**Pull request merged**
