### PR TITLE
feat: add block proposal summary metric to validator monitor

### PR DESCRIPTION
**Pull request by dapplion**
**Motivation**

- Simplified version of https://github.com/ChainSafe/lodestar/pull/5448 following the pattern of https://github.com/ChainSafe/lodestar/pull/5602

**Description**

|  | Original approach | This PR |
| -- | -- | -- |
| Tracked data | Proposal stats for all validators in the network + local tracked ones | Only local validators |
| When persists data to metrics | At finalization | After one epoch |
| Re-org resistance | Handles re-orgs of any depth | Handles re-orgs of up to SLOTS_PER_EPOCH |
| Complexity | Affects / depends on Archiver, ProposerCache, and StateCache. Requires adding a field in fork choice blocks | Requires caching the previous block proposers in CachedState. Only modifies validator monitor |

IMO this PR achieves a similar goal of best effort observability at less complexity cost. We really only need to debug what happened to our own proposals. For network wide metrics one should use explorers.

@g11tech Can you please double check if any of the deleted functionality is critical for your original purpose?

----

Marking as draft as it depends on https://github.com/ChainSafe/lodestar/pull/5602, and needs updated dashboards

### CODE REVIEW

**Comment by g11tech** [comment]
looks good :+1:

**Comment by wemeetagain** [comment]
I think the diff is messed up here

**Comment by dapplion** [comment]
> I think the diff is messed up here

It looks good to me. This PR reverts https://github.com/ChainSafe/lodestar/pull/5448 plus implements a new strategy implemented in a completely different place

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.10.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.10.0) :tada:

**Pull request merged**
