### PR TITLE
v1.1.0 release

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**

Release v1.1.0

### CODE REVIEW

**Review by g11tech — APPROVED** [review]
LGMT!

**Comment by g11tech** [comment]
Stable mem metrics
image

**Comment by twoeths** [comment]
some great gossipsub metrics with v1.1.0:

- 98% of peers are mesh peers
Screen Shot 2022-09-27 at 17 34 40

- better peer score
Screen Shot 2022-09-27 at 17 35 17

- number of subnets with mesh peers are consistently 64
Screen Shot 2022-09-27 at 17 35 42

**Comment by twoeths** [comment]
some down side due to too many mesh peers
- We drop more attestation gossip messages
Screen Shot 2022-09-27 at 17 37 12

- gossipsub has to send / receive more messages
Screen Shot 2022-09-27 at 17 37 48

==> this is the main cause for the I/O lag issue introduced in #4600

**Pull request merged**
