### PR TITLE
test: consolidate sim-merge tests

### PR DESCRIPTION
**Pull request by nazarhussain**
**Motivation**

Consolidate the sim tests, to minimize the CI run time and reduce maintenance effort. 

**Description**

- Move assertions from `merge-interop.test.ts` to `multi_fork.test.ts`
- Remove  `merge-interop.test.ts`

**Steps to test or reproduce**

- Run all tests

### CODE REVIEW

**Comment by nazarhussain** [comment]
@g11tech Please review, if there is any assertion left in `merge-interop.test.ts` but not covered in `multi_fork.test.ts`

**Review by g11tech — DISMISSED** [review]
lets observe sim tests reliability, and then review this if things on sim tests are stable (blocking it till then)

**Comment by nazarhussain** [comment]
Tried locally and on CI many consecutive runs. With recent changes made to improve sim tests, it's stability seem good now. 
https://github.com/ChainSafe/lodestar/actions/workflows/test-sim.yml
image


@wemeetagain @g11tech I feel it's good to review/merge this PR.

**Comment by nflaig** [comment]
Sim merge tests seem to be stuck, running for almost 3 hours already

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
:tada: This PR is included in [v1.17.0](https://github.com/ChainSafe/lodestar/releases/tag/v1.17.0) :tada:

**Pull request merged**
