### PR TITLE
feat: swap @chainsafe/bls to use napi blst implementation

### PR DESCRIPTION
**Pull request by matthewkeil**
**Motivation**

DRAFT PR.  Not ready for full review.

Branch is deployed to `feat2` to collect metrics

**Description**

Updated `@chainsafe/bls` to use the Napi version of `@chainsafe/blst`.  Added async codepaths to bls processing an added flag to allow selection of `Worker`pool or libuv threadpool.

### CODE REVIEW

**Comment by twoeths** [comment]
gossip block "till received" is somehow 150ms later than unstable + stable mainnet nodes

Screenshot 2024-02-01 at 18 19 12

"till received" is created in gossipsub of network thread

**Comment by twoeths** [comment]
also rss is ~2GB higher than unstable

Screenshot 2024-02-02 at 09 25 10

**Comment by matthewkeil** [comment]
Comparing against stable because unstable has a performance regression. Not sure if that got resolved yet.

All metrics are over a 12hr timeline and 1h moving average with `stable-mainnet` first and then `feat2-mainnet` after:

Screenshot 2024-02-08 at 7 49 48 PM

Screenshot 2024-02-08 at 7 50 02 PM

Screenshot 2024-02-08 at 7 52 41 PM

Screenshot 2024-02-08 at 7 52 46 PM

Screenshot 2024-02-08 at 7 45 18 PM

Screenshot 2024-02-08 at 7 45 25 PM

Screenshot 2024-02-08 at 8 01 58 PM

Screenshot 2024-02-08 at 8 01 30 PM

Screenshot 2024-02-08 at 7 51 26 PM

Screenshot 2024-02-08 at 7 51 38 PM

Screenshot 2024-02-08 at 7 46 14 PM

Screenshot 2024-02-08 at 7 47 53 PM

Screenshot 2024-02-08 at 7 46 48 PM

Screenshot 2024-02-08 at 7 47 38 PM

Screenshot 2024-02-08 at 7 50 20 PM

Screenshot 2024-02-08 at 7 50 28 PM

**Comment by matthewkeil** [comment]
There are some metrics that do not look better and they are listed below. I am trying to figure out why the memory is higher.  I think a piece is that the NAPI objects are larger but it does not account for the whole increase in RSS.  I think the other part is how RSS is reported for worker threads but I am not sure.  I am working on a way to investigate this using the kernel to determine overall memory consumption from outside of the process (from the kernel's perspective).  Will update when I have findings.

Timeline is same as above, 12hr with 1hr `rate() interval` with stable first and feat2 second. 

Screenshot 2024-02-08 at 8 04 04 PM

Screenshot 2024-02-08 at 8 04 11 PM

Screenshot 2024-02-08 at 8 04 26 PM

Screenshot 2024-02-08 at 8 04 33 PM

**Comment by twoeths** [comment]
memory on service deployment is usually higher than that of docker https://github.com/ChainSafe/js-libp2p-gossipsub/pull/468#issuecomment-1931624210

just reviewed the memory in the last 2 days, rss has been stable and decreased over time

Screenshot 2024-02-19 at 11 19 43

**Comment by wemeetagain** [comment]
- Closing in favor of  #6616

**Pull request closed without merging**
