### PR TITLE
JSON friendly logger statements

### LINKED ISSUE #1249: Structured logs
I know it was designed that way, I do think we should minimize nested structures when we can. 
I'm just trying to make our logs more machine readable, and handling arbitrary `Json` IMO is part of the process, especially for debug or verbose-level logs.

IMO, in an ideal setting, we would output logs to JSON-LD format in production, or with a certain "productionized logs" flag.
We would still have a pretty-printer, like in this file, for daily use, but the underlying representation is simply `Json`. This will allow us to easily ingest logs into log aggregators and do more advanced analytics on logs. This is how logging will be used in production settings.
Logs that look like `[CHAIN] "Attestation ${X} processed at epoch ${Y}"` should be refactored into `[CHAIN] "processed attestation", {attestationRoot, epoch}`. Which has a machine representation of `{timestamp: 9999999, module: "chain", message: "processed attestation", attestationRoot, epoch}`

_Originally posted by @wemeetagain in https://github.com/ChainSafe/lodestar/pull/1240#discussion_r461631285_

### PR DESCRIPTION
**Pull request by dapplion**
Make almost all lodestar monorepo logger statements JSON friendly. Fixes https://github.com/ChainSafe/lodestar/issues/1249

Extends the API of the logger to force the error to always be the third argument. This way the error is identified in the JSON renderization and simplifies the logic
```ts
type LogHandler = (message: string, context?: Context, error?: Error) => void
```

### CODE REVIEW

**Comment by dapplion** [comment]
Some `eth2RequestDecode` are failing but I've only modified logger statements. Do those tests depend on stuff being logged out or what can be happening?

```
@chainsafe/lodestar:   1) request encoders
@chainsafe/lodestar:        eth2RequestDecode - request validation
@chainsafe/lodestar:          should yield {isValid: false} if it takes more than 10 bytes for varint:
@chainsafe/lodestar:       AssertionError: expected false to be true
@chainsafe/lodestar:       + expected - actual
@chainsafe/lodestar:       -false
@chainsafe/lodestar:       +true
@chainsafe/lodestar:       
@chainsafe/lodestar:       at Context.<anonymous> (test/unit/network/encoders/request.test.ts:123:57)
```

https://github.com/ChainSafe/lodestar/pull/1837/checks?check_run_id=1507855943#step:9:1138

**Comment by mpetrunic** [comment]
> Some `eth2RequestDecode` are failing but I've only modified logger statements. Do those tests depend on stuff being logged out or what can be happening?
> 
> ```
> @chainsafe/lodestar:   1) request encoders
> @chainsafe/lodestar:        eth2RequestDecode - request validation
> @chainsafe/lodestar:          should yield {isValid: false} if it takes more than 10 bytes for varint:
> @chainsafe/lodestar:       AssertionError: expected false to be true
> @chainsafe/lodestar:       + expected - actual
> @chainsafe/lodestar:       -false
> @chainsafe/lodestar:       +true
> @chainsafe/lodestar:       
> @chainsafe/lodestar:       at Context.<anonymous> (test/unit/network/encoders/request.test.ts:123:57)
> ```
> 
> https://github.com/ChainSafe/lodestar/pull/1837/checks?check_run_id=1507855943#step:9:1138

yup, just change message or for extra credit each validation check could be utility function which can be stubbed and spied. But then each of those utility function should have own unit tests I guess.

**Comment by dapplion** [comment]
> yup, just change message or for extra credit each validation check could be utility function which can be stubbed and spied. But then each of those utility function should have own unit tests I guess.

Asserting a logged statement as a test success sounds really crazy. Not in the scope on this PR, but couldn't this be done more cleanly with custom errors or something?

**Comment by mpetrunic** [comment]
> > yup, just change message or for extra credit each validation check could be utility function which can be stubbed and spied. But then each of those utility function should have own unit tests I guess.
> 
> Asserting a logged statement as a test success sounds really crazy. Not in the scope on this PR, but couldn't this be done more cleanly with custom errors or something?

Possibly, but it's almost the same thing. You change error name/enum and you have to correct tests as well? :slightly_smiling_face:

**Comment by dapplion** [comment]
> Possibly, but it's almost the same thing. You change error name/enum and you have to correct tests as well?

Tests are still failing, could you take a look?

EDIT: All good!

**Review by wemeetagain — APPROVED** [review]

**Pull request merged**
