### PR TITLE
fix: mockExecutionEngine without checking parentHash

### PR DESCRIPTION
**Pull request by yrong**
**Motivation**

Start the beacon node in mock mode without requiring an execution node.

**Description**

https://github.com/ChainSafe/lodestar/discussions/6188

### CODE REVIEW

**Review by nflaig — COMMENTED** [review]
We can't just remove those checks like this a we use the engine mock for testing as well.

I think the engine mock is useful for people that want to quickly spin up a node on any network and we should think about how we can make it so it does not report _syncing_ unless the node is synced from genesis.

Since the engine mock is not secure either way as it does not validate the execution payloads I think removing the parent hash validation doesn't matter much but I would like to hear what others have to say about this.

I am in favor of removing this and for testing, we can explicitly configure the engine mock to do parent hash validation.

**Comment by philknows** [comment]
Made this open for review to get more attention + discussion unless there's a reason why it should stay as a draft @yrong. We'll be discussing this on our standup as the PR has been getting a bit stale. Thanks!

**Comment by nflaig** [comment]
Closed in favor of https://github.com/ChainSafe/lodestar/pull/6872

**Comment by nflaig** [comment]
@yrong we are still considering how to proceed with this, could you further elaborate on your use cases, e.g. what beacon apis do you require to work for testing?

**Comment by yrong** [comment]
> what beacon apis do you require to work for testing?

https://github.com/Snowfork/snowbridge/blob/main/web/packages/test/scripts/fetch-beacon-data.sh

More context we are [snowbridge](https://docs.snowbridge.network/), by leveraging these api to relay beacon finality updates to polkadot. We maintain a [light client](https://github.com/paritytech/polkadot-sdk/blob/master/bridges/snowbridge/pallets/ethereum-client/src/lib.rs) on polkadot to verify these updates.

As you may notice, we don't run a client as validator, just the bridge stuff. So the mock mode makes sense for our use case.

@nflaig More context hope that will be helpful, let me know if anything unclear.

**Comment by nflaig** [comment]
> More context hope that will be helpful, let me know if anything unclear.

Thanks for the details. I am still not clear though why you need to EL to report as synced for this.

The light client apis should work either way.

**Comment by yrong** [comment]
> The light client apis should work either way.

Just confirmed with @claravanstaden testing with lodestar 1.19.0 with flags ```--execution.engineMock --eth1 false``` it seems everything works fine.

So this won't be an issue any more.

**Comment by nflaig** [comment]
> So this won't be an issue any more.

thanks for confirming, we could consider to unhide the flag as it seems generally useful for testing / development

**Pull request closed without merging**
