### PR TITLE
test: update beacon api spec version to 2.4.1

### PR DESCRIPTION
**Pull request by nflaig**
**Motivation**

Compliance to latest beacon api spec ([v2.4.1](https://github.com/ethereum/beacon-APIs/releases/tag/v2.4.1))

**Description**

This branch is used to test our API against latest beacon api spec.

There are several updates required
- ensure operationIds match spec value
- https://github.com/ChainSafe/lodestar/issues/5693
- https://github.com/ChainSafe/lodestar/issues/5542
- https://github.com/ChainSafe/lodestar/issues/5694
- https://github.com/ChainSafe/lodestar/issues/5696
- https://github.com/ChainSafe/lodestar/issues/5697
- https://github.com/ChainSafe/lodestar/issues/5698
- https://github.com/ChainSafe/lodestar/issues/5699
- https://github.com/ChainSafe/lodestar/issues/5700
- https://github.com/ChainSafe/lodestar/issues/5701
- https://github.com/ChainSafe/lodestar/issues/5702
- https://github.com/ChainSafe/lodestar/issues/4638

### CODE REVIEW

**Comment by dapplion** [comment]
Having a jumbo PR bundling all 2.4.1 items is too much, implement an explicit ignore list and go one be one

**Comment by nflaig** [comment]
> Having a jumbo PR bundling all 2.4.1 items is too much

This PR should just be used to keep track of missing items and test against latest spec version, in the end can close it or just merge the spec version update.

> implement an explicit ignore list

Was thinking about that as well, but there is still the issue that some APIs need new parameters for spec tests to pass.

**Comment by dapplion** [comment]
> This PR should just be used to keep track of missing items

To track progress it's best to use issues. This PR seems it will be open for a long time so just best to reference the branch on the issue if it has value.

**Comment by nflaig** [comment]
> To track progress it's best to use issues

Generally agree, but we can check spec compliance programmatically in this case which is not possible if an issue is used. Would have just rebased this branch against unstable after there has been progress on the APIs to get updated results as it will not be possible to update spec tests to 2.4.1 on unstable for a while.

If this branch gets stale or unused after a while if there is no progress we should close it.

Feel free to close is now already if you feel strongly about using an issue instead, will create the according issue then to keep track.

**Comment by dapplion** [comment]
> Feel free to close is now already if you feel strongly about using an issue instead, will create the according issue then to keep track.

Yes please open the issue, I'm just trying to keep our list of open PRs under control :pray: 

To programatically test that a branch passes tests you can trigger a manual workflow

https://github.com/ChainSafe/lodestar/blob/6638ea7ad20bd8a115b77503defbefd856a2379a/.github/workflows/test.yml#L13

**Pull request closed without merging**
